.github/ISSUE_TEMPLATE/bug-report.md
Does what it says on the tin (hopefully).
Resolves https://github.com/okta/odyssey/issues/99
=> add a Bug Report issue template to GH

scripts/publish.sh, scripts/setup.sh
Adds required scripts to our repo for integration with the Bacon publishing setup.
Closes https://github.com/okta/odyssey/issues/150
=> Scripts for Bacon -> NPM publication

.github/ISSUE_TEMPLATE/a11y-issue.md, .github/ISSUE_TEMPLATE/request.md
- add new issue templates
- update bug template slightly
Closes https://github.com/okta/odyssey/issues/187
=> GH Issue Templates

.github/ISSUE_TEMPLATE/a11y-issue.md, .github/ISSUE_TEMPLATE/bug-report.md
- remove unintentional SP reference :joy:
=> Slight tweak to issue templates

README.md, package.json, src/scss/abstracts/_colors.scss, src/scss/abstracts/_functions.scss, src/scss/abstracts/_variables.scss, src/scss/base/_reset.scss, src/scss/base/_typography.scss, src/scss/components/_banner.scss, src/scss/components/_button.scss, src/scss/components/_callout.scss, src/scss/components/_card.scss, src/scss/components/_checkbox.scss, src/scss/components/_dropdown.scss, src/scss/components/_forms.scss, src/scss/components/_label.scss, src/scss/components/_modal.scss, src/scss/components/_radio-button.scss, src/scss/components/_switch.scss, src/scss/components/_table.scss, src/scss/components/_text-input.scss, src/scss/components/_toast.scss, src/scss/components/_tooltip.scss, src/scss/odyssey.scss, src/scss/vendors-ext/_selectize-ext.scss, yarn.lock
- Migrates odyssey codebase from internal repo: this includes all work up until today, completely overriding what was in place.
- Replace "nim" w/ "odyssey" everywhere
- Fixes remaining lint errors
Closes https://github.com/okta/odyssey/issues/204
=> Mass Migration!

src/scss/components/_button.scss
=> Button Borders to 1px

src/scss/components/_button.scss, src/scss/components/_text-input.scss
=> make inputs and buttons use the same height math

packages/docs/source/_data/nav.yml, packages/docs/source/getting-started/status.md, packages/docs/themes/nimatron/source/css/_samples.scss, packages/docs/themes/nimatron/source/css/nimatron.scss
- adds prelim status page to docs
- fixes font-weights throughout
- fixes type size in nav
Closes #426
=> Initial component status page

packages/odyssey/src/scss/components/_input-field.scss
=> Missing ods prefix in label

lerna.json, packages/docs/package.json, packages/odyssey/package.json
Updates all packages to `0.1.0` for release.
=> :package: 0.1.0

packages/docs/source/_data/nav.yml, packages/docs/source/components/tab.md, packages/odyssey/src/scss/abstracts/_mixins.scss, packages/odyssey/src/scss/base/_typography-text.scss, packages/odyssey/src/scss/components/_button.scss, packages/odyssey/src/scss/components/_checkbox.scss, packages/odyssey/src/scss/components/_radio-button.scss, packages/odyssey/src/scss/components/_tab.scss, packages/odyssey/src/scss/odyssey.scss
- Adds tabs component and documentation
- Outline mixin for focusable elements and updates all instances where outlines were styled as one-offs
=> Component: Tabs

packages/docs/source/components/status.md
=> fix: casing in status docs

packages/docs/source/components/modal.md, packages/docs/themes/nimatron/layout/layout.swig
Small PR to change our Modal content element from `main` to `div`
Closes https://github.com/okta/odyssey/issues/567
=> Bug/567 - Modal content element

packages/odyssey/src/scss/abstracts/_mixins.scss, packages/odyssey/src/scss/components/_checkbox.scss, packages/odyssey/src/scss/components/_label.scss, packages/odyssey/src/scss/components/_radio-button.scss
Closes https://github.com/okta/odyssey/issues/570
=> update disabled text colors to text-body for input values and labels

README.md, lerna.json, packages/docs/README.md, packages/docs/package.json, packages/odyssey-icons/README.md, packages/odyssey-icons/package.json, packages/odyssey/CHANGELOG.md, packages/odyssey/package.json, packages/vuepress-theme-nimatron/package.json
Merges our release branch back into `develop`.
=> Maintenance: release 0.4.0 -> develop

packages/docs/components/modal.md
Fixes #635, which created an issue where no modal popped up.
This PR adds in previously removed modal markup.
=> Modal docs fix

.github/workflows/preview.yml, scripts/notify-slack.sh
Adds:
- GitHub Deployments API integration
- Slack Notification script (which deploys to a private channel for the time being)
Removes:
- PR comment notification in favor of GitHub Deployments API
=> 690/691 CD enhancements

.github/CODEOWNERS
Sorry @santhoshbalakrishnan, I meant to get this in before the last release but it totally slipped my mind.
=> Adds Santhosh to CODEOWNERS

packages/docs/base/elements.md, packages/odyssey/src/scss/base/_typography-text.scss
This adds basic styling and some guidance for the uses of `dfn`.
=> Styled Element: dfn/definition

packages/docs/base/elements.md, packages/odyssey/src/scss/base/_typography-text.scss
Adds styling and guidance for the `q` element.
=> Styled Element: <q> (quotation)

packages/docs/base/elements.md, packages/odyssey/src/scss/base/_typography-text.scss
Adds styling for and guidance for using `samp`.
=> Styled Element: <samp> / sample

packages/docs/components/tag.md, packages/odyssey/src/scss/components/_tag.scss
Updates our Overview content for Tag.
We'll need a new Anatomy diagram here @joejezowski-okta, but we can handle that separately if need be.
=> Docs Content: Tag

packages/docs/components/toast.md
Updates content for Toast documentation.
=> Docs Content: Toast

packages/docs/components/tooltip.md, packages/vuepress-theme-odyssey/styles/index.scss
=> Docs Content: Tooltip

packages/docs/components/link.md, packages/docs/components/tooltip.md
Updates docs content for Link.
Includes a small typo fix for Tooltip.
=> Docs content: Link

packages/docs/components/modal.md
Updates docs content for Modal.
@joejezowski-okta I've pulled in all of the Figma content, so this may seem a little crowded. I wanted to ensure we started with the highest level of coverage. 
Also to note, I've changed some of the Anatomy language and updated the descriptions - would appreciate your 👀 there.
@arnoldsandoval-okta the demo doesn't seem to be working here.
=> Docs content: Modal

packages/vuepress-theme-odyssey/components/DocsCardGroup.vue, packages/vuepress-theme-odyssey/components/DocsLink.vue, packages/vuepress-theme-odyssey/components/DocsPagination.vue, packages/vuepress-theme-odyssey/styles/components/_DocsLink.scss, packages/vuepress-theme-odyssey/styles/components/_DocsPagination.scss, packages/vuepress-theme-odyssey/styles/components/_DocsSidebar.scss, packages/vuepress-theme-odyssey/styles/index.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateComponent.scss, packages/vuepress-theme-odyssey/templates/DocsTemplateComponent.vue
* Create DocsPagination component
* Add underline variant to DocsLink
* Add pagination to component docs
=> Add pagination to component docs

packages/prism-theme-odyssey/README.md, packages/prism-theme-odyssey/package.json, packages/prism-theme-odyssey/src/index.html, packages/prism-theme-odyssey/src/index.js, packages/prism-theme-odyssey/src/theme.scss, packages/prism-theme-odyssey/webpack.config.js, packages/vuepress-theme-odyssey/package.json, packages/vuepress-theme-odyssey/styles/index.scss, yarn.lock
Adds `prism-theme-odyssey` package. 
**Note:** This is a private package that is only used in `vuepress-theme-odyssey` at this time. It will not be distributed until someone requests it.
=> Adds prism-theme-odyssey package

packages/docs/components/button.md, packages/docs/components/select.md, packages/docs/components/text-input.md, packages/odyssey/src/scss/vendors-ext/_choices-ext.scss, packages/vuepress-theme-odyssey/styles/docskit/_Visual.scss
Adds content for Select docs.
This also updates the grid layout for Visual examples and adds a background'd variant.
=> Docs Content: Select

packages/docs/.vuepress/config.js, packages/docs/base/index.md, packages/docs/components/index.md, packages/docs/icons.md, packages/docs/index.md, packages/docs/principles.md, packages/vuepress-theme-odyssey/styles/components/_DocsSidebar.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateHome.scss, packages/vuepress-theme-odyssey/templates/DocsTemplateHome.vue
- Updates homepage copy
- Adds principles page
- Adds Roadmap to sidebar
=> Adds home and principles page copy

packages/docs/.vuepress/config.js, packages/vuepress-theme-odyssey/components/DocsNav.vue, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateComponent.scss, packages/vuepress-theme-odyssey/templates/DocsTemplateComponent.vue
=> Show focus outline for component template links, remove external links from docs site

packages/docs/components/status.md
Updates docs content for the Status component.
=> Docs content: Status

packages/docs/base/color.md, packages/docs/base/elements.md, packages/docs/base/tokens.md, packages/docs/base/typography.md, packages/docs/components/button.md, packages/docs/components/checkbox.md, packages/docs/components/modal.md, packages/docs/components/radio-button.md, packages/docs/components/select.md, packages/docs/components/tag.md, packages/docs/components/text-input.md, packages/docs/components/toast.md, packages/docs/components/tooltip.md, packages/vuepress-theme-odyssey/styles/index.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateComponent.scss
- updates description and lead for color, elements, tokens and typography
- Checkbox, Modal, Radio Button and Select HTML/CSS tabs
=> HTML/CSS tab content for Checkbox, Modal, Radio Button, Tag, Text Input, Tooltip, Toast and Select

packages/docs/base/color.md, packages/docs/base/elements.md, packages/docs/base/tokens.md, packages/docs/components/radio-button.md, packages/docs/components/select.md, packages/docs/components/toast.md
misc edits generated during code doc review
=> Docs content: Code example review

packages/docs/components/table.md, packages/odyssey/src/scss/components/_checkbox.scss, packages/odyssey/src/scss/components/_table.scss, packages/vuepress-theme-odyssey/global-components/Description.vue, packages/vuepress-theme-odyssey/styles/docskit/_Description.scss, packages/vuepress-theme-odyssey/styles/docskit/_Visual.scss, packages/vuepress-theme-odyssey/styles/docskit/_coin.scss, packages/vuepress-theme-odyssey/styles/docskit/_marker.scss, packages/vuepress-theme-odyssey/styles/index.scss
Adds content for both Overview and HTML/CSS tabs for Table.
This includes a new variant for Description as well as a new docskit component, "coin".
=> Docs: Table content

.eslintignore, .eslintrc.js, package.json, packages/docs/help.md, packages/prism-theme-odyssey/src/index.js, packages/vuepress-theme-odyssey/.eslintrc.js, packages/vuepress-theme-odyssey/components/DocsCardGroup.vue, packages/vuepress-theme-odyssey/components/DocsPagination.vue, packages/vuepress-theme-odyssey/components/DocsSidebar.vue, packages/vuepress-theme-odyssey/global-components/Anatomy.vue, packages/vuepress-theme-odyssey/global-components/Visual.vue, packages/vuepress-theme-odyssey/package.json, packages/vuepress-theme-odyssey/templates/DocsTemplateHome.vue, packages/vuepress-theme-odyssey/templates/DocsTemplateIndex.vue, packages/vuepress-theme-odyssey/templates/DocsTemplatePlain.vue, yarn.lock
- Adds eslint to monorepo
- Fixes linter errors
=> Adds eslint

packages/docs/beta.md, packages/vuepress-theme-odyssey/components/DocsBanner.vue, packages/vuepress-theme-odyssey/global-components/Description.vue, packages/vuepress-theme-odyssey/layouts/Layout.vue, packages/vuepress-theme-odyssey/styles/components/_DocsBanner.scss, packages/vuepress-theme-odyssey/styles/components/_DocsSidebar.scss, packages/vuepress-theme-odyssey/styles/index.scss
Adds:
- Beta beta notice to homepage
- Beta notice page
- DocsBanner component
=> Add beta notice/docs banner component

packages/docs/.vuepress/config.js, packages/docs/base/typography.md, packages/docs/type-test.md, packages/odyssey/src/scss/abstracts/_tokens.scss, packages/odyssey/src/scss/base/_typography-global.scss, packages/odyssey/src/scss/base/_typography-header.scss, packages/odyssey/src/scss/base/_typography-list.scss, packages/odyssey/src/scss/base/_typography-text.scss, packages/odyssey/src/scss/components/_checkbox.scss, packages/odyssey/src/scss/components/_forms.scss, packages/odyssey/src/scss/components/_input-field.scss, packages/odyssey/src/scss/components/_radio-button.scss, packages/odyssey/src/scss/components/_tab.scss, packages/odyssey/src/scss/components/_table.scss, packages/prism-theme-odyssey/src/theme.scss, packages/vuepress-theme-odyssey/styles/_shame.scss, packages/vuepress-theme-odyssey/styles/components/_DocsCard.scss, packages/vuepress-theme-odyssey/styles/components/_DocsNav.scss, packages/vuepress-theme-odyssey/styles/components/_DocsPageHeader.scss, packages/vuepress-theme-odyssey/styles/docskit/_Description.scss, packages/vuepress-theme-odyssey/styles/docskit/_marker.scss, packages/vuepress-theme-odyssey/styles/index.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateComponent.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateHome.scss
Latest build: https://e635039.ods.dev/
Latest type test: https://e635039.ods.dev/type-test/
Open questions:
- Solving this with Sass math for now; we can move to `calc()` or other once we wrangle custom props.
=> Foundations: Update Type Scale

packages/docs/components/button.md
Update documentation to wrap the button label with a `span.button--label`
=> [OKTA-358478] Wrap button label with span

.github/CODEOWNERS
This swaps UI Core ownership to dependencies-only. This will be revisited once JB has joined the team and infrastructure work begins in earnest.
=> [Internal] Update codeowners for new team setup

packages/docs/components/button.md, packages/odyssey/src/scss/components/_button.scss
Adds a full-width Button variant and examples.
https://0bf2c8a.ods.dev/components/button/
=> Full-width button variant

packages/odyssey/src/scss/base/_typography-text.scss, packages/prism-theme-odyssey/package.json, packages/prism-theme-odyssey/src/demo.scss, packages/prism-theme-odyssey/src/index.html, packages/prism-theme-odyssey/src/index.js, packages/prism-theme-odyssey/src/theme.scss, packages/prism-theme-odyssey/src/utils/CustomPropertyInspector.js, packages/prism-theme-odyssey/webpack.config.js, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateComponent.scss
Updates the `prism-theme-odyssey` theme based on brand design direction from @nickarcidy-okta.
1. The theme is WCAG 2.0 AA compliant
2. Uses all Odyssey colors except for `--functionColor` which is not currently provided by Odyssey but IS a Brand color.
3. Includes `CustomPropertyInspector` which automatically gets the custom properties used in the theme and allows for the user to change the values. This is gated behind the `inspector` query param and works in FF and Safari only. **This is in place so that designers can easily change colors in the future.**
=> Updates Odyssey Prism theme

packages/vuepress-theme-odyssey/components/DocsCard.vue, packages/vuepress-theme-odyssey/global-components/Anatomy.vue, packages/vuepress-theme-odyssey/global-components/Description.vue, packages/vuepress-theme-odyssey/global-components/OdsToast.vue, packages/vuepress-theme-odyssey/layouts/Layout.vue, packages/vuepress-theme-odyssey/templates/DocsTemplateHome.vue
This PR addresses our current existing ESlint violations.
=> eslint cleanup

packages/odyssey/src/scss/components/_checkbox.scss
@joejezowski-okta here's a fix for the updated UI
=> fix(checkbox): ui invalid+disabled+unchecked state

packages/docs/components/radio-button.md, packages/odyssey/src/scss/components/_radio-button.scss
=> fix: radio button disabled no longer reacts to hover

.github/workflows/deployment.yml
see this doc link for [handling multi-line strings](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#multiline-strings)
=> Fix $GITHUB_ENV setup for multiline strings

.eslintignore, .eslintrc.js, package.json, packages/odyssey-eslint/package.json, packages/odyssey-eslint/src/index.js, packages/odyssey-eslint/src/utils/header.js, packages/odyssey-react/.eslintrc.js, packages/odyssey-react/package.json, packages/odyssey-stylelint/.eslintrc.js, packages/odyssey-stylelint/src/rules/header/index.js, packages/prism-theme-odyssey/src/utils/CustomPropertyInspector.js, packages/vuepress-theme-odyssey/.eslintrc.js, yarn.lock
This PR adds a new, private package: `@okta/odyssey-eslint`
This package contains eslint configuration specific to our mono repo
=> feat(odyssey-eslint): add eslint package

packages/odyssey-react/src/components/Tag/Tag.stories.tsx, packages/odyssey-react/src/components/Tag/Tag.test.tsx, packages/odyssey-react/src/components/Tag/index.tsx, packages/odyssey-react/src/components/TextArea/TextArea.stories.tsx
This PR introduces a new `<Tag />` component.
=> feat(odyssey-react): adds tag component

packages/docs/components/status.md, packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/Status/Status.stories.tsx, packages/odyssey-react/src/components/Status/Status.test.tsx, packages/odyssey-react/src/components/Status/index.tsx, packages/odyssey-react/src/index.ts
This PR adds a new `Status` component
=> feat(odyssey-react): adds status component

packages/odyssey-react/src/components/RadioGroup/RadioGroup.stories.tsx, packages/odyssey-react/src/components/RadioGroup/RadioGroup.test.tsx, packages/odyssey-react/src/components/RadioGroup/index.tsx
This PR adds a new `<RadioGroup />` component. See the base branch for more information about the `<Radio />` component
=> feat(odyssey-react): add RadioGroup component

packages/odyssey-react/src/components/Checkbox/Checkbox.stories.tsx, packages/odyssey-react/src/components/Checkbox/Checkbox.test.tsx, packages/odyssey-react/src/components/Checkbox/index.tsx
Adds a new `<Checkbox>` component.
=> feat(odyssey-react): add Checkbox component

packages/odyssey-react/src/components/Banner/Banner.stories.tsx, packages/odyssey-react/src/components/Banner/Banner.test.tsx, packages/odyssey-react/src/components/Banner/index.tsx, packages/odyssey/src/scss/components/_banner.scss
Adds Banner component and tests.
=> feat(odyssey-react): add banner component

package.json, yarn.lock
=> chore: update lerna to 4.0.0 to fix vulnerabilities

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/.storybook/preview.scss, packages/odyssey-react/package.json, packages/odyssey-react/src/components/Tag/Tag.module.scss, packages/odyssey-react/src/components/Tag/index.tsx, packages/odyssey-react/styles.d.ts, packages/odyssey-react/tsconfig.json, packages/vuepress-theme-odyssey/package.json, packages/vuepress-theme-odyssey/styles/index.scss, yarn.lock
[OKTA-416025](https://oktainc.atlassian.net/browse/OKTA-416025)
[OKTA-416115](https://oktainc.atlassian.net/browse/OKTA-416115)
=> feat(odyssey-react): update Tag to use scss module

packages/odyssey-react/src/components/TextArea/TextArea.module.scss, packages/odyssey-react/src/components/TextArea/TextArea.stories.tsx, packages/odyssey-react/src/components/TextArea/index.tsx, packages/odyssey-react/stylelint.config.js
[OKTA-416116](https://oktainc.atlassian.net/browse/OKTA-416116)
=> feat(odyssey-react): update TextArea to use scss module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/TextInput/TextInput.module.scss, packages/odyssey-react/src/components/TextInput/index.tsx
[OKTA-416117](https://oktainc.atlassian.net/browse/OKTA-416117)
=>  feat(odyssey-react): update TextInput to use scss module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/Checkbox/Checkbox.module.scss, packages/odyssey-react/src/components/Checkbox/index.tsx
[OKTA-416107](https://oktainc.atlassian.net/browse/OKTA-416107)
=> feat(odyssey-react): update Checkbox to use scss module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/index.tsx
[OKTA-416111](https://oktainc.atlassian.net/browse/OKTA-416111)
=> feat(odyssey-react): update Link to use scss module

packages/odyssey-react/src/components/Title/Title.test.tsx, packages/odyssey-react/src/components/Title/index.tsx
https://github.com/okta/odyssey/pull/1020#discussion_r685363481
=> feat(odyssey-react): improve Title type annotations

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/Infobox/Infobox.module.scss, packages/odyssey-react/src/components/Infobox/index.tsx, packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/stylelint.config.js
[OKTA-416110](https://oktainc.atlassian.net/browse/OKTA-416110)
=> feat(odyssey-react): update Infobox to use scss module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/Button/Button.module.scss, packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/Button/index.tsx
Adds a CSS Module for Button
Jira: [OKTA-416105](https://oktainc.atlassian.net/browse/OKTA-416105)
=> add Button CSS Module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/Modal/Modal.module.scss, packages/odyssey-react/src/components/Modal/index.tsx
[OKTA-416112](https://oktainc.atlassian.net/browse/OKTA-416112)
=> feat(odyssey-react): update Modal to use scss module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/src/components/Tab/Tab.module.scss, packages/odyssey-react/src/components/Tab/index.tsx
[OKTA-416299](https://oktainc.atlassian.net/browse/OKTA-416299)
=> feat(odyssey-react): update Tabs to use scss module

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/package.json, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/index.ts, packages/odyssey-storybook/tsconfig.json, yarn.lock
separates our storybook preset into a new private package as well
=> feat(odyssey-storybook): add storybook RTL toggle

packages/odyssey-react/src/components/Tooltip/Tooltip.module.scss, packages/odyssey-react/src/components/Tooltip/index.tsx, packages/odyssey-storybook/src/index.ts
Converts our Tooltip to a CSS module. Removes the sass from storybook.
=> add CSS Module for Tooltip

packages/odyssey-react/src/components/Checkbox/Checkbox.module.scss, packages/odyssey-react/src/components/Radio/RadioButton.module.scss, packages/odyssey-react/src/components/Tooltip/Tooltip.module.scss, packages/odyssey-react/stylelint.config.js
[OKTA-419873](https://oktainc.atlassian.net/browse/OKTA-419873)
=> feat: improve css module safety with new lint config

packages/odyssey-react/src/components/Select/Select.module.scss, packages/odyssey-react/src/components/Select/Select/index.tsx, packages/odyssey-react/src/components/Select/Select/useChoices.ts, packages/odyssey-storybook/src/index.ts
A straight port over of styles with renaming.
=> feat(odyssey-react): add select scss module

packages/odyssey-react/src/components/Toast/Toast.module.scss, packages/odyssey-react/src/components/Toast/index.tsx, packages/odyssey-storybook/src/index.ts
[OKTA-423830](https://oktainc.atlassian.net/browse/OKTA-423830)
=> feat(odyssey-react): update Toast/ToastPen to use scss module

packages/odyssey-react/src/components/Toast/Toast.module.scss, packages/odyssey-react/src/components/Toast/Toast.stories.tsx, packages/odyssey-react/src/components/Toast/Toast.test.tsx, packages/odyssey-react/src/components/Toast/index.tsx, packages/odyssey-storybook/src/index.ts
[OKTA-399771](https://oktainc.atlassian.net/browse/OKTA-399771)
=> feature(odyssey-react): add toast

packages/odyssey-react/src/components/Checkbox/Checkbox.module.scss, packages/odyssey-react/src/components/Checkbox/index.tsx, packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/index.tsx, packages/odyssey-react/src/components/Select/Select.module.scss, packages/odyssey-react/src/components/Select/Select/index.tsx, packages/odyssey-react/src/components/Select/Select/useChoices.tsx, packages/odyssey-react/src/components/Table/Table.module.scss, packages/odyssey-react/src/components/Table/TableSortButton.tsx, packages/odyssey-react/src/components/TextInput/TextInput.module.scss, packages/odyssey-react/src/components/TextInput/index.tsx
Replace the use of pseudo element visual indicators with presentational elements in JSX
=> UI visual indicators

packages/odyssey-react/.storybook/decorators/index.ts, packages/odyssey-react/.storybook/decorators/withGlobalReset.tsx, packages/odyssey-react/src/components/Banner/Banner.stories.tsx, packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/Checkbox/Checkbox.stories.tsx, packages/odyssey-react/src/components/FieldLabel/FieldLabel.stories.tsx, packages/odyssey-react/src/components/Infobox/Infobox.stories.tsx, packages/odyssey-react/src/components/Link/Link.stories.tsx, packages/odyssey-react/src/components/Modal/Modal.stories.tsx, packages/odyssey-react/src/components/Radio/Radio.stories.tsx, packages/odyssey-react/src/components/Select/Select.stories.tsx, packages/odyssey-react/src/components/Status/Status.stories.tsx, packages/odyssey-react/src/components/Tab/Tab.stories.tsx, packages/odyssey-react/src/components/Table/Table.stories.tsx, packages/odyssey-react/src/components/Tag/Tag.stories.tsx, packages/odyssey-react/src/components/TextArea/TextArea.stories.tsx, packages/odyssey-react/src/components/TextInput/TextInput.stories.tsx, packages/odyssey-react/src/components/Title/Title.stories.tsx, packages/odyssey-react/src/components/Toast/Toast.stories.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.stories.tsx, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/index.ts, packages/odyssey/src/scss/base/_reset.scss, yarn.lock
[OKTA-419543](https://oktainc.atlassian.net/browse/OKTA-419543)
=> chore(odyssey-react): remove global css reset styles in favor of story decorator

packages/odyssey-react/src/components/Banner/Banner.stories.tsx, packages/odyssey-react/src/components/Banner/Banner.test.tsx, packages/odyssey-react/src/components/Banner/Banner.tsx, packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/Button/Button.test.tsx, packages/odyssey-react/src/components/Button/Button.tsx, packages/odyssey-react/src/components/Modal/Modal.stories.tsx, packages/odyssey-react/src/components/Modal/Modal.test.tsx, packages/odyssey-react/src/components/Modal/index.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.stories.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.test.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.tsx, packages/odyssey-react/src/components/Tooltip/index.ts, packages/odyssey-storybook/src/index.ts
New PR for https://github.com/okta/odyssey/pull/1101 and https://github.com/okta/odyssey/pull/1105
[Tooltip](https://bfeb9c0.ods.dev/?path=/story/components-tooltip--default) + [Modal](https://bfeb9c0.ods.dev/?path=/story/components-modal--default)
=> withStyles Tooltip + Modal

packages/odyssey-react/.postcssrc.js
Thank you @edburyenegren-okta for pointing this out!
=> fix(odyssey-react): production postcssrc config

packages/odyssey-react/package.json, packages/odyssey-react/scripts/prepack.js
fix our public npmjs landing page and update lifecycle scripts
=> chore(odyssey-react): update package repo details

packages/odyssey-react/scripts/buildSource, packages/odyssey-react/scripts/start.js, packages/odyssey-storybook/.storybook/main.js
<details>
<summary>DEMO</summary>
<br>
</details>
Hot module logic will need to be added in the future but that can always be remedied with a CMD+R page refresh 😉
=> chore(odyssey-react): rework start script to compile JS on style changes

lerna.json, package.json, packages/conventional-changelog-odyssey/index.js, packages/conventional-changelog-odyssey/package.json
This PR is focused on improving our release process so that versioning and `CHANGELOG` generation is done programmatically rather than by hand.
=> chore(conventional-changelog-odyssey): add new package

packages/odyssey-commitlint/package.json, packages/odyssey-commitlint/src/index.js, yarn.lock
See more information [here](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular) and [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#type)
=> fix(odyssey-commitlint): use angular lint preset

packages/odyssey-storybook/src/contributing/Documentation.stories.mdx
Adds a copyable documentation template along with a short explainer for each section.
=> Add documentation template

packages/odyssey-storybook/package.json, yarn.lock
[This PR](https://github.com/okta/odyssey/pull/1130) was never merged and got a bit outdated.
Here's an SB-only update to the most current minors.
(Commit should be chore. Will amend on merge.)
=> Update Storybook Dependencies

packages/odyssey-storybook/src/components/Field/Field.docgen.tsx, packages/odyssey-storybook/src/components/Field/Field.mdx, packages/odyssey-storybook/src/components/Field/Field.stories.tsx, packages/odyssey-storybook/src/components/TextInput/TextInput.stories.tsx
This adds docs and stories for Field. It also updates related stories so they can be utilized as examples for Field.
=> Field documentation

packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/components/Select/Select.stories.tsx, yarn.lock
This reverts commit 77683b4eacfd7a7f23f43dbe34f44b3741427113, reversing
changes made to c022c8ccda17898e5fc32c105db7b6af4cc71d9b.
=> chore: Revert "Merge pull request #1196 from okta/ee/update-storybook"

packages/odyssey-react/src/components/Table/TableCell.module.scss, packages/odyssey-react/src/components/Table/TableContainer.module.scss, packages/odyssey-react/src/components/Table/TableContainer.tsx, packages/odyssey-react/src/components/Table/TableDataCell.tsx, packages/odyssey-react/src/components/Table/TableHeaderCell.tsx, packages/odyssey-react/src/components/Table/TableSortButton.module.scss, packages/odyssey-react/src/components/Table/TableSortButton.tsx
follow up PR from some good feedback from @arnoldsandoval-okta [here](https://github.com/okta/odyssey/pull/1212#discussion_r770977515)
=> chore(odyssey-react): rename root classes

packages/odyssey-react/src/components/Table/Table.tsx, packages/odyssey-react/src/components/Table/TableContainer.tsx, packages/odyssey-react/src/components/Table/TableSortButton.tsx
Only adding Box to elements that could stand alone.
=> feat(odyssey-react): add Box to Table

packages/odyssey-design-tokens/src/border.json, packages/odyssey-design-tokens/src/color/background.json, packages/odyssey-design-tokens/src/color/border.json, packages/odyssey-design-tokens/src/color/focus.json, packages/odyssey-design-tokens/src/color/functional.json, packages/odyssey-design-tokens/src/color/text.json, packages/odyssey-design-tokens/src/font.json, packages/odyssey-design-tokens/src/shadow.json, packages/odyssey-design-tokens/src/space.json, packages/odyssey-react/src/components/Box/Box.theme.ts, packages/odyssey-react/src/components/Box/Box.tsx, packages/odyssey-react/src/components/Box/_box-background.scss, packages/odyssey-react/src/components/Box/_box-border.scss, packages/odyssey-react/src/components/Box/_box-hover-focus.scss, packages/odyssey-react/src/components/Box/_box-margin.scss, packages/odyssey-react/src/components/Box/_box-padding.scss, packages/odyssey-react/src/components/Box/_box-root.scss, packages/odyssey-react/src/components/Box/_box-text.scss, packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/Link.theme.ts, packages/odyssey-react/src/components/Status/Status.module.scss, packages/odyssey-react/src/components/Status/Status.theme.ts
This PR adds theme variables for Box, as well as a handful of missing upstream global tokens.
[OKTA-454207](https://oktainc.atlassian.net/browse/OKTA-454207)
=> feat(odyssey-react): withTheme for Box

packages/odyssey-design-tokens/src/color/border.json, packages/odyssey-design-tokens/src/color/text.json, packages/odyssey-design-tokens/src/font.json, packages/odyssey-react/src/components/Box/Box.theme.ts, packages/odyssey-react/src/components/Box/_box-text.scss, packages/odyssey-react/src/components/Button/Button.theme.ts, packages/odyssey-react/src/components/Checkbox/Checkbox.theme.ts, packages/odyssey-react/src/components/Field/Field.tsx, packages/odyssey-react/src/components/Radio/RadioButton.theme.ts, packages/odyssey-react/src/components/Text/Text.module.scss, packages/odyssey-react/src/components/Text/Text.theme.ts, packages/odyssey-react/src/components/Text/Text.tsx, packages/odyssey-storybook/src/components/Text/TextStyles.stories.tsx
BREAKING CHANGE: Text prop fontWeight "regular" renamed to "normal"
BREAKING CHANGE: Text prop color "heading" "danger-disabled" and "code" removed
BREAKING CHANGE: Text prop fontSize "lede" removed
BREAKING CHANGE: Text prop textTransform "full-width" and "full-size-kana" removed
BREAKING CHANGE: Text prop lineHeight "font" removed
BREAKING CHANGE: Text prop overflowWrap "anywhere" removed
=> feat(odyssey-react): withTheme for Text

packages/odyssey-design-tokens/README.md
=> docs(odyssey-design-tokens): update README example

packages/odyssey-react/src/components/TextArea/TextArea.module.scss, packages/odyssey-react/src/components/TextArea/TextArea.test.tsx, packages/odyssey-react/src/components/TextArea/TextArea.tsx, packages/odyssey-storybook/src/components/TextArea/TextArea.mdx, packages/odyssey-storybook/src/components/TextArea/TextArea.stories.tsx
Adding the resize attribute to TextArea. 
[OKTA-464388](https://oktainc.atlassian.net/browse/OKTA-464388)
=> chore(odyssey-react): Adding resize attribute to TextArea

packages/odyssey-babel-preset/CHANGELOG.md, packages/odyssey-postcss-scss/README.md, packages/odyssey-postcss-theme/README.md
This PR improves documentation usage examples and cleans up a CHANGELOG
=> docs: improve documentation examples

.yarnrc
This PR version controlls a yarnrc file in the root of our monorepo. This should allow for fewer headaches for Oktanauts that want to clone our repo and develop locally after strap. [Release script changes are here.](https://github.com/okta/external-build-scripts/pull/19)
=> build: add .yarnrc file

.yarnrc
Fix dev only `.yarnrc` registry TLD
=> build: use correct yarn registry TLD

README.md, packages/browserslist-config-odyssey/README.md, packages/browserslist-config-odyssey/package.json
This PR prepares the `@okta/browserslist-config-odyssey` package for publish to public NPM registries.  [See the release script changes here.](https://github.com/okta/external-build-scripts/pull/19)
=> feat(browserslist-config-odyssey): make package public

scripts/setup.sh
This PR updates the node and yarn version for our bacon setup script used as part of our release process.
=> build: update node and yarn version in setup script

packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/Link.theme.ts
Adds a `:focus` state to link.
=> feat(odyssey-react): add :focus state to Link

packages/odyssey-design-tokens/src/shadow.json, packages/odyssey-react/src/components/Box/Box.theme.ts, packages/odyssey-react/src/components/Toast/Toast.theme.ts
Updates Shadow token names and associated values. Updates Box and Toast to pull from new tokens.
=> Update Shadow tokens

packages/odyssey-react/src/components/TextInput/TextInput.module.scss
Restores native search UI for Chrome, Safari, and IE.
=> feat(odyssey-react): restore native ui functions for TextInput, Search

packages/odyssey-react/package.json, packages/odyssey-react/src/components/Modal/Modal.test.tsx, packages/odyssey-react/src/components/Modal/Modal.tsx, packages/odyssey-react/src/utils/focusHandling.ts, packages/odyssey-react/src/utils/index.ts, packages/odyssey-storybook/src/components/Modal/Modal.stories.tsx, yarn.lock
This PR introduces the following features for the odyssey-react Modal component...
- When the modal is OPEN the first focusable item should receive focus (in the case of the modal it is the Dismiss button)
- The focus should be retained within the bounds of the modal dialog at all times while the modal is in view.
- When the modal is CLOSED the element focused prior to the modal opening should receive focus.
See https://oktainc.atlassian.net/browse/OKTA-419312 (Okta employees only)
NOTE: This PR replaces https://github.com/okta/odyssey/pull/1362
=> OKTA-419312: Improve keyboard focus handling in odyssey-react Modal component via @react-aria/focus

packages/odyssey-storybook/src/components/Button/Button.stories.tsx
This PR fixes the Button theme story!
=> fix(odyssey-storybook): controls for Button theme story

packages/odyssey-storybook/src/components/Button/Button.stories.tsx, packages/odyssey-storybook/src/components/NativeSelect/NativeSelect.stories.tsx
This PR fixes an incorrectly configured Button stories to remove a11y violations in our docs. It also fixes the NativeSelect controlled example to work as it should have been intended.
=> fix(odyssey-storybook): doc examples

packages/odyssey-babel-plugin/src/normalizeOpts.ts, packages/odyssey-babel-plugin/src/plugin.ts
This PR refactors our babel plugin to better support development workflows and conventional configuration.
=> refactor(odyssey-babel-plugin)

packages/odyssey-storybook/src/contributing/GettingStarted.stories.mdx, packages/odyssey-storybook/src/contributing/OdysseyDevelopment.stories.mdx, packages/odyssey-storybook/src/contributing/PreparingAPullRequest.stories.mdx, packages/odyssey-storybook/src/guidelines/DownstreamDevelopment.stories.mdx
This PR includes additional long form documentation on contributing to Odyssey, and setting up an Odyssey first toolchain for downstream projects. Corresponding Demo App is here: https://github.com/jeffbelser-okta/odyssey-demo
=> docs(odyssey-storybook): add long form development docs

package.json
This PR separates our ie11 sandbox start script from the base storybook build
=> build: separate ie11 start script

.github/workflows/x-browser-vrt.yml
This PR fixes cron VRT script to use a non merge commit sha from the `develop` branch
=> build: skip merge commits for VRT run

.github/workflows/x-browser-vrt.yml
This PR fetches additional commit history depth to allow for successful x-browser vrt runs
=> build: increase fetch depth for x-browser vrt run

packages/eslint-plugin-odyssey/src/rules/no-invalid-theme-properites.test.js, packages/eslint-plugin-odyssey/src/rules/no-invalid-theme-properties.js, packages/odyssey-react/src/components/Box/Box.theme.ts
This PR fine tunes our eslint rule to enforce valid theme token names. It also adjusts necessary lint escaping within `odyssey-react` to account for the rule changes
=> build(eslint-plugin-odyssey): allow numeric suffix

packages/odyssey-storybook/src/components/Button/Button.stories.tsx
This PR updates our button theme story to provide VRT coverage for theme override behavior
=> chore(odyssey-storybook): render Button theme story with overrides for VRT

packages/odyssey-storybook/applitools.config.js
This PR updates the `testConcurrency` configuration to match our account threshold
=> build(odyssey-storybook): update testConcurrency applitools config

scripts/setup.sh
Previously, I made assumptions that `scripts/setup.sh` would work since we couldn't directly test this in bacon. While working in the okta-ui-shared repo, I was able to test some changes in bacon, so I'm taking the learnings here.
This will be in tandem with https://github.com/okta/external-build-scripts/pull/26 and https://github.com/okta/robo-warrior/pull/958
=> fix: update bacon setup script

.github/workflows/ci.yml, .github/workflows/warm-cache.yml, .github/workflows/x-browser-vrt.yml, .nvmrc, package.json, scripts/setup.sh
Use gallium LTS node version rather than a pinned 16.x version
=> build: use lts/gallium node version

scripts/setup.sh
fix: use yarn override env variable in ci setup script
This should be the last of the `yarn config set` usages that modifies the `.yarnrc.yml` file
=> fix: use yarn override env variable in ci setup script

packages/odyssey-storybook/src/components/Button/Button.mdx, packages/odyssey-storybook/src/components/Checkbox/Checkbox.mdx, packages/odyssey-storybook/src/components/Link/Link.mdx, packages/odyssey-storybook/src/components/Modal/Modal.mdx, packages/odyssey-storybook/src/components/Radio/Radio.mdx, packages/odyssey-storybook/src/components/Select/Select.mdx, packages/odyssey-storybook/src/components/Status/Status.mdx, packages/odyssey-storybook/src/components/Table/Table.mdx, packages/odyssey-storybook/src/components/Tabs/Tabs.mdx, packages/odyssey-storybook/src/components/TagList/TagList.mdx, packages/odyssey-storybook/src/components/TextInput/TextInput.mdx, packages/odyssey-storybook/src/components/Toast/Toast.mdx, packages/odyssey-storybook/src/components/Tooltip/Tooltip.mdx
Removes any unused "Anatomy" sections from the docs.
=> [FixIt] remove unused "Anatomy" sections

package.json
fix local husky install for yarn 3
=> fix: yarn 3 husky local install

packages/odyssey-storybook/src/components/Table/Table.mdx, packages/odyssey-storybook/src/components/Table/Table.stories.tsx
Adds stories for Default Table and Supported Content. This also renames the prior "Default" story to "Sorted".
=> docs(odyssey-storybook): add missing Table stories

packages/odyssey-react/src/components/Select/Select.module.scss, packages/odyssey-react/src/components/Select/Select.theme.ts
Updates height calculations for MultiSelect to ensure height doesn't change when options are selected.
This PR also adds Tokens in place of Sass variables where code was refactored.
=> fix(odyssey-react): multiselect height no longer changes on selection

packages/odyssey-storybook/src/components/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/Infobox/Infobox.stories.tsx, packages/odyssey-storybook/src/components/Toast/Toast.stories.tsx
Groups `Banner`, `Infobox`, and `Toast` together.
=> Group Alert components together

packages/odyssey-react/src/components/Banner/Banner.module.scss, packages/odyssey-react/src/components/Banner/Banner.test.tsx, packages/odyssey-react/src/components/Banner/Banner.theme.ts, packages/odyssey-react/src/components/Banner/Banner.tsx, packages/odyssey-storybook/src/components/Banner/Banner.mdx, packages/odyssey-storybook/src/components/Banner/Banner.stories.tsx
Removes the ability to add headings/titles to Banner as per https://oktainc.atlassian.net/browse/OKTA-500084
=> Banner: remove Heading

packages/odyssey-storybook/src/components/Banner/Banner.mdx, packages/odyssey-storybook/src/components/Field/Field.mdx, packages/odyssey-storybook/src/components/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/Toast/Toast.mdx
Fixes broken story references now that "Alert" components are nested.
=> fix(odyssey-storybook): fix nested story references

packages/odyssey-storybook/src/components/PasswordInput/PasswordInput.stories.tsx
fix custom theme not applying in storybook to PasswordInput
=>  chore(odyssey-storybook): fix custom theme

packages/odyssey-react-mui/src/themes/odyssey/index.ts, packages/odyssey-react-mui/src/themes/odyssey/shape.ts, packages/odyssey-react-mui/src/themes/odyssey/spacing.ts, packages/odyssey-react-mui/src/themes/odyssey/theme.ts
This PR uses tokens for the shape and space theme values
=> Mui theme tokens shape and space

packages/odyssey-react-mui/src/themes/odyssey/index.ts, packages/odyssey-react-mui/src/themes/odyssey/shape.ts, packages/odyssey-react-mui/src/themes/odyssey/theme.ts
This PR uses tokens for the shape theme values
=> chore(odyssey-react-mui): use tokens for theme shape

.gitignore, .prettierignore, packages/odyssey-eslint-config/src/index.js, packages/odyssey-react-mui/babel.config.cjs, packages/odyssey-react/package.json, packages/odyssey-react/tsconfig.composite.json, packages/odyssey-react/tsconfig.production.json, packages/odyssey-storybook/tsconfig.json
This PR should fix our `develop` branch allowing composite tsconfig projects to compile and type check successfully
=> build: fix tsconfig composite configuration

.github/CODEOWNERS
add @kamronbatmanghelich-okta to codeowners
=> add @kamronbatmanghelich-okta to codeowners

packages/odyssey-react-mui/src/themes/odyssey/palette.ts
This PR uses token values for our palette theme module
=> chore(odyssey-react-mui): use tokens for palette theme

package.json, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-storybook/.storybook/main.js, yarn.lock
- Added the `npm-run-all` library.
- MUI source and types now update when files are changed. Those rebuild and are picked up by Storybook which triggers a hot-reload.
[OKTA-509799](https://oktainc.atlassian.net/browse/OKTA-509799)
=> feat(odyssey-react-mui): Storybook dev updates with MUI theme changes

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.mdx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx
Adds theming for TextField components + support for InputAdornment on text fields.
=> Theme for TextField components

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-react-mui/src/themes/odyssey/components.types.ts, packages/odyssey-react-mui/src/themes/odyssey/mixins.ts, packages/odyssey-react-mui/src/themes/odyssey/mixins.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
Adds a theme and stories for Banner and Toast, using MUI's `<Alert>`.
=> Theme for Banner and Toast

packages/odyssey-react-mui/README.md
Added information about `ThemeProvider` and `useTheme` to `README`.
=> feat: added information about ThemeProvider and useTheme to README

packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx
this includes updated content and guidelines for radio button and radio group
=> docs(odyssey-storybook): radio docs update

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-react-mui/src/themes/odyssey/mixins.ts, packages/odyssey-react-mui/src/themes/odyssey/mixins.types.ts, packages/odyssey-react-mui/src/themes/odyssey/palette.ts, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx, yarn.lock
=> Theme for MUI Tabs

packages/odyssey-react-mui/package.json
Temporarily removed `type: "module"` from `odyssey-react-mui`. Tested this locally on @kamronbatmanghelich-okta's machine in the Example SPA project.
=> fix: odyssey-react-mui index.js errors in consuming apps

packages/babel-plugin-fully-specified/package.json, packages/browserslist-config-odyssey/package.json, packages/conventional-changelog-odyssey/package.json, packages/eslint-plugin-odyssey/package.json, packages/odyssey-babel-loader/package.json, packages/odyssey-babel-plugin/package.json, packages/odyssey-babel-preset/package.json, packages/odyssey-commitlint/package.json, packages/odyssey-design-tokens/package.json, packages/odyssey-eslint-config/package.json, packages/odyssey-icons/package.json, packages/odyssey-ie-11-sandbox/package.json, packages/odyssey-lifecycle/package.json, packages/odyssey-lint-staged/package.json, packages/odyssey-postcss-preset/package.json, packages/odyssey-postcss-scss/package.json, packages/odyssey-postcss-theme/package.json, packages/odyssey-react-mui/package.json, packages/odyssey-react-theme/package.json, packages/odyssey-react/package.json, packages/odyssey-storybook/package.json, packages/odyssey-stylelint/package.json, packages/odyssey-svgr/package.json, packages/odyssey-typescript/package.json
Added missing `"sideEffects"` to `package.json`.
=> feat: add missing `"sideEffects": false` to all packages

package.json, packages/babel-plugin-fully-specified/package.json, packages/odyssey-babel-plugin/package.json, packages/odyssey-babel-plugin/src/compileFactory.ts, packages/odyssey-babel-plugin/src/normalizeOpts.ts, packages/odyssey-babel-plugin/src/plugin.ts, packages/odyssey-babel-preset/package.json, packages/odyssey-postcss-preset/package.json, packages/odyssey-postcss-scss/package.json, packages/odyssey-postcss-theme/package.json, packages/odyssey-react-mui/package.json, packages/odyssey-react-theme/package.json, packages/odyssey-react/package.json, packages/odyssey-storybook/package.json, packages/odyssey-stylelint/package.json, yarn.lock
Fixed compatibility issues with TypeScript with custom Babel plugins. This is a hotfix.
=> fix: compatibility issues with TypeScript in custom Babel plugins

package.json, yarn.lock
=> fix: upgrade Lerna to 5.5.4

packages/odyssey-ie-11-sandbox/package.json, yarn.lock
=> fix: upgraded node-sass

packages/odyssey-ie-11-sandbox/package.json, yarn.lock
Upgraded `webpack-dev-server`.
=> fix: upgraded webpack-dev-server

packages/odyssey-eslint-config/package.json, yarn.lock
Upgraded `eslint-plugin-import`.
=> fix: upgraded eslint-plugin-import

package.json, yarn.lock
=> fix: upgrade caniuse-lite

package.json, packages/odyssey-babel-plugin/src/__tests__/importVisitor.test.js, packages/odyssey-babel-plugin/src/__tests__/requireVisitor.test.js, packages/odyssey-design-tokens/package.json, packages/odyssey-icons/package.json, packages/odyssey-postcss-preset/package.json, packages/odyssey-react-mui/package.json, packages/odyssey-react/package.json, packages/odyssey-storybook/package.json, packages/odyssey-stylelint/package.json, packages/odyssey-stylelint/src/index.js, yarn.lock
Upgraded libraries depending on the minimist library which had a vulnerability.
=> fix: upgraded libraries depending on minimist

package.json, yarn.lock
Updated `qs` to the latest not-vulnerable version.
=> fix: force-updated qs as the vulnerability is in Applitools and Storybook

package.json, yarn.lock
Upgraded transitive dependencies for vulnerable Ramda and qs libraries using Yarn resolutions.
=> fix: force-upgraded vulnerable Ramda and qs libraries

.github/workflows/ci.yml, .github/workflows/warm-cache.yml, .github/workflows/x-browser-vrt.yml, scripts/setup.sh
Updated Node.js versions in Bacon scripts to match the version in `.nvmrc`.
=> fix: updated Node.js versions in Bacon scripts

packages/odyssey-react-mui/src/components/PasswordInput/PasswordInput.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/utils/createUniqueId.test.ts, packages/odyssey-react-mui/src/utils/createUniqueId.ts, packages/odyssey-react-mui/src/utils/useUniqueId.ts
Exported `useUniqueId` and `createUniqueId`.
=> feat: exported useUniqueId and createUniqueId

packages/odyssey-react-mui/src/themes/odyssey/components.tsx
Small fix for `TabPanel` styling + Labs types.
=> feat(odyssey-react-mui): import Labs types, add styling for TabPanel

packages/odyssey-react-mui/src/theme/components.tsx
Updates visual appearance of `Tag`
=> refactor(odyssey-react-mui): update Tag padding, border-radius

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
Updates `Button` stories and fixes CSS to size and align Button icons.
=> [Fix] Buttons w/ Icon

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/components.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Status/Status.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Status/Status.stories.tsx
Adds the `status` variant to `Chip` + Status docs to Storybook.
=> Component theme: Status

packages/odyssey-react-mui/src/theme/components.tsx
The purpose of this PR is to convert the occurrences of physical CSS properties to use its logical counterpart for RTL language support. This includes `text-align: left/right`, `margin-right: ...`, `margin-left: ...`, `padding-right: ...`, `padding-left: ...`.
=> fix: update physical CSS properties (*-left, *-right) to use logical CSS properties

packages/odyssey-react-mui/src/Status.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/Status/Status.stories.tsx
Wraps and exports the status component with our API.
=> [Component] Status

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/.storybook/components/MuiThemeDecorator.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Table/Table.stories.tsx
- Updates SB content to reflect changes rec'd by content team.
- Wraps stories in `ScopedCssBaseline` for safer VRT
- Adds `caption` and titles to Table stories
- makes `figcaption` styles less specific
=> Storybook Content Updates

scripts/setup.sh
- Possible fix for deployment script.
=> fix: possible fix for deployment script

scripts/setup.sh
Fixes setup using the wrong folder.
=> Kb fix setup sh

scripts/setup.sh
=> fix: use the original cwd instead of assuming

lerna.json
=> fix: updated lerna not working with changed files Yarn rc

lerna.json
=> Kg/update 0.18

scripts/setup.sh
fix: build script not working properly
=> fix: build script not working properly

packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.mdx
`TextField`'s "Invalid" story was incorrectly showing a loading spinner.
=> doc: fixed TextField Invalid story doc

lerna.json
This change was made in `master` when the deploy was having issues. We need to remove it since the fix was made in the build script.
=> fix: remove unnecessary Lerna ignore for publishing

packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-react-mui/src/MenuItem.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.mdx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx
- Exports an assembled `MenuButton`
- Exports a wrapped `MenuItem`
- Styles `MenuList`, `MenuItem`, `ListSubHeader`, `Divider`
=> Menu Button

packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
Content updates for `Select` and `Banner` stories.
- https://oktainc.atlassian.net/browse/OKTA-573398
- https://oktainc.atlassian.net/browse/OKTA-579511
=> docs(odyssey-storybook): content updates for Select, Banner examples

packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/customization/CustomTheme.stories.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.stories.tsx, packages/odyssey-storybook/src/guidelines/Colors.stories.mdx, packages/odyssey-storybook/src/guidelines/CustomTheming.stories.mdx
Fixed incorrect theme info in `CustomTheming`.
Also renamed `.stories.mdx` to `.mdx`.
=> docs: fixed incorrect CustomTheming info

packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx
Updates Dialog content to match guidelines
=> docs(odyssey-storybook): update Dialog content to match guidelines

packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
update infobox content to match guidelines
=> docs(odyssey-storybook): update infobox content to match guidelines

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/palette.ts, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx
- Updates `disabled` and `readonly` states for `InputBase`, `Radio`, and `Checkbox`
- Adds transitions to these components
=> Update form control states, add transitions

packages/odyssey-react-mui/src/theme/components.tsx
Fast follow to fix checkbox icon sizing after https://github.com/okta/odyssey/pull/1769/files
=> fix(odyssey-react-mui): fix Icon sizing for Checkbox

packages/odyssey-react-mui/src/Toast.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
Toasts were disappearing in stories; this fixes that.
=> Fix broken Toast stories

packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
include static toast stories for docs
=> fix(odyssey-storybook): include static toast stories for docs

packages/odyssey-react-mui/src/Fieldset.tsx, packages/odyssey-react-mui/src/Form.tsx, packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/Fieldset/Fieldset.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Fieldset/Fieldset.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.stories.tsx
Adds Form and FieldSet components.
=> Form and FieldSet components

packages/odyssey-react-mui/src/Icon.tsx, packages/odyssey-react-mui/src/Toast.tsx
chore: remove unused forwardRef from Icon and Toast
=> chore: remove unused forwardRef from Icon and Toast

packages/odyssey-react-labs/package.json, packages/odyssey-react-labs/src/datePickerTheme.tsx, packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx, packages/odyssey-react-mui/src/theme/index.ts, packages/odyssey-react-mui/src/theme/mixins.ts, packages/odyssey-react-mui/src/theme/palette.ts, packages/odyssey-react-mui/src/theme/shape.ts, packages/odyssey-react-mui/src/theme/spacing.ts, packages/odyssey-react-mui/src/theme/theme.ts, packages/odyssey-react-mui/src/theme/typography.ts, packages/odyssey-storybook/.storybook/components/MuiThemeDecorator.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.mdx, packages/odyssey-storybook/src/contributing/CustomTheme.mdx, packages/odyssey-storybook/src/contributing/CustomTheme.stories.tsx, packages/odyssey-storybook/src/guidelines/RTL.stories.mdx, yarn.lock
- add support to override odyssey design-tokens
=> feat: add odyssey token override support

packages/odyssey-react-mui/i18n.config.json
- Add `defaultBranch` prop so our translation scripts know to read `develop` and not `master`
=> chore(odyssey-react-mui): Modify i18n.config.json to specify default branch branch

.gitignore, packages/odyssey-typescript/tsconfig.strict.json
Added `incremental` to tsconfig root, so it caches TS compilation and greatly speeds up build times locally.
=> fix: add incremental to root tsconfig

packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/Radio.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx
Two tickets, one PR:
1. Remove the unnecessary `isDefaultChecked` from `Radio`.
2. Change `hasError` to `isInvalid` in `Radio` to make it consistent with `Checkbox`
=> Remove isDefaultChecked and add isInvalid to Radio

packages/odyssey-react-mui/src/OdysseyI18n.ts
- fix: correctly import zh-CN and zh-TW files
=> fix: orrectly import zh-CN and zh-TW files

packages/odyssey-storybook/applitools.config.js
Fixed Applitools config making it so Applitools doesn't error in CI.
=> fix: Applitools VRT

packages/odyssey-react-mui/src/Banner.tsx, packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/CheckboxGroup.tsx, packages/odyssey-react-mui/src/Dialog.tsx, packages/odyssey-react-mui/src/Field.tsx, packages/odyssey-react-mui/src/FieldError.tsx, packages/odyssey-react-mui/src/FieldHint.tsx, packages/odyssey-react-mui/src/FieldLabel.tsx, packages/odyssey-react-mui/src/Infobox.tsx, packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-react-mui/src/MuiPropsChild.tsx, packages/odyssey-react-mui/src/OdysseyCacheProvider.tsx, packages/odyssey-react-mui/src/Radio.tsx, packages/odyssey-react-mui/src/RadioGroup.tsx, packages/odyssey-react-mui/src/ScreenReaderText.tsx, packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/Tabs.tsx, packages/odyssey-react-mui/src/Tag.tsx, packages/odyssey-react-mui/src/TagList.tsx, packages/odyssey-react-mui/src/ToastStack.tsx
=> Add missing displayNames to components

packages/odyssey-storybook/src/axe-util.ts, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/storybookTypes.ts
fix: add playwright tests for tooltip, tabs, autocomplete and banner components
**Recording**
https://github.com/okta/odyssey/assets/40774045/3ac42585-48ea-496c-aabb-9c834edb1f3f
=> fix: add tooltip play test

packages/odyssey-react-mui/src/Dialog.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/PasswordField/PasswordField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.stories.tsx
Add play test for dialog, menubutton, select, tag, passwordfield
=> fix: add play test for dialog, menubutton, select, tag, passwordfield

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx
Minor cleanup to Tab/Tabs styling to match rebrand designs.
=> refactor(odyssey-react-mui): update Tab/Tabs styling

packages/odyssey-design-tokens/src/palette.json, packages/odyssey-react-mui/src/theme/components.tsx
Updates HTML element styles based on Rebrand.
=> Rebrand: ScopedCSSBaseline

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/typography.ts
Updates Dialog to match Rebrand spec.
=> Rebrand: Dialog

packages/odyssey-react-mui/src/theme/components.tsx
In addition to removing borders, this matches Button.Tertiary background color grades to Button.Secondary's
=> refactor(odyssey-react-mui): remove borders from button:hover

packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx
Added `ScopedCssBaseline` to `OdysseyThemeProvider`.
=> feat: adds ScopedCssBaseline to OdysseyThemeProvider

packages/odyssey-react-mui/src/Field.tsx, packages/odyssey-react-mui/src/Fieldset.tsx, packages/odyssey-react-mui/src/FieldsetContext.tsx, packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Fieldset/Fieldset.stories.tsx
`Fieldset` would work with `isDisabled`, but `Field` components wouldn't react to those changes. So you'd have something visually, but not logically, disabled.
=> feat: add `isDisabled` in context from Fieldset to Field

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/Dialog.tsx, packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-react-mui/src/MuiPropsContext.ts, packages/odyssey-react-mui/src/OdysseyCacheProvider.test.tsx, packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/Status.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/PaginatedTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/StaticTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx, packages/odyssey-storybook/src/contributing/CustomTheme.stories.tsx
Adds tooltip capabilities to `Status` and adds `tooltipText` to `MenuButton`.
**BREAKING CHANGE:** Renames `Button`'s `text` to `label`.
=> Adds missing Tooltip functionality support to MenuButton and Status

packages/odyssey-react-mui/src/theme/components.tsx
Fixed broken styles in `MuiInputBase`. They weren't caught because MUI's type coverage doesn't check nested dynamic style props. I added `satisfies` and a new ticket to cover the rest.
=> fix: broken styles in MuiInputBase

.bacon.yml, scripts/semgrep.sh
feat: adds semgrep static scan to the repo
=> feat: adds semgrep static scan to the repo

packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx
Move `ScopedCssBaseline` from `OdysseyThemeProvider` to `OdysseyProvider`.
=> refactor: move ScopedCssBaseline to OdysseyProvider

packages/odyssey-react-mui/src/Tabs.tsx
Add value prop to Odyssey Tabs component
=> Fix: add value prop to tabs

packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx
Minor content updates to the `MenuButton` stories.
=> docs(odyssey-storybook): updates to MenuButton content

packages/odyssey-react-mui/src/OdysseyI18n.ts, packages/odyssey-react-mui/src/OdysseyTranslationProvider.types.ts, packages/odyssey-storybook/src/guidelines/OdysseyTranslationProvider.stories.mdx
Forgot  to add Vietnamese as a supported language
=> chore: add vi into language list

packages/odyssey-react-mui/src/labs/PaginatedTable.tsx, packages/odyssey-react-mui/src/labs/StaticTable.tsx
Pass in the stored `globalFilter` and `columnFilters` into state to make filtering work as expected.
=> fix: make global + column filtering work in Tables (@okta/odyssey-react-mui/labs)

packages/odyssey-storybook/.storybook/components/MuiThemeDecorator.tsx, packages/odyssey-storybook/src/contributing/CustomTheme.stories.tsx
[N/A](https://oktainc.atlassian.net/browse/REPLACE_WITH_JIRA_TICKET_NUMBER)
Some TS errors ended up in the repo because of a merge mistake. I'm fixing those here.
N/A
=> fix: some TS errors went through the cracks

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
[OKTA-652646](https://oktainc.atlassian.net/browse/OKTA-652646)
We couldn't change the `id` nor the `name` for `Select` in Storybook. This is because it was rendering using the old v6 method and missing a bunch of props.
I also added some missing memoization.
=> fix: id and name not changing in Storybook

README.md, packages/browserslist-config-odyssey/README.md, packages/odyssey-babel-loader/README.md, packages/odyssey-babel-preset/README.md, packages/odyssey-design-tokens/README.md, packages/odyssey-react-mui/README.md, packages/odyssey-react-mui/scripts/properties-to-ts.js, packages/odyssey-react-mui/src/labs/README.md
[OKTA-651439](https://oktainc.atlassian.net/browse/OKTA-651439)
Switched to inclusive language from Odyssey per Okta guidelines.
N/A
=> fix: inclusive language adjustments

packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.stories.tsx, packages/odyssey-storybook/src/components/odyssey-labs/GroupPicker/GroupPicker.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Callout/Callout.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CheckboxGroup/CheckboxGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CircularProgress/CircularProgress.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/PaginatedTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/StaticTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Fieldset/Fieldset.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Link/Link.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/NativeSelect/NativeSelect.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/PasswordField/PasswordField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/SearchField/SearchField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Status/Status.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx
[OKTA-633500](https://oktainc.atlassian.net/browse/OKTA-633500)
- Update default value for components in storybook
- Add **Required** in description
=> docs: storybook default values

packages/odyssey-react-mui/src/RadioGroup.tsx
[OKTA-661562](https://oktainc.atlassian.net/browse/OKTA-661562)
- Use MUI onChange props
=> Use MUI interface for onChange handler

packages/odyssey-react-mui/src/Dialog.tsx
[OKTA-662265](https://oktainc.atlassian.net/browse/OKTA-662265)
- Add tab index to scrollable dialog content to allow keyboard navigation
=> Allow keyboard navigation of overflow dialog

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/CheckboxGroup.tsx, packages/odyssey-react-mui/src/Field.tsx, packages/odyssey-react-mui/src/NativeSelect.tsx, packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/RadioGroup.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/TextField.tsx
[OKTA-653192](https://oktainc.atlassian.net/browse/OKTA-653192)
- Use correct `aria-errormessage` attributes.
- Add `aria-labelledby` to `TextField` and `AutoComplete` components.
- Fix broken `aria-labelledby` attribute on `Select` component
=> Adds more detailed aria attributes to inputs

packages/odyssey-react-mui/src/PasswordField.tsx
[OKTA-662401](https://oktainc.atlassian.net/browse/OKTA-662401)
- Apply autocomplete="off" when user toggles password visibility
=> Apply autocomplete="off" when user toggles password visibility

packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx
This reverts commit 4ae50debc051299774847804509aa1dae0dad831.
[OKTA-664319](https://oktainc.atlassian.net/browse/OKTA-664319)
=> fix: revert #2013

packages/odyssey-react-mui/src/Tooltip.tsx
[659417](https://oktainc.atlassian.net/browse/659417)
Memoizes tooltip component and adds displayName to it
=> Cpulsinelli okta 659417 fix tooltip displayname

.bacon.yml, .github/workflows/ci.yml, .github/workflows/version.yml, .github/workflows/warm-cache.yml, .github/workflows/x-browser-vrt.yml
https://oktainc.atlassian.net/browse/OKTA-663938
We need to version Odyssey when merging to `main` so we can automate publishing of Odyssey altogether. Right now, it's a very manual process, and this is the first step in fixing that.
Once we have this fixed, we can move onto automating the publish process and then the post-publish tasks.
N/A
=> Automatically Odyssey versioning when merging to main

packages/odyssey-react-mui/src/theme/components.tsx
[DES-4279](https://oktainc.atlassian.net/browse/DES-4279)
- Update Callout titles so that they match the Figma definition
=> Update Callout titles to match Figma

packages/odyssey-react-mui/src/createShadowRootElement.ts
[OKTA-667926](https://oktainc.atlassian.net/browse/OKTA-667926)
Fixes an issue introduced in the last build when refactoring shadow DOM code.
N/A
=> fix: shadow DOM function using wrong return value

packages/odyssey-react-mui/src/OdysseyCacheProvider.tsx
[OKTA-674571](https://oktainc.atlassian.net/browse/OKTA-674571)
=> fix: add back props removed from odyssey cache provider

packages/odyssey-design-tokens/src/typography.json, packages/odyssey-react-mui/src/OdysseyTranslationProvider.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx, packages/odyssey-typescript/tsconfig.react.json
Replacement PR for #2032
Previous PR was failing VRT for unknown reasons
[OKTA-660477](https://oktainc.atlassian.net/browse/OKTA-660477)
=> Add lang selector support for font families

packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/labs/Switch.tsx, packages/odyssey-react-mui/src/labs/index.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/Switch/Switch.stories.tsx
[OKTA-597718](https://oktainc.atlassian.net/browse/OKTA-597718)
- Adds a `Switch` component to labs
https://www.figma.com/file/wl4WWe0AreTdy5m76BfyOP/Switch-Component-%5BDraft%5D?type=design&node-id=823%3A8844&mode=dev
=> Add switch component

packages/odyssey-react-mui/src/OdysseyTranslationProvider.tsx
- Fix bug where translation files containing `_` could not be accessed
=> Pass non-formatted languageCode to i18n

packages/odyssey-design-tokens/src/transition.json, packages/odyssey-react-mui/src/labs/DataTable.tsx
[OKTA-671404](https://oktainc.atlassian.net/browse/OKTA-671404)
- Adds ability for table row reordering using only keyboard
=> Add keyboard table reordering

packages/odyssey-react-mui/src/labs/Switch.tsx
=> FIX: (odyssey-react-mui): move variable declaration below import

packages/odyssey-react-mui/src/Badge.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx
- Limit badge count to increments of 10, up to 100
=> Limit max to increments of 10 up to 100

.github/workflows/ci.yml
[OKTA-683702](https://oktainc.atlassian.net/browse/OKTA-683702)
Updates Applitools URL from public to private using GitHub secrets.
=> build: updates APPLITOOLS_SERVER_URL to use private url

packages/odyssey-storybook/src/components/odyssey-labs/Switch/Switch.stories.tsx
[OKTA-686277](https://oktainc.atlassian.net/browse/OKTA-686277)
=> Update storybook switch docs

packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/labs/VirtualizedAutocomplete.tsx
=> Fix lint issue

packages/odyssey-react-mui/src/CircularProgress.tsx
- Fixes display name and adds memoization
=> Memoize and fix progress display name

lerna.json, packages/odyssey-react-mui/src/index.ts
- Fixes export that breaks build
=> Fix broken FocusHandle export

packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx
…ctive and disabled item styling
[OKTA-687359](https://oktainc.atlassian.net/browse/OKTA-687359)
- Fixes bug where menu button could not be disabled
- Brings destructive and disabled menu item styles in line with Figma
=> Allow disabling of menu button. Update destructive and disabled item styles

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/MuiPropsContext.ts
[OKTA-690643](https://oktainc.atlassian.net/browse/OKTA-690643)
- Fixing adding focus ref caused issues with tooltip ref.
=> Fix muiProps ref on button with tooltip

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/SearchField.tsx
- Expose tabindex for Button and SearchField
=> Expose tabindex for Button and SearchField

packages/odyssey-react-mui/src/@types/react-augment.d.ts, packages/odyssey-react-mui/src/NativeSelect.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/NativeSelect/NativeSelect.stories.tsx
[OKTA-688308](https://oktainc.atlassian.net/browse/OKTA-688308)
Removed `ForwardRefWithType` as it's not needed and its implementation wasn't working as expected to begin with.
=> fix: remove unused type

packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-694540](https://oktainc.atlassian.net/browse/OKTA-694540)
- Fix min width for check and radio
=> Minor styling fixes for checkbox and radio

packages/odyssey-react-mui/src/Button.tsx
- Fix props not being passed to button
=> Pass props through to button

packages/odyssey-react-mui/src/Status.tsx
- Fixes code samples not appearing correctly.
- Adds memoization
=> Memoize status and add display name

packages/odyssey-react-mui/src/Typography.tsx
- Fixes passing `data-se` prop to `Typography`. It expects `testId` instead
=> Pass correct props to utility Typography components

packages/odyssey-react-mui/src/Dialog.tsx, packages/odyssey-react-mui/src/labs/Drawer.tsx, packages/odyssey-react-mui/src/labs/index.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/.storybook/test-runner.js, packages/odyssey-storybook/src/components/odyssey-labs/Drawer/Drawer.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx
[OKTA-570830](https://oktainc.atlassian.net/browse/OKTA-570830)
* Adds Drawer component
* [Figma](https://www.figma.com/file/IG8unZFro7D5hv7d2gRTGS/Drafts%2FDrawer?type=design&node-id=10-138067&mode=design&t=SPcGo4sKankNpVtQ-0)
=> Add Drawer component to labs

.bacon.yml
[OKTA-701305](https://oktainc.atlassian.net/browse/OKTA-701305)
Odyssey isn't publishing because we upgrade Yarn to v4 which requires Node v20. While we have that version, Bacon wasn't using it. We've updated the Bacon yaml file to pull the build with the correct Node version.
N/A
=> Fix Odyssey not publishing

packages/odyssey-react-mui/src/IconWithTooltip.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/IconWithTooltip/IconWithTooltip.stories.tsx
[OKTA-681936](https://oktainc.atlassian.net/browse/OKTA-681936)
- Add component to render an `i` icon and tooltip for additional context
=> Add additional context icon

packages/odyssey-react-mui/src/Callout.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Callout/Callout.stories.tsx
Modifies the margin at the top of the CTA in Callouts.
=> Update cta spacing in Callout

packages/odyssey-react-mui/src/Button.tsx
[OKTA-709642](https://oktainc.atlassian.net/browse/OKTA-709642)
- Fixes fullWidth prop on button
=> Fix button full width prop

.github/workflows/ci.yml, packages/odyssey-storybook/applitools.config.js, packages/odyssey-storybook/package.json, yarn.lock
- Upgraded Applitools SDK version
- Changed the ci.yml to use the applitools config file. 
[Ticket](https://oktainc.atlassian.net/browse/OKTA-705795)
=> fix: Applitools Integration

.bacon.yml
[OKTA-710706](https://oktainc.atlassian.net/browse/OKTA-710706)
Odyssey is changing its release cycle, so our continuous delivery task needs to be disabled. This is the first step in a number of other upcoming changes.
N/A
=> build: disables continuous delivery

packages/odyssey-storybook/package.json, yarn.lock
=> fix: upgrade vrt

README.md, packages/odyssey-react-mui/README.md
- Update README to include link to local dev docs
=> Add local development link to readme

packages/odyssey-react-mui/src/Select.tsx
The height on controlled multi-selects was broken; this makes it consistent with the others.
=> Fix broken height on multi-select

packages/odyssey-storybook/.storybook/test-runner.js, packages/odyssey-storybook/src/components/odyssey-mui/Accordion/Accordion.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Box/Box.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Breadcrumbs/Breadcrumbs.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CheckboxGroup/CheckboxGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CircularProgress/CircularProgress.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CssBaseline/CssBaseline.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Fieldset/Fieldset.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Link/Link.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/NativeSelect/NativeSelect.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/PasswordField/PasswordField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/SearchField/SearchField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx, packages/odyssey-storybook/src/fieldComponentPropsMetaData.ts
[OKTA-705452](https://oktainc.atlassian.net/browse/705452)
- Add more tests to odyssey-storybook for visual test
- Add `errorMessageList` description to form components
- Make sure code block only show the correct context when expand
=> fix: tests in odyssey-storybook

packages/odyssey-react-mui/src/DataTable/DataTable.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.stories.tsx
=> Rename text wrapping prop

packages/odyssey-react-mui/src/Drawer.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/labs/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/Drawer/Drawer.stories.tsx
[OKTA-700393](https://oktainc.atlassian.net/browse/OKTA-700393)
Moves Drawer from Labs to Odyssey
=> Move Drawer from labs to Odyssey [OKTA-700393]

packages/odyssey-storybook/src/components/odyssey-mui/Callout/Callout.stories.tsx
[OKTA-708136](https://oktainc.atlassian.net/browse/OKTA-708136)
Add `children` to the props table in Storybook for Callout
=> fix: update callout storybook docs

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
- Update guidance around disabled buttons
=> Updated disabled button guidance

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/components.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
[DES-5604](https://oktainc.atlassian.net/browse/DES-5604)
Adds "Secondary Danger" as a new button variant to align with a recently added Figma library update 
https://github.com/okta/odyssey/assets/147574410/a5e76d67-42e2-4044-b847-105d805da1f2
=> Add Secondary Danger button variant

packages/odyssey-react-mui/src/MenuItem.tsx
[OKTA-727755](https://oktainc.atlassian.net/browse/OKTA-727755)
- Fixes a bug where MenuButton was not accessible via KB
=> Add tabindex to enable menu KB navigation

lerna.json
[OKTA-725386](https://oktainc.atlassian.net/browse/OKTA-725386)
This is the test.
=> feat: bumps lerna version

packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-loader/package.json, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/package.json
[OKTA-733685](https://oktainc.atlassian.net/browse/OKTA-733685)
Bump version to 1.17
=> fix: bump version to 1.17

packages/odyssey-react-mui/src/labs/DataFilters.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.stories.tsx
[OKTA-723709](https://oktainc.atlassian.net/browse/OKTA-723709)
- Fix bug where label was passed to filter rather than value
- Allow multi-select
- Apply filters on click away
=> Allow multi-select. pass value to filter

lerna.json
[OKTA-734792](https://oktainc.atlassian.net/browse/OKTA-734792)
=> build: bump lerna version

packages/odyssey-react-mui/src/labs/DataFilters.tsx
- Renamed branch. [Previous PR](#2244 )
=> Fix filter autocomplete value

CHANGELOG.md
[OKTA-737616](https://oktainc.atlassian.net/browse/OKTA-737616)
Manually updates `changelog.md` with the latest from the 6/7/24 `odyssey-1.16.0` release
=> Update changelog.md to include odyssey-1.16.0

packages/odyssey-react-mui/src/DataTable/DataTable.tsx, packages/odyssey-react-mui/src/EmptyState.tsx
=> feat: add backwards compatible empty state export

packages/odyssey-react-mui/src/Accordion.tsx
[OKTA-739874](https://oktainc.atlassian.net/browse/OKTA-739874)
- Fixes a bug where `testId` does not appear in the DOM
=> Pass tsetId to Accordion

.releng.yml, lerna.json, packages/babel-plugin-fully-specified/package.json, packages/browserslist-config-odyssey/package.json, packages/conventional-changelog-odyssey/package.json, packages/eslint-plugin-odyssey/package.json, packages/odyssey-babel-loader/package.json, packages/odyssey-babel-preset/package.json, packages/odyssey-commitlint/package.json, packages/odyssey-design-tokens/package.json, packages/odyssey-eslint-config/package.json, packages/odyssey-icons/package.json, packages/odyssey-lifecycle/package.json, packages/odyssey-lint-staged/package.json, packages/odyssey-react-mui/package.json, packages/odyssey-stylelint/package.json, packages/odyssey-typescript/package.json
=> Backport 1.17 main

lerna.json, packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-loader/package.json, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/package.json
=> Bump odyssey versions

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-746694](https://oktainc.atlassian.net/browse/OKTA-746694)
- Fixes a bug where autocomplete menu is longer than necessary sometimes
=> Only apply height rules to virtualized autocomplete

packages/odyssey-react-mui/package.json
[OKTA-747545](https://oktainc.atlassian.net/browse/OKTA-747545)
=> Bump odyssey-react-mui version not bumped in error

packages/odyssey-react-mui/i18n.config.json
[OKTA-737434](https://oktainc.atlassian.net/browse/OKTA-737434)
- Add Slack information for sending Slack notifications
=> Add Slack information for Odyssey

packages/odyssey-react-mui/src/DataTable/DataTable.tsx
=> fix DataTable callback dep warnings

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/properties/odyssey-react-mui.properties, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
[OKTA-742635](https://oktainc.atlassian.net/browse/OKTA-742635)
Before:
Now:
=> English leak for "Close" in Autocomplete

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
[OKTA-795987](https://oktainc.atlassian.net/browse/OKTA-795987)
=> fix(odyssey-react-mui): Add min-heights to keep correct heights

packages/odyssey-react-mui/src/labs/SideNav/SideNav.tsx, packages/odyssey-storybook/.storybook/preview-head.html
=> fix(odyssey-design-tokens): using correct weights in SB

CHANGELOG.md, lerna.json, packages/browserslist-config-odyssey/CHANGELOG.md, packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-preset/CHANGELOG.md, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/CHANGELOG.md, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/CHANGELOG.md, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/labs/DataView/DataView.test.tsx, packages/odyssey-react-mui/src/labs/DataView/DataView.tsx, packages/odyssey-react-mui/src/labs/DataView/componentTypes.ts, packages/odyssey-storybook/CHANGELOG.md, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/components/odyssey-labs/DataView/DataView.stories.tsx, packages/odyssey-svgr/CHANGELOG.md, packages/odyssey-svgr/package.json, scripts/publish-packages.sh
=> Backport 1.23 main

CHANGELOG.md, lerna.json, packages/browserslist-config-odyssey/CHANGELOG.md, packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-preset/CHANGELOG.md, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/CHANGELOG.md, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/CHANGELOG.md, packages/odyssey-react-mui/package.json, packages/odyssey-storybook/CHANGELOG.md, packages/odyssey-storybook/package.json, packages/odyssey-svgr/CHANGELOG.md, packages/odyssey-svgr/package.json
[DES-6554](https://oktainc.atlassian.net/browse/DES-6554)
* merging 1.24 => main
=> Backport 1.24 main

CHANGELOG.md, lerna.json, packages/browserslist-config-odyssey/CHANGELOG.md, packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-preset/CHANGELOG.md, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/CHANGELOG.md, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/CHANGELOG.md, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/CHANGELOG.md, packages/odyssey-storybook/package.json, packages/odyssey-svgr/CHANGELOG.md, packages/odyssey-svgr/package.json
[DES-6558](https://oktainc.atlassian.net/browse/DES-6558)
- Backport 1.24.1 to main
=> Merge 1.24.1 => main

packages/odyssey-storybook/src/guidelines/OdysseyTranslationProvider.stories.mdx
[DES-6603](https://oktainc.atlassian.net/browse/DES-6603)
- Adds 'ht' to supported languages object
- Adds new keys that were previously undocumented
=> chore(odyssey-storybook): add ht to langs and add newer keys

packages/odyssey-react-mui/src/labs/AppTile.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/AppTile/AppTile.stories.tsx
[OKTA-811761](https://oktainc.atlassian.net/browse/OKTA-811761)
- Remove background color for on hover behavior
- Add custom styling for AppTile (won't affect other components that use MUI's Card)
- Add grey background to storybook
=> Update on hover CSS for AppTile component

packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx
[DES-6665](https://oktainc.atlassian.net/browse/DES-6665)
* Adds height style to ref div in OdysseyThemeProvider
* Note: this does not resolve any known issues, we are adding it as a precaution.
=> Add height style to OdysseyThemeProvider div

packages/odyssey-storybook/src/guidelines/Roadmap/roadmap.json, packages/odyssey-storybook/src/guidelines/Roadmap/roadmapData.tsx
[DES-6678](https://oktainc.atlassian.net/browse/DES-6678)
* Updates roadmap data in Storybook with the latest from the Odyssey Component Tracker spreadsheet
* Fix column width to accommodate the "Page template" label
*
=> Updates roadmap page data with latest

packages/odyssey-storybook/src/guidelines/Roadmap/roadmap.json
[DES-6678](https://oktainc.atlassian.net/browse/DES-6678)
* Updates roadmap data in Storybook with the latest from the Odyssey Component Tracker spreadsheet
* Includes Policy template
=> Updates roadmap page data with policies

packages/odyssey-react-mui/src/Surface.tsx, packages/odyssey-react-mui/src/labs/SideNav/NavAccordion.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavItemContent.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavItemLinkContent.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavToggleButton.tsx, packages/odyssey-react-mui/src/labs/TopNav/TopNav.tsx, packages/odyssey-react-mui/src/labs/UiShell/UiShellContent.tsx
[DES-6729](https://oktainc.atlassian.net/browse/DES-6729)
Some minor cosmetic fast follows for SideNav
=> Side nav followups

packages/odyssey-react-mui/i18n.config.json
[OKTA-818689](https://oktainc.atlassian.net/browse/OKTA-818689)
- Add enduser namespace for use in globalization scripts
=> Add namespace

packages/odyssey-react-mui/src/labs/SideNav/SideNav.test.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavItemContent.tsx
Fixing five broken SideNav tests.
=> Fix broken SideNav tests

packages/odyssey-react-mui/src/labs/UiShell/UiShell.tsx, packages/odyssey-react-mui/src/labs/UiShell/UiShellContent.tsx, packages/odyssey-react-mui/src/labs/UiShell/renderUiShell.tsx
[OKTA-835567](https://oktainc.atlassian.net/browse/OKTA-835567)
=> fix: the UiShell should not have gray background or padding in app area

packages/odyssey-react-mui/src/Pagination/Pagination.test.tsx, packages/odyssey-react-mui/src/labs/UiShell/UiShell.test.tsx, scripts/odyssey-code-coverage.sh, scripts/publish-storybook.sh, scripts/unit-test.sh, scripts/visual-regression-test.sh
[OKTA-835565](https://oktainc.atlassian.net/browse/OKTA-835565)
=> fix tests and Bacon

CHANGELOG.md, lerna.json, packages/browserslist-config-odyssey/CHANGELOG.md, packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-preset/CHANGELOG.md, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/CHANGELOG.md, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/CHANGELOG.md, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/labs/UiShell/renderUiShell.test.tsx, packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.ts, packages/odyssey-storybook/CHANGELOG.md, packages/odyssey-storybook/package.json, packages/odyssey-svgr/CHANGELOG.md, packages/odyssey-svgr/package.json
[DES-6853](https://oktainc.atlassian.net/browse/DES-6853)
The Bacon backport tasked failed and this needs to be manually merged back
=> Backport 1.28.1 => main

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/Breadcrumbs.tsx, packages/odyssey-react-mui/src/Buttons/MenuItem.tsx, packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/HtmlProps.ts, packages/odyssey-react-mui/src/Radio.tsx, packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/mixins.ts, packages/odyssey-react-mui/src/theme/mixins.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
Some minor a11y enhancements found during audit
=> a11y enhancements

yarn.lock
[OKTA-810811](https://oktainc.atlassian.net/browse/OKTA-810811)
Upgrades rollup to use non-vulnerable versions of these dependencies
=> fix: vuln upgrade rollup versions

yarn.lock
[OKTA-827857](https://oktainc.atlassian.net/browse/OKTA-827857)
Natural version bump on package version to remove it's vulnerability
=> fix: bump cross-spawn version

yarn.lock
[OKTA-822642](https://oktainc.atlassian.net/browse/OKTA-822642)
Natural bump of micromatch version to remove exposure to its vulnerability
=> fix: bump version of micromatch

packages/odyssey-react-mui/src/labs/OdysseyPickers/ComposablePicker.tsx, packages/odyssey-react-mui/src/labs/OdysseyPickers/Picker.tsx, packages/odyssey-react-mui/src/labs/OdysseyPickers/PickerWithOptionAdornment.tsx
[DES-6973](https://oktainc.atlassian.net/browse/DES-6973)
[DES-6962](https://oktainc.atlassian.net/browse/DES-6962)
- Allow no options prop to be passed through
- Fix unique key warnings
=> Picker fixes

packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/types.ts, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
[OKTA-856004](https://oktainc.atlassian.net/browse/OKTA-856004)
feat: add option to control sidenav collapse state
=> feat: add option to control sidenav collapse state

packages/odyssey-react-mui/src/ui-shell/UiShellContent.tsx, packages/odyssey-react-mui/src/ui-shell/useScrollState.ts, packages/odyssey-storybook/src/components/odyssey-ui-shell/UiShell/UiShell.stories.tsx
[OKTA-856222](https://oktainc.atlassian.net/browse/OKTA-856222)
=> feat: allow consumer to manage the scroll container for UIShell

README.md, scripts/publish-packages.sh
[OKTA-856266](https://oktainc.atlassian.net/browse/OKTA-856266)
=> fix: remove references to babel-preset package

packages/odyssey-react-mui/src/ui-shell/SideNav/types.ts
[OKTA-858580](https://oktainc.atlassian.net/browse/OKTA-858580)
[fix] sidenavitem type update to support isSortable prop
=> fix: type update for sidenavitem to ignore isSortable prop

packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/ui-shell/TopNav/TopNav.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.tsx, packages/odyssey-react-mui/src/ui-shell/UiShellContent.tsx, packages/odyssey-storybook/src/components/odyssey-ui-shell/UiShell/UiShell.stories.tsx
[OKTA-858557](https://oktainc.atlassian.net/browse/OKTA-858557)
Do not put ScopedCssBaseline around UiShell app content (or banners)!
=> feat: do not put ScopedCssBaseline around app content in UiShell

CHANGELOG.md, lerna.json, packages/browserslist-config-odyssey/CHANGELOG.md, packages/browserslist-config-odyssey/package.json, packages/odyssey-design-tokens/CHANGELOG.md, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/CHANGELOG.md, packages/odyssey-react-mui/package.json, packages/odyssey-storybook/CHANGELOG.md, packages/odyssey-storybook/package.json
[DES-7044](https://oktainc.atlassian.net/browse/DES-7044)
=> Backport 1.31 => main

CHANGELOG.md, lerna.json, packages/browserslist-config-odyssey/CHANGELOG.md, packages/browserslist-config-odyssey/package.json, packages/odyssey-design-tokens/CHANGELOG.md, packages/odyssey-design-tokens/package.json, packages/odyssey-react-mui/CHANGELOG.md, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.test.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.tsx, packages/odyssey-react-mui/src/ui-shell/UiShellContent.tsx, packages/odyssey-react-mui/src/ui-shell/renderUiShell.tsx, packages/odyssey-storybook/CHANGELOG.md, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/components/odyssey-ui-shell/UiShell/UiShell.stories.tsx
[DES-7051](https://oktainc.atlassian.net/browse/DES-7051)
=> merge 1.31 => main

packages/odyssey-react-mui/src/ui-shell/UiShell.test.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.tsx, packages/odyssey-react-mui/src/ui-shell/UiShellContent.tsx, packages/odyssey-react-mui/src/ui-shell/renderUiShell.tsx
[OKTA-861669](https://oktainc.atlassian.net/browse/OKTA-861669)
=> fix: uishell should allow horizontal scrolling if necessary

packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavItemContent.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavItemLinkContent.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavLogo.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/types.ts, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
[OKTA-861817](https://oktainc.atlassian.net/browse/OKTA-861817)
- add onClick support for the Logo (OKTA-861817)
- add no-translate to support non-localized strings (OKTA-866093)
=> add onClick support for the Logo

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
[OKTA-890845](https://oktainc.atlassian.net/browse/OKTA-890845)
support lang attribute in select option items
=> OKTA-890845: allow select option item take lang attr

packages/odyssey-react-mui/src/labs/OdysseyPickers/SearchDropdown.tsx, packages/odyssey-react-mui/src/labs/OdysseyPickers/index.ts, packages/odyssey-storybook/src/components/odyssey-labs/SearchDropdown/SearchDropdown.stories.tsx
=> feat: add SearchDropdown component

lerna.json, packages/odyssey-react-mui/src/OdysseyCacheProvider.test.tsx, packages/odyssey-react-mui/src/createUniqueAlphabeticalId.test.ts, packages/odyssey-react-mui/src/createUniqueId.test.ts, packages/odyssey-react-mui/src/theme/StringWithValue.ts, packages/odyssey-react-mui/src/theme/useMediaQuery.test.ts, packages/odyssey-react-mui/src/theme/useMediaQuery.ts, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.test.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.test.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.tsx, packages/odyssey-react-mui/src/ui-shell/bufferLatest.test.ts, packages/odyssey-react-mui/src/ui-shell/createMessageBus.test.ts, packages/odyssey-react-mui/src/ui-shell/createStore.test.ts, packages/odyssey-react-mui/src/ui-shell/index.ts, packages/odyssey-react-mui/src/ui-shell/renderUiShell.test.tsx, packages/odyssey-react-mui/src/ui-shell/renderUiShell.tsx, packages/odyssey-react-mui/src/ui-shell/useUiShellBreakpoints.test.ts, packages/odyssey-react-mui/src/ui-shell/useUiShellBreakpoints.ts, packages/odyssey-react-mui/src/web-component/createReactRootElements.test.ts, packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.test.tsx, packages/odyssey-react-mui/tsconfig.json, packages/odyssey-react-mui/vitest.setup.ts
[OKTA-900099](https://oktainc.atlassian.net/browse/OKTA-900099)
UI Shell Breakpoints are now customizable on Admin.
Also added missing tests for breakpoint identification.
Tests all pass 👍.
=> fix: adds customizable UI Shell breakpoints for Admin

packages/odyssey-react-mui/src/labs/DataView/TableLayoutContent.tsx
https://oktainc.atlassian.net/browse/OKTA-905097
Before:
After:
=> fix: empty tables creating scrollbar

packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavToggleButton.tsx, packages/odyssey-react-mui/src/ui-shell/WideUiShellContent.tsx
[OKTA-913359](https://oktainc.atlassian.net/browse/OKTA-913359)
=> fix: restyle side nav in UI Shell

packages/odyssey-react-mui/src/labs/PageTemplate/DocumentationLink.tsx, packages/odyssey-react-mui/src/labs/PageTemplate/PageTemplate.tsx
https://oktainc.atlassian.net/browse/OKTA-866065
Update the width of documentation link in PageTemplate.
Also, open a new tab instead of redirect the page when clicking on the link.
Before:
After:
With documentation link and action buttons:
No action buttons:
No documentation link:
=> Franky okta 866065 documentation link

.envrc, yarn.lock
[OKTA-910281](https://oktainc.atlassian.net/browse/OKTA-910281)
=> fix: natural upgrade of vite (for master)

.envrc, package.json, yarn.lock
[OKTA-905140](https://oktainc.atlassian.net/browse/OKTA-905140)
=> fix: resolution for tar-fs (on master)

yarn.lock
[OKTA-910281](https://oktainc.atlassian.net/browse/OKTA-910281)
=> fix: natural upgrade of vite (on main)

yarn.lock
[OKTA-910281](https://oktainc.atlassian.net/browse/OKTA-910281)
=> fix: more vite vuln fixes

packages/odyssey-react-mui/src/labs/PageTemplate/PageTemplate.tsx
[OKTA-923438](https://oktainc.atlassian.net/browse/OKTA-923438)
Update font style of description in PageTemplate.
Before:
After:
=> fix: font style of description in PageTemplate

packages/odyssey-react-mui/src/labs/OdysseyPickers/ComposablePicker.tsx, packages/odyssey-react-mui/src/labs/OdysseyPickers/Picker.tsx, packages/odyssey-react-mui/src/labs/OdysseyPickers/PickerWithOptionAdornment.tsx
Merge the missing backporting commit to main
* fix(odyssey-react-mui): pass through no options text
* fix(odyssey-react-mui): fix unique key not being applied to option
* fix(odyssey-react-mui): fix picker return type mismatch
* fix(odyssey-react-mui): remove commented code
* fix(odyssey-react-mui): change prop name and update key logic
* fix(odyssey-react-mui): no const for key
https://oktainc.atlassian.net/browse/OKTA-939526
=> Picker fixes (#2462)

yarn.lock
[OKTA-944218](https://oktainc.atlassian.net/browse/OKTA-944218)
=> Update vite again (master)

packages/odyssey-react-mui/i18n.config.json
[OKTA-962297](https://oktainc.atlassian.net/browse/OKTA-962297)
- Add Jira component so the correct team can be assigned when translation PRs are delivered
=> Add Jira component

packages/odyssey-react-mui/src/ui-shell/useScrollState.browser.test.ts, packages/odyssey-react-mui/src/ui-shell/useScrollState.ts
[OKTA-958764](https://oktainc.atlassian.net/browse/OKTA-958764)
Swaps filter operations to improve performance on longer non virtualized lists
=> fix: improve scroll detection for longer lists with useScrollState
