scripts/setup.sh
- Fixes an issue when the external publish script is triggered, resulting in an incorrect `{REPO}` value.
=> Fixes setup script being called from an external source

.github/CODEOWNERS, lerna.json, package.json, packages/docs/package.json, packages/odyssey/package.json
- Increments version to`0.1.1` to deploy new design-docs package.
- Updates CODEOWNERS to require DS review on `scss`, `html`, and `md` files.
- Require `eng-uicore` review on everything else (`js`, `json`, `sh`)
=> :package: Increment version to deploy design-docs

packages/docs/.gitignore, packages/docs/package.json, packages/docs/source/_data/nav.yml, packages/docs/source/getting-started/status.md, packages/odyssey/CHANGELOG.md
Adds up to date changelog for `0.1.1`.
@jmelberg-okta, @arnoldsandoval-okta's set this up to copy the repo changelog into the docs, so we have a web visible version as well. Won't get detected by Hexo's hot reload, but I figure we can find a more elegant solution when we swap frameworks if we need to.
=> Add Changelog

packages/odyssey/CHANGELOG.md, packages/odyssey/src/scss/components/_table.scss
Fixes Table cell overflow by adding `overflow-wrap: break-word`.
Fixes #463
=> Bugfix: table overflow

packages/docs/source/_data/nav.yml, packages/docs/source/components/status.md, packages/docs/source/components/table.md, packages/odyssey/src/scss/abstracts/_colors.scss, packages/odyssey/src/scss/components/_banner.scss, packages/odyssey/src/scss/components/_callout.scss, packages/odyssey/src/scss/components/_meter.scss, packages/odyssey/src/scss/components/_status-layout.scss, packages/odyssey/src/scss/components/_status.scss, packages/odyssey/src/scss/odyssey.scss
Status is used to keep users informed, by providing appropriate feedback on particular concepts or entities. For Okta, status can be used to display overall operational status all the way down to very granular concepts, like user status.
We provide semantic variants for Neutral, Success, Caution, and Danger, distinguished by applying a class to the root.
We provide both labeled and unlabeled Statuses, distinguished by applying a class to the root.
Most a11y concerns are met by utilizing the intended markup. For async statuses, the `role="status"` attribute should be used.
=> Component: Status

packages/odyssey/src/scss/components/_tab.scss
Explicitly adds text color css rule to `.ods-tabs--tab button`
=> Tab color element fix

packages/odyssey/src/scss/components/_button.scss
Small fix to prevent Button copy from wrapping - most common in tables.
Closes https://github.com/okta/odyssey/issues/548
=> Bug/548 - Prevent button text from wrapping

packages/odyssey/src/scss/abstracts/_tokens.scss
Fixes #579 by removing `border-default` variable
=> Removes border-default variable

packages/docs/components/link.md, packages/docs/getting-started/changelog.md, packages/odyssey/src/scss/base/_typography-link.scss
This removes the purple styling on `:visited` links. 
We've run into some styling limitations that have caused issues for design as well as minor but real security/privacy concerns on the browser side.
While this removes the affordance for "you have visited this link before", we feel the compromise is worthwhile.
=> Removes unique styling for :visited links

packages/docs/components/tab.md, packages/odyssey/src/scss/components/_tab.scss, packages/vuepress-theme-nimatron/global-components/OdsTabs.vue
Updates implementation so that `aria-selected` handles the display of the tab indicator line as opposed to handling positioning via JS (fixes #564)
cc: @mattkaniaris-okta
=> Update tab indicator implementation

.github/CODEOWNERS
This will allow @jeffbelser-okta to start reviewing Odyssey code (on `develop` merges until our release this week, when this gets moved to `master`).
=> Add J Belser to Codeowners

packages/docs/base/elements.md, packages/odyssey/src/scss/base/_typography-list.scss, packages/odyssey/src/scss/base/_typography-text.scss
This adds styling for three HTML elements we don't have yet:
- `pre` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre
- `dl`, `dt`, and `dd` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
- `details`/`summary` - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
Preview here: https://shred.ods.so/base/elements/
=> HTML styling: pre, description list, and details/summary

packages/docs/components/button.md, packages/docs/components/tooltip.md, packages/odyssey/src/scss/base/_iconography.scss, packages/odyssey/src/scss/components/_button.scss, packages/odyssey/src/scss/components/_tooltip.scss
This updates the Button and Tooltip docs to provide accessibility guidance for Iconography. 
This includes documenting the use of `aria-` attributes as well as best practices for icon-only buttons.
=> Fast Follow: update component docs for icon a11y

packages/docs/.vuepress/config.js
Title no longer reads as "VuePress" 😂 😭 
Closes #658
=> Bugfix: title attribute

packages/docs/base/tokens.md
Type samples were previously using one of the swatches intended to display token swatches, leading to some table layout weirdness.
Before:
After:
Closes: #670
=> bugfix: display type token samples as text, not swatch

package.json, packages/vuepress-theme-odyssey/.eslintignore, packages/vuepress-theme-odyssey/.eslintrc.js, packages/vuepress-theme-odyssey/package.json, yarn.lock
Adds eslint to monorepo, [eslint-config-vuepress](https://www.npmjs.com/package/eslint-config-vuepress) for use in vuepress-theme-odyssey (DRAFT PR is available [here](https://github.com/okta/odyssey/pull/667))
=> Adds eslint, eslint-config-vuepress for use in vuepress-theme-odyssey

packages/docs/.vuepress/config.js
Currently, VuePress turns all outbound links into open-external links and adds an SVG to indicate this.
we want neither of these things to happen, so let's disable both!
Before:
After:
Confirmed our styles and behaviors are unaffected by this change - this merely removes the additional processing VuePress was doing:
Closes #669
=> bugfix: disable automatic outbound link manipulation

packages/docs/components/link.md, packages/odyssey/src/scss/base/_iconography.scss, packages/odyssey/src/scss/base/_typography-link.scss
Adds guidance and catch-all styling for using Icons as Link content.
This adds an addition `.ods-link--has-icon` style for standalone links with Icons. Grid will treat the text leaf as an independent cell and lay things out automatically (also provides RTL support).
Closes https://github.com/okta/odyssey/issues/682
=> Styled Element: Links + Icons

packages/docs/base/elements.md, packages/odyssey/src/scss/components/_input-field.scss
This adds basic styling for the `<output>` element. Since use cases are broad, I haven't added any specific styling here other than a fallback for appropriate layout within ODS fields.
=> Styled Element: `output`

packages/odyssey/src/scss/abstracts/_functions.scss, packages/odyssey/src/scss/components/_modal.scss, packages/vuepress-theme-odyssey/styles/abstracts/_functions.scss, packages/vuepress-theme-odyssey/styles/components/_DocsPageHeader.scss, packages/vuepress-theme-odyssey/styles/components/_DocsSidebar.scss, packages/vuepress-theme-odyssey/styles/components/_DocsTopbar.scss, packages/vuepress-theme-odyssey/styles/index.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateComponent.scss, packages/vuepress-theme-odyssey/styles/templates/_DocsTemplateHome.scss
- add z-index function to Odyssey
- use z-index function in `DocsSidebar`, `DocsTopbar`, `DocsTemplateComponent` and `DocsTemplateHome`
Fixes #747 
Note: Follow up issue #773 has been logged to ensure Odyssey uses `z-index` function going forward.
=> Update modal z-index

packages/docs/components/button.md, packages/docs/components/checkbox.md, packages/docs/components/field-labels.md, packages/docs/components/link.md, packages/docs/components/radio-button.md, packages/docs/components/select.md, packages/docs/components/text-input.md, packages/odyssey/src/scss/abstracts/_mixins.scss, packages/odyssey/src/scss/components/_checkbox.scss, packages/odyssey/src/scss/components/_radio-button.scss
This updates the content for Checkbox, Radios, and Text Inputs as a template for form elements. It also includes the initial setup for Field Labels.
Tackling Select and Field Label content separately so avoid a cumbersome review.
Re: feedback - There are still some remaining questions about naming, field label docs, and which states to document. If possible, I'd like to hold out on those until we have a preview available with all form materials for easy review.
=> Docs content: Inputs

packages/docs/updates/index.md, packages/odyssey/CHANGELOG.md
- update "Updates" section to link to GH Release notes
- updates CHANGELOG to reflect the date the release went out, rather than when the changelog entry was authored.
=> Updates section

packages/docs/components/link.md, packages/docs/components/modal.md, packages/docs/components/tab.md, packages/docs/components/tooltip.md
- Fix sentence casing in Link doc header links
- Add `micromodal-data-close` to modal example buttons
- Wrap keyboard accessibility table with `Description` in Tab docs
- Remove legacy docs link in tooltip docs
=> Design review fixes

.github/workflows/preview.yml
Today, Github deprecated the use of `set-env` which was used heavily by the previews workflow to get the commit short-sha, message, and build a preview URL. This PR makes the appropriate updates resulting from that change.
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Fix Previews

packages/vuepress-theme-odyssey/package.json, yarn.lock
Updates focus-trap-vue dependency to no longer use the arnoldsandoval-okta/focus-trap-vue fork.
=> [OKTA-356709] Update focus-trap-vue dependency

packages/docs/components/text-input.md
This adds guidance for how to specify the input purpose via `autocomplete` when collecting personal information. I've also updated our text input examples to ensure they're compliant.
More context can be found in the ticket: https://oktainc.atlassian.net/browse/OKTA-361264
=> [a11y] adds input purpose guidance to docs

packages/odyssey/src/scss/components/_toast.scss
This adds a media query to check if `prefers-reduced-motion` is enabled. If so, we remove the automatic outbound animation. Since our component checks for that animation to finish before leaving the DOM, the user is able to view the Toast until they dismiss it manually.
Jira: https://oktainc.atlassian.net/browse/OKTA-361265
For some context, this is a system preference as seen here:
=> [a11y] respect prefers-reduced-motion in Toasts

.eslintrc.js, .github/workflows/preview.yml, README.md, header.js, package.json, packages/docs/package.json, packages/odyssey/package.json, packages/prism-theme-odyssey/src/index.js, packages/prism-theme-odyssey/src/utils/CustomPropertyInspector.js, packages/prism-theme-odyssey/webpack.config.js, packages/vuepress-theme-odyssey/.eslintrc.js, packages/vuepress-theme-odyssey/enhanceApp.js, packages/vuepress-theme-odyssey/index.js, packages/vuepress-theme-odyssey/utils/index.js, yarn.lock
This PR helps align a few details here in our monorepo with Okta's OSS guidance.
I've also reworked our lint script to support failing the CI build if a `.js` file is does not include our license header. A bit more effort will be required for `.vue` files or other source files we want to prefix in a similar fashion.
=> Legal updates for OSS

packages/docs/components/checkbox.md, packages/odyssey/src/scss/components/_checkbox.scss
Fixes incorrect display and `:hover` state of checked, disabled checkboxes. Adds example to HTML/CSS docs.
Preview: https://05774fe.ods.dev/components/checkbox/
=> fix: invalid checkbox disabled state

packages/odyssey/src/scss/components/_button.scss
This updates our Dismiss button to have an a11y compliant focus state. Examples below.
For the focus state, we leave off any color declarations, which allows the `box-shadow` to pick up the `color` in use.
```box-shadow: 0 0 0 2px;```
This allows for the Dismiss button to be used in multiple light/dark color contexts without the need for an additional variant.
NB: this change only changes our `:focus` state; `:hover` will behave as before without a focus ring.
Preview here: https://75d17a3.ods.dev/components/button/
=> update focus state for dismiss button

packages/docs/components/tab.md, packages/odyssey/src/scss/abstracts/_tokens.scss, packages/odyssey/src/scss/base/_typography-global.scss, packages/odyssey/src/scss/base/_typography-header.scss, packages/odyssey/src/scss/components/_infobox.scss, packages/odyssey/src/scss/components/_tab.scss, packages/vuepress-theme-odyssey/styles/components/_DocsPageHeader.scss
This updates our Typography in a few major ways:
- Our base font size is now `16px`, up from `14px`
- Our font stack now prefers Public Sans and Noto to Whyte
- Our body line-height is now `1.5`, down from `.7142857`
- This previous number was to allow for 16px-based spacing units with a 14px font-size
- Our scale ratio is now `1.1487`, giving us a heading selection of 16px, 18px, 21px, 24px, 28px, 32px
This PR also includes related fixes for a handful of components that previously relied on our odd 14/16 interplay.
Preview here: https://d24ea1d.ods.dev/base/typography/
=> Type Scale 4.0

packages/docs/components/text-input.md
Previously, our Search input docs were missing guidance to use `label` as normal. 
Also, the aria attributes for Search + Button inputs were utilized incorrectly.
=> Docs: fix HTML docs for Search inputs

.github/workflows/preview.yml
This PR caches `node_modules` directories within our monorepo during CI builds. It uses a content hash of every `yarn.lock` file (currently we have just one at the root) as a key for cache invalidation meaning any time a new dependency is added anywhere within the monorepo the cache is invalidated.
This speeds up our CI builds considerably as the cache weighs in currently at 176 MB and I saw a build speed improvement of roughly 3 minutes 30 seconds when the cache is warm vs cold.
=> cache node_modules in CI

.github/workflows/deployment.yml, .github/workflows/preview-deployment.yml, .github/workflows/stale.yml
Adds a stale workflow that uses [actions/stale](https://github.com/actions/stale) to mark and close stale issues and PRs after a predetermined amount of time.
The current time before stale and closed are totally arbitrary and copied from the demo at the link above. They seemed sensible to me, but if anyone has specific thoughts on what these values should be, drop them in the comments.
=> chore: add stale workflow, rename preview workflow

packages/docs/components/checkbox.md, packages/docs/components/field-labels.md, packages/docs/components/radio-button.md, packages/docs/components/select.md, packages/docs/components/text-input.md, packages/odyssey/src/scss/abstracts/_mixins.scss, packages/odyssey/src/scss/components/_checkbox.scss, packages/odyssey/src/scss/components/_radio-button.scss, packages/odyssey/src/scss/vendors-ext/_choices-ext.scss
This PR removes the reliance on `data-invalid` in favor of the `:invalid` state with class names as a fallback.
Docs note: @arnoldsandoval-okta currently, in Firefox + VuePress, `:enabled:required:empty` fields are marked as `:invalid` *before* a user interacts with the form, leading to a full page of errors on load. This does not occur on CodePen or in a plain HTML page. For now, I've removed the `required` attribute from doc examples that were causing this issue.
=> Refactor: remove data-attrs in favor of :invalid or class

packages/odyssey-react/src/components/TextInput/TextInput.stories.tsx, packages/odyssey-react/src/components/TextInput/TextInput.test.tsx, packages/odyssey-react/src/components/TextInput/index.tsx, packages/odyssey-react/src/utils/index.ts, packages/odyssey-react/src/utils/oid.test.ts, packages/odyssey-react/src/utils/oid.ts
This PR adds the baseline `<TextInput />` component. I plan to include separate components for the other variants not included with this work (`<TextArea />` etc).
=> feat(odyssey-react): add TextInput component

packages/docs/components/status.md, packages/odyssey-react/src/components/Status/Status.stories.tsx, packages/odyssey-react/src/components/Status/Status.test.tsx, packages/odyssey-react/src/components/Status/Status.tsx
This refactors our Status component (both packages) to utilize a `div/span` relationship instead of `dl/dd/dt`, as the latter was too verbose for screen readers. This also makes the `role="status"` attribute non-optional.
=> Status HTML Refactor

packages/odyssey-react/src/components/Tooltip/Tooltip.stories.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.test.tsx, packages/odyssey-react/src/components/Tooltip/index.tsx, packages/odyssey-react/src/index.ts
This PR performs a bit of cleanup for our `<Tooltip />` component
=> refactor(odyssey-react): cleanup Tooltip component

packages/odyssey-react/src/components/TextArea/TextArea.stories.tsx, packages/odyssey-react/src/components/TextArea/TextArea.test.tsx, packages/odyssey-react/src/components/TextArea/index.tsx, packages/odyssey-react/src/components/TextInput/TextInput.test.tsx, packages/odyssey-react/src/components/TextInput/index.tsx, packages/odyssey-react/src/utils/index.ts, packages/odyssey-react/src/utils/oid.test.ts, packages/odyssey-react/src/utils/oid.ts
This PR adds a new `<TextArea />` component
Additional commits included here:
* minor updates to our `oid` utility and exposing a `useOid` hook
* Refactoring TextInput logic for oid and rendering the label
=> feat(odyssey-react): add TextArea component

packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/Button/Button.test.tsx, packages/odyssey-react/src/components/Button/Button.tsx, packages/odyssey-react/src/components/Button/index.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.stories.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.test.tsx, packages/odyssey-react/src/components/Tooltip/index.tsx, packages/odyssey-react/src/index.ts, packages/odyssey-react/src/utils/omit.test.ts, packages/odyssey-react/src/utils/omit.ts
This pr adds a new `<Tooltip />` component
It also includes some necessary refactor for `<Button />` and adds a new `omit` util and corresponding hook
=> feat(odyssey-react): adds tooltip component

packages/odyssey-react/src/components/Button/index.tsx, packages/odyssey-react/src/utils/cx.test.ts, packages/odyssey-react/src/utils/cx.ts
This PR adds a new util `cx` that replaces the `classnames` dependency we previously installed. The idea here is that we can avoid the cost of network requests for each install (CI builds etc) into the future by rolling our own simple util.
=> feat(odyssey-react): add cx util

.github/workflows/deployment.yml, .gitignore
This PR adds a static build of our storybook playground into the publicly hosted dir for the vuepress docs site. Accessible via a URL path for now: `/sb/index.html`
=> chore: add sb deploy to workflow

packages/odyssey-eslint/src/index.js, packages/odyssey-react/jest.d.ts, packages/odyssey-react/package.json, packages/odyssey-react/src/components/Button/Button.test.tsx, packages/odyssey-react/src/components/Status/Status.test.tsx, packages/odyssey-react/src/components/Tag/Tag.test.tsx, packages/odyssey-react/src/components/TextArea/TextArea.test.tsx, packages/odyssey-react/src/components/TextInput/TextInput.test.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.test.tsx, packages/odyssey-react/tsconfig.json, yarn.lock
This PR adds a new testing util function `a11yCheck` to provide static analysis of our markup for a11y concerns.
<details>
<br>
<summary><strong>EXAMPLE OF TEST FAILURE</strong></summary>
<br>
</details>
=> test(odyssey-react): add a11yCheck test util

packages/odyssey-react/src/components/Button/index.tsx
This came up in our last craft discussion.
=> fix(odyssey-react): swap children to ReactText type

packages/odyssey-react/src/utils/omit.test.ts, packages/odyssey-react/src/utils/omit.ts
This PR refactors `omit` to include `style` as a default omitted prop (to enforce design consistency and easy to maintain styling APIs). It also cleans up the type declarations and removes memoization that actually hurts performance due to the way JS allocates a new referential identity for every rest parameter.
=> refactor(odyssey-react): omit

packages/odyssey-react/src/components/FieldLabel/FieldLabel.stories.tsx, packages/odyssey-react/src/components/FieldLabel/FieldLabel.test.tsx, packages/odyssey-react/src/components/FieldLabel/index.tsx, packages/odyssey-react/src/utils/cx.test.ts, packages/odyssey-react/src/utils/cx.ts
This PR adds a new `<FieldLabel />` component. I'm holding off on refactoring other form inputs to use this until we have our discussion next sprint regarding form design. This PR additionally fixes a small issue for `cx` where preceding falsy expressions would append a leading space into the class attribute in the DOM.
=> feat(odyssey-react): add FieldLabel component

packages/odyssey-eslint/package.json, packages/odyssey-eslint/src/index.js, yarn.lock
This PR introduces a new eslint preset for jsx flavored files to provide static analysis for common a11y concerns. This will provide another layer of automation to help us build accessible interfaces, catching issues even before running tests or manual audits.
=> feat(odyssey-eslint): add jsx-a11y recommended config

packages/odyssey-react/.storybook/main.js, packages/odyssey-react/.storybook/preview.js, packages/odyssey-react/package.json, packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/FieldLabel/FieldLabel.stories.tsx, packages/odyssey-react/src/components/Status/Status.stories.tsx, packages/odyssey-react/src/components/Tag/Tag.stories.tsx, packages/odyssey-react/src/components/TextArea/TextArea.stories.tsx, packages/odyssey-react/src/components/TextInput/TextInput.stories.tsx, packages/odyssey-react/src/components/Tooltip/Tooltip.stories.tsx, yarn.lock
This PR adds a new [storybook addon for a11y](https://storybook.js.org/addons/@storybook/addon-a11y). This addon allows us to *manually* check for accessibility concerns while building out components within the storybook playground.
This PR also contains a small refactor commit to de-duplicate configuration parameters for the [controls addon](https://storybook.js.org/addons/@storybook/addon-controls) to be located in the global `preview.js` file.
=> feat(odyssey-react): add storybook a11y

packages/docs/components/button.md, packages/docs/components/modal.md, packages/docs/components/tab.md, packages/docs/components/table.md, packages/docs/components/toast.md, packages/docs/components/tooltip.md, packages/docs/icons.md, packages/odyssey-react/src/components/Tooltip/Tooltip.stories.tsx, packages/odyssey-react/src/components/Tooltip/index.tsx, packages/odyssey/src/scss/components/_tooltip.scss
Now that our codebase has moved beyond physical properties, we should upgrade our language to match. At the simplest, this is moving from a Right/Left paradigm to a Start/End paradigm in documentation, props, and class names.
Jira: https://oktainc.atlassian.net/browse/OKTA-405624
=> Refactor: RTL Naming

packages/docs/components/button.md, packages/odyssey-react/src/components/Button/Button.stories.tsx, packages/odyssey-react/src/components/Button/index.tsx, packages/odyssey/src/scss/components/_button.scss
This PR adds the "Large" button variant to our styles and component + updates the Button docs to account for available sizes.
This also adds a `min-width` for `.ods-button-label`. This is applied to the label and not the Button to keep the requirement sequestered to Buttons with written labels.
=> Update available Button sizes

packages/odyssey/src/scss/components/_table.scss
Because it's always parsed LTR, numerical data in Tables should remain right-aligned for both LTR and RTL languages.
The ongoing [RTL document](https://docs.google.com/document/d/1yt4tyiFEjcdJVOXyPnTOIOmVkVIzG0cNYLjKkeA6J9s/edit#) has been updated to reflect this guidance.
=> fix(odyssey): numerical data should not flip in RTL

packages/odyssey-react/src/components/Banner/index.tsx, packages/odyssey-react/src/components/Infobox/Infobox.module.scss, packages/odyssey-react/src/components/Infobox/index.tsx, packages/odyssey-react/src/components/Modal/Modal.module.scss, packages/odyssey-react/src/components/Modal/index.tsx, packages/odyssey-react/src/components/Title/Title.module.scss, packages/odyssey-react/src/components/Title/Title.stories.tsx, packages/odyssey-react/src/components/Title/Title.test.tsx, packages/odyssey-react/src/components/Title/index.tsx, packages/odyssey-storybook/src/index.ts
[OKTA-419574](https://oktainc.atlassian.net/browse/OKTA-419574)
- Refactors `<Title />` types
- string based rather than numeric for easier JSX use
- Allows `level` prop to default to `"1"` as intended.
- Allows for omitted rest props against instrinsic h1 type
- Adds new style focused props as a temporary API until we have `<View />` or `<Box />`
- Fixes static ids for `<Modal />` component a11y associations
=> chore(odyssey-storybook): remove typography-header global styles

.github/workflows/deployment.yml
See if this fixes caching across branches 🤞  - build time is ~50% faster not having to download and build just under 500mB of dependencies.
[this github writeup describes the cache + branch relationship](https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows#example-of-search-priority).
=> chore: add workflow_dispatch to preview deployment & fix cache

packages/odyssey-typescript/package.json, packages/odyssey-typescript/tsconfig.strict.json, yarn.lock
This PR upgrades our TS depedency to [the latest minor release version](https://devblogs.microsoft.com/typescript/announcing-typescript-4-4/). I'd love to see us adopt [`exactOptionalPropertyTypes` ](https://www.typescriptlang.org/tsconfig#exactOptionalPropertyTypes) but we'll need to work through a separate batch of about 60 component prop violations where we explicitly pass undefined through.
=> feat(odyssey-typescript): upgrade to 4.4.2

packages/odyssey-react/src/components/Button/Button.module.scss, packages/odyssey-react/src/components/Status/Status.module.scss, packages/odyssey-storybook/package.json, packages/odyssey-transform-styles-babel-plugin/package.json, packages/odyssey/package.json, packages/odyssey/src/scss/abstracts/_functions.scss, packages/odyssey/src/scss/abstracts/_tokens.scss, packages/odyssey/src/scss/base/_typography-global.scss, packages/odyssey/src/scss/components/_button.scss, packages/odyssey/src/scss/components/_status.scss, packages/prism-theme-odyssey/package.json, packages/vuepress-theme-odyssey/package.json, packages/vuepress-theme-odyssey/styles/components/_DocsCardGroup.scss, packages/vuepress-theme-odyssey/styles/index.scss, yarn.lock
Transitions remaining packages from `node-sass` to `sass`, and updates the deprecated syntax throughout.
=> refactor: update SCSS to use Dart Sass syntax

packages/odyssey-lint-staged/src/index.js
Improve DX by automatically amending commits with prettier formatting changes.
This also fixes the stylelint and eslint commands to now run during the precommit hook
=> fix(odyssey-lint-staged): amend commit with prettier changes

packages/odyssey-storybook/src/index.ts
These two scss files do not contain styles that affect our components at this point FWICT based on grep of project source. Removing so that we can move toward CSS Modules more quickly and so that we don't introduce new implicit dependencies on them in any other future work.
[a11y sheet](https://github.com/okta/odyssey/blob/develop/packages/odyssey/src/scss/base/_accessibility.scss)
[icon sheet](https://github.com/okta/odyssey/blob/develop/packages/odyssey/src/scss/base/_iconography.scss)
=> feat: remove global accessibility and iconography styles from storybook

packages/odyssey/package.json
no need to execute sass to build the static CSS output for this package as part of our other npm lifecycle scripts as it is going to be removed :soon:
=> build(odyssey): remove sass build in prepare npm script

packages/odyssey-postcss-scss/package.json, packages/odyssey-postcss-scss/src/index.ts, packages/odyssey-postcss-scss/src/plugin.ts, packages/odyssey-postcss-scss/tsconfig.json, packages/odyssey-react/.postcssrc.js, packages/odyssey-react/package.json, packages/odyssey-react/src/components/Select/Select.module.scss, packages/odyssey-transform-styles-babel-plugin/package.json, packages/odyssey-transform-styles-babel-plugin/src/__tests__/__snapshots__/importVisitor.test.js.snap, packages/odyssey-transform-styles-babel-plugin/src/__tests__/__snapshots__/requireVisitor.test.js.snap, packages/odyssey-transform-styles-babel-plugin/src/__tests__/fixture.module.scss, packages/odyssey-transform-styles-babel-plugin/src/compile.ts
The motivation here is to remove a dependency on sass in our shared tooling that will be distributed downstream to other teams in the future.
=> build(odyssey-react): use odyssey-postcss-scss plugin

packages/conventional-changelog-odyssey/index.js, packages/conventional-changelog-odyssey/package.json, packages/odyssey-commitlint/package.json, packages/odyssey-commitlint/src/index.js, yarn.lock
Moving us back to the [conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/#specification) after finding the concrete implementation I couldn't find last week 😅
=> build: use conventional commits for changelog and lint

README.md, packages/odyssey-design-tokens/package.json, packages/odyssey-design-tokens/src/components/button.json, packages/odyssey-design-tokens/stylelint.config.js, packages/odyssey-storybook/.storybook/OdysseyTheme.js, packages/odyssey-storybook/.storybook/manager.js, packages/odyssey-storybook/.storybook/preview-head.html, packages/odyssey-storybook/.storybook/preview.js, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/contributing/Documentation.stories.mdx, packages/odyssey-storybook/src/guidelines/DocsStatus.stories.mdx, yarn.lock
Customizes our SB UI via the theming interface with values from @josesolano-okta.
=> docs: adds an Odyssey theme for Storybook

packages/odyssey-react/src/components/Button/Button.module.scss, packages/odyssey-react/src/components/Button/Button.tsx, packages/odyssey-react/src/components/Text/Text.module.scss, packages/odyssey-react/src/components/Text/Text.tsx, packages/odyssey-react/src/components/Toast/Toast.tsx
Removes dependency on global text styles.
The interactive states of button required the addition of Text styles to enable hover, focus, and disabled states. Having Text as a child of button also means that those style are currently enabled via descendant selectors.
=> feat(odyssey-react): add Text component to Button

packages/odyssey-storybook/.storybook/preview.js, packages/odyssey-storybook/src/components/Box/Box.mdx, packages/odyssey-storybook/src/components/Box/Box.stories.tsx, packages/odyssey-storybook/src/components/ScreenReaderText/ScreenReaderText.stories.tsx, packages/odyssey-storybook/src/components/Text/Text.mdx, packages/odyssey-storybook/src/components/Text/TextElements.stories.tsx
This PR adds baseline documentation for Text and Box. It also migrates our Text "descriptions" out of CSF and into MDX.
Prior conversation can be found here: https://github.com/okta/odyssey/pull/1188
=> Text/Box Docs

packages/odyssey-react/src/components/TextInput/TextInput.module.scss, packages/odyssey-react/src/components/TextInput/index.tsx, packages/odyssey-storybook/src/components/FieldGroup/FieldGroup.stories.tsx
Fixes the layer height of our Search Icon to prevent it from leaking across layers. This also improves tab ordering for any outdated screen readers that ignore `presentation`.
=> Fix: Search/Select icon layering

packages/odyssey-react/.postcssrc.js, packages/odyssey-react/src/components/Select/Select.module.scss, packages/odyssey-storybook/src/components/Select/Select.stories.tsx
- Absolutely positions "remove" buttons to ensure vertical alignment
- Remove button inline padding now matches block
- Sets a max-width on multi-select items to prevent overflow
- Increases dropdown indicator padding to prevent overlap
=> Fix: Select blemishes

packages/odyssey-design-tokens/src/color/functional.json, packages/odyssey-design-tokens/src/font.json, packages/odyssey-design-tokens/src/space.json, packages/odyssey-react/src/components/Status/Status.module.scss, packages/odyssey-react/src/components/Status/Status.theme.ts, packages/odyssey-react/src/components/Status/Status.tsx
Updates Status to use design tokens.
Creates new tokens for:
- Color: Caution, Success, and Neutral bases
- Spacing: relative and fixed units (these are hard coded and not generated)
- Font: bold weight
Two types of values have not been converted:
- Private, component-specific variables that need not be themed (yet)
- Values that rely on `calc()`
=> withTheme for Status

packages/odyssey-postcss-theme/src/plugin.test.js, packages/odyssey-react-theme/src/withTheme/factory.tsx, packages/odyssey-react-theme/src/withTheme/utils.ts
* use fallback values directly for browser that do not support custom properties i.e. IE11
* refactor `WithTheme` implementation for better type safety and clarity
* pass shallow copy of theme to reducer to avoid accidental mutation of context value/props
* throw when invalid theme value is referenced in style module to avoid typo errors (no type safety in CSS afterall)
=> theme cleanup

packages/odyssey-react/src/components/Field/Field.test.tsx, packages/odyssey-react/src/components/Field/Field.tsx, packages/odyssey-react/src/components/FieldGroup/FieldGroup.test.tsx, packages/odyssey-react/src/components/Form/Form.test.tsx
This PR does the following:
* Add a baseline of unit tests for components that need them
* Add accessibility unit tests for components that need them
=> chore(odyssey-react): add missing unit coverage

packages/odyssey-postcss-scss/package.json, packages/odyssey-postcss-scss/src/plugin.test.js, packages/odyssey-postcss-theme/src/plugin.ts, packages/odyssey-react/src/components/Status/Status.module.scss, packages/odyssey-transform-styles-postcss-preset/package.json, packages/odyssey-transform-styles-postcss-preset/src/plugin.test.js
This PR does the following:
* Allow `calc()` expressions to be used with custom properties in our build toolchain
* [OKTA-455370](https://oktainc.atlassian.net/browse/OKTA-455370)
* Improve unit test coverage for build tooling packages
=> chore(odyssey-postcss-theme): replace values in OnceExit event

packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/Link.theme.ts, packages/odyssey-react/src/components/Link/Link.tsx
@josesolano-okta, FYI I've updated the spacing units for Icons/Indicators from `0.2em` to our standard xs spacing of `0.375em`
https://81a7b1b.ods.dev/?path=/story/components-link--default
=> enable theming for Link

.eslintrc.js, commitlint.config.js, packages/odyssey-eslint/package.json, packages/odyssey-eslint/src/index.js, packages/odyssey-react-theme/package.json, packages/odyssey-react/package.json, packages/odyssey-storybook/package.json, packages/odyssey-transform-styles-babel-plugin/package.json, packages/odyssey-transform-styles-babel-plugin/src/transformStyles.ts, stylelint.config.js, yarn.lock
This PR does the following:
* Add static analysis to ensure consumed dependencies are listed correctly in the corresponding package.json
* [rule documentation](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md) 
* Within a monorepo, publishing packages that are broken at install time due to missing dependencies is an easy trap to stumble into. This is because at develop time, dependencies are often available to the node module resolution algorithm transitively, or even via sibling packages. The assumed version (or any version) may not be present at install time. Being explicit about our dependency graph will help us maintain quality as we scale.
* Update violations via adding dependencies to package.json files, or escaping in the case of …
=> build: add no-extraneous-dependencies rule

packages/odyssey-react/src/components/TextInput/TextInput.tsx
I removed an unnecessary ternary from `TextInput`.
=> 🔥 Removed unnecessary ternary

packages/odyssey-react/src/components/Checkbox/Checkbox.tsx, packages/odyssey-react/src/components/Field/Field.test.tsx, packages/odyssey-react/src/components/Field/Field.tsx, packages/odyssey-react/src/components/Field/types.ts, packages/odyssey-react/src/components/Radio/Radio.test.tsx, packages/odyssey-react/src/components/Radio/RadioButton.tsx, packages/odyssey-react/src/components/Radio/RadioGroup.tsx, packages/odyssey-react/src/components/Select/Select.tsx, packages/odyssey-react/src/components/TextArea/TextArea.test.tsx, packages/odyssey-react/src/components/TextArea/TextArea.tsx, packages/odyssey-react/src/components/TextInput/TextInput.test.tsx, packages/odyssey-react/src/components/TextInput/TextInput.tsx, packages/odyssey-storybook/src/components/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/Form/Form.stories.tsx, packages/odyssey-storybook/src/components/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/TextInput/TextInput.stories.tsx
Leaving aside the desired union type for `required`/`optionalLabel` for now.
=> fix(odyssey-react): required prop default to true 

.github/CONTRIBUTING.md, packages/odyssey-storybook/src/contributing/GettingStarted.stories.mdx, packages/odyssey-storybook/src/guidelines/Philosophy.stories.mdx
This PR adds a new `Philosophy.stories.mdx` writeup under the doc site `Guidelines` to better describe some of the design influences for the the project that can help guide new contributors as well!
Additionally, it renders our contributing writeup on the doc site as well under the `Contribution` section
=> docs: add philosophy writeup

packages/odyssey-storybook/applitools.config.js, packages/odyssey-storybook/src/components/FieldGroup/FieldGroup.stories.tsx, packages/odyssey-storybook/src/components/Text/TextStyles.stories.tsx
* [chore(odyssey-storybook): fix heading for Infobox in FieldGroup story](https://github.com/okta/odyssey/commit/c06b870beee0778601e223e23207820d48175835)
* [chore(odyssey-storybook): rename title to heading for Text story](https://github.com/okta/odyssey/commit/aa7d5e0844acded23b1c71d3ca5ba24f924bfc2c)
* [chore(odyssey-storybook): exclude Toast.Provider story from VRT](https://github.com/okta/odyssey/commit/cbd56c2ea6c79eca8d6137c51269ee938554aa07)
=> chore(odyssey-storybook): fixes + cleanup

packages/odyssey-react/src/components/Infobox/Infobox.module.scss, packages/odyssey-react/src/components/Infobox/Infobox.tsx, packages/odyssey-storybook/src/components/Infobox/Infobox.stories.tsx
This change allows for content to be displayed without a heading and not have any gap between the content and the top of the Infobox.
=> Infobox content gap bugfix

packages/odyssey-react/src/components/Checkbox/Checkbox.tsx, packages/odyssey-react/src/components/Radio/RadioButton.tsx
This PR adds relative position to the Box containers in Checkbox and Radio to ensure their absolutely positioned hidden input elements do not unexpectedly reposition.
=> fix(odyssey-react): Checkbox and Radio hidden element position

packages/odyssey-transform-styles-babel-plugin/src/__tests__/__snapshots__/importVisitor.test.js.snap, packages/odyssey-transform-styles-babel-plugin/src/__tests__/__snapshots__/requireVisitor.test.js.snap, packages/odyssey-transform-styles-postcss-preset/package.json, packages/odyssey-transform-styles-postcss-preset/src/plugin.ts, packages/odyssey-transform-styles-postcss-preset/src/types.d.ts, yarn.lock
This PR changes how our build generates class names. Previously hashing was done with the contents of the filename and class name which lead to bugs across versions of Odyssey deployed within the same browser frame. We now hash based on the contents of the style module and use a base62 encoding to further reduce any accidental collisions by two orders of magnitude or so.
=> fix: improve class name hashing

.npmrc, packages/odyssey-react/src/components/TextInput/TextInput.test.tsx, packages/odyssey-react/src/components/TextInput/TextInput.tsx
Conditionally display the aria-describedby attribute in the text input field (`TextInput` component), only adding the attribute when a hint or an error is present.
See https://oktainc.atlassian.net/browse/OKTA-473744 (Okta employees only)
=> fix(odyssey-react): conditionally display aria-describedby attribute in TextInput component

.npmrc, packages/odyssey-react/src/components/Checkbox/Checkbox.test.tsx, packages/odyssey-react/src/components/Checkbox/Checkbox.tsx, packages/odyssey-react/src/components/Icon/SvgIcon.tsx
Conditionally display the `aria-describedby` attribute to the checkbox input field, only adding the attribute when an error is present.
See https://oktainc.atlassian.net/browse/OKTA-473739 (Okta employees only)
=> fix(odyssey-react): conditionally display aria-describedby attribute to avoid a11y warnings in Checkbox component

packages/odyssey-ie-11-sandbox/src/App.tsx, packages/odyssey-react/src/components/Banner/Banner.module.scss, packages/odyssey-react/src/components/Banner/Banner.theme.ts
This PR makes Banner IE11-friendly and updates our styles to match the most recent design.
Some theme variables are removed; however, the React API does not allow the Success variant, so these were extraneous.
=> feat(odyssey-react): update Banner styles and make Banner IE11-friendly

packages/odyssey-ie-11-sandbox/src/App.tsx, packages/odyssey-react/src/components/List/List.module.scss
This updates `dl` to be IE11-friendly.
=> Description List: IE11-friendly

packages/odyssey-ie-11-sandbox/src/App.tsx, packages/odyssey-react/src/components/Infobox/Infobox.module.scss, packages/odyssey-react/src/components/Infobox/Infobox.theme.ts, packages/odyssey-react/src/components/Infobox/Infobox.tsx, packages/odyssey-storybook/src/components/Infobox/Infobox.stories.tsx
This PR makes Banner IE11-friendly and updates our styles to match the most recent design. Changes to the component itself reflect pattern-matching with the related Toast and Banner components.
=> Infobox: IE11-Friendly + Style Update

packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/Link.test.tsx, packages/odyssey-react/src/components/Link/Link.theme.ts, packages/odyssey-react/src/components/Link/Link.tsx, packages/odyssey-storybook/src/components/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/Infobox/Infobox.stories.tsx, packages/odyssey-storybook/src/components/Link/Link.stories.tsx
Updates Link variant names: "primary" is now "default"; "secondary" is now "monochrome".
=> Update Link variant names

packages/babel-plugin-fully-specified/babel.config.json, packages/babel-plugin-fully-specified/package.json, packages/babel-plugin-fully-specified/src/__tests__/__snapshots__/plugin.test.js.snap, packages/babel-plugin-fully-specified/src/__tests__/plugin.test.js, packages/babel-plugin-fully-specified/src/index.ts, packages/babel-plugin-fully-specified/src/plugin.ts, packages/babel-plugin-fully-specified/tsconfig.json, packages/odyssey-react-theme/babel.config.cjs, packages/odyssey-react/babel.config.cjs
This PR uses our build toolchain to create fully specified module imports/exports before we publish production code. This is important because ultimately we are targeting a browser based platform that requires this (see spec details below). We also have a necessary intermediate step of using module bundlers applied by downstream teams which will also need to interop with our module syntax. Making this change allows both platforms to understand our ESM code.
Background information:
* [WHATWG](https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier)
* https://nodejs.org/docs/latest-v16.x/api/esm.html#esm_modules_ecmascript_modules
* https://nodejs.org/docs/latest-v16.x/api/esm.html#esm_resolution_algorithm
This PR purposefully does not update our source code …
=> build fully specified imports for prod

packages/browserslist-config-odyssey/index.ts
This PR exposes two new browserslist configs that can be activated without any explicit config via conventional `NODE_ENV` values of `development` and `test`. Under this approach, a standard `create-react-app` workflow will compile successfully. Using the configuration as it stood before (defaulting to `production`/`all`) create-react-app could not start the development server.
This change **could** lead to broken builds in test or development environments for downstream teams who previously cared about exercising ie11 in those environments. To work around this they'll now need to set an explicit `BROWSERSLIST_ENV` value to `all` or `production`
=> feat(browserslist-config-odyssey): expose development and test configs

yarn.lock
This PR updates the `caniuse-lite` dependency leveraged by browserslist to determine compatibility for browser targets. This is a package that needs to be updated occasionally to have the most up to date browser target info available locally. I ran `$ ./node_modules/.bin/browserslist --update-db` and then committed the resulting `yarn.lock` changes
=> build: update browserslist caniuse-lite dep

packages/odyssey-react/src/components/Banner/Banner.module.scss, packages/odyssey-react/src/components/Banner/Banner.theme.ts, packages/odyssey-react/src/components/Banner/Banner.tsx
Extends the `max-width` for Banner to `MaxLineLength * 2`. For now, this is not accessible via a unique theme variable, as we do not want folks re-theming their Banner layout.
=> refactor(odyssey-react): extends max-width for Banner content

packages/odyssey-react/src/components/Table/TableSortButton.module.scss
Updates our styles to account for there now being two icons in the Sort button; now uses `--SortIndicatorFontSize` rather than a magic `em` to set the width.
https://oktainc.atlassian.net/browse/OKTA-481541
=> Fix: Table sort indication overlaps label with multiple icons for unsorted

packages/odyssey-react/src/components/Link/Link.module.scss
Fixes https://oktainc.atlassian.net/browse/OKTA-481515 by ensuring Link Icons/Indicators are constrained to their associated text height. This was a Chrome-only bug--Safari and Firefox remain 💯 after the fix.
=> fix(odyssey-react): Link Icons now match text height

packages/odyssey-react/src/components/Tabs/Tabs.module.scss, packages/odyssey-react/src/components/Tabs/Tabs.test.tsx, packages/odyssey-react/src/components/Tabs/Tabs.theme.ts, packages/odyssey-react/src/components/Tabs/Tabs.tsx
Addresses minor a11y issues for `:focus` and updates designs to match the latest from @josesolano-okta.
- Tabs are now Text, Sub in color unless Selected (then Primary, Base)
- Tabs are now normal weight unless Selected (then Bold)
- Hover state text is now in Primary, Base
- Focus state now happens at the label level instead of the label container and it is styled the same as a focused link
=> fix(odyssey-react): update Tab states to be more accessible

packages/odyssey-react/src/components/TextInput/TextInput.module.scss, packages/odyssey-react/src/components/TextInput/TextInput.test.tsx, packages/odyssey-react/src/components/TextInput/TextInput.theme.ts, packages/odyssey-react/src/components/TextInput/TextInput.tsx, packages/odyssey-react/src/utils/useSharedRef.ts, packages/odyssey-storybook/src/components/TextInput/TextInput.stories.tsx
This PR exposes `prefix` and `suffix` string props for the `TextInput` component.
`prefix` insert a string before the input, `suffix` will append a string after the input
If the `TextInput` is `type="search"` then any prefix text will be ignored
=> feat(odyssey-react): add prefix and suffix text props to TextInput component

packages/odyssey-react/src/components/Button/Button.module.scss, packages/odyssey-react/src/components/Button/Button.theme.ts
Updates Dismiss styles for better accessibility and parity with Figma.
- @josesolano-okta has proposed renaming this to "Ghost" or "Floating" since dismissal is not the only use case, I'm +1 there
- The "inverted" variant can be removed since we are using standard Button `:focus` states now
If we have good alignment on making the follow-up changes, I'll address them here. If we need to discuss, I can create cards for next sprint.
=> fix(odyssey-react): accessible focus states for Dismiss Button

packages/odyssey-react/src/components/Banner/Banner.module.scss, packages/odyssey-storybook/.storybook/manager-head.html, packages/odyssey-storybook/applitools.config.js, packages/odyssey-storybook/src/components/Banner/Banner.mdx, packages/odyssey-storybook/src/components/Banner/Banner.stories.tsx
Updates Banner's stories to cover all variations.
Also include decorators for:
- hiding Stories from the sidebar
- marking Stories as "Don't" variations for doc guidance
=> docs(odyssey-storybook): update Banner stories to showcase all options

packages/odyssey-storybook/.storybook/manager-head.html, packages/odyssey-storybook/.storybook/preview-head.html, packages/odyssey-storybook/applitools.config.js, packages/odyssey-storybook/src/components/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/Infobox/Infobox.stories.tsx
- Updates `Infobox` stories to include previous examples and variants
- Adds "Do" and "Don't" styling for stories
New decorators for Do / Don't examples:
=> Docs: Infobox stories

packages/odyssey-react/src/components/Banner/Banner.tsx, packages/odyssey-react/src/components/Button/Button.module.scss, packages/odyssey-react/src/components/Button/Button.theme.ts, packages/odyssey-react/src/components/Button/Button.tsx, packages/odyssey-react/src/components/Modal/Modal.tsx, packages/odyssey-react/src/components/Toast/Toast.tsx, packages/odyssey-storybook/src/components/Button/Button.mdx, packages/odyssey-storybook/src/components/Button/Button.stories.tsx
Renames our "dismiss" Button variant to "floating" and removes the previous "invertedDismiss" variant.
Use cases remain the same until we combine "clear" and "floating" into one variant.
=> Button: rename "dismiss" to "floating"

packages/odyssey-react/src/components/Checkbox/Checkbox.module.scss, packages/odyssey-react/src/components/TextInput/TextInput.module.scss, packages/odyssey-react/src/components/TextInput/TextInput.theme.ts
Makes `border-color` `:hover` behavior consistent across invalid Form controls.
=> fix(odyssey-react): make invalid border behavior consistent

packages/odyssey-react/src/components/Infobox/Infobox.tsx
The aria role of "status" is not allowed for `aside` elements, so `Infobox` is now a `div`.
=> fix(odyssey-react): [a11y] Infobox is no longer an `aside`

packages/odyssey-react/src/components/Select/Select.module.scss, packages/odyssey-react/src/components/Select/Select.theme.ts
=> fix(odyssey-react): MultiSelect dismissal is visible again

.github/workflows/ci.yml, .github/workflows/warm-cache.yml, .github/workflows/x-browser-vrt.yml, .nvmrc, scripts/setup.sh
Uses `v16.15.0` instead of `lts/gallium`.
=> build: use fixed node version instead of alias

.yarnrc.yml
build: use environment variable to override okta registry server for ci
Since there is no way to do complex yarn environment variable overrides, we must explicitly look for `OKTA_NPM_REGISTRY_SERVER`
See external-build-scripts PR https://github.com/okta/external-build-scripts/pull/28
=> build: use environment variable to override okta registry server for ci

packages/odyssey-react/src/components/Banner/Banner.module.scss, packages/odyssey-react/src/components/Banner/Banner.theme.ts, packages/odyssey-react/src/components/Banner/Banner.tsx, packages/odyssey-storybook/src/components/Banner/Banner.mdx, packages/odyssey-storybook/src/components/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/Toast/Toast.mdx, packages/odyssey-storybook/src/guidelines/DocsStatus.stories.mdx
Renames 'dismissable' props/docs/styles to 'dismissible'.
=> Fix: rename misspelled 'dismissable' props/docs/styles

packages/babel-plugin-fully-specified/package.json, packages/browserslist-config-odyssey/package.json, packages/odyssey-babel-loader/package.json, packages/odyssey-babel-plugin/package.json, packages/odyssey-babel-preset/package.json, packages/odyssey-design-tokens/package.json, packages/odyssey-postcss-preset/package.json, packages/odyssey-postcss-scss/package.json, packages/odyssey-postcss-theme/package.json, packages/odyssey-react-theme/package.json, packages/odyssey-react/package.json, packages/odyssey-storybook/package.json
Here's another fix for the publish script 😅! I was able to reproduce the error we were seeing in bacon on my local. I'm unable to find any github issues in lerna that matches what we are seeing. But in general it appears that lerna does not officially support yarn 2/3...
Here's what I think is happening: it is always using `npm pack` triggering lifecycle scripts such as `prepack`. This ignores the `npmClient` configuration which we have set to `yarn` ([Lerna code](https://github.com/lerna/lerna/blob/8b99493ac90484e05f7ebee533c0763534d60218/commands/publish/index.js#L634)) ([odyssey lerna config](https://github.com/okta/odyssey/blob/develop/lerna.json#L3)). Since `npm` has a different way of resolving dependencies than `yarn`, that may be causing the error that `sh: prepack: command not …
=> fix: explicitly call yarn in prepack lifecycle script for lerna

packages/odyssey-react/src/components/Modal/Modal.module.scss, packages/odyssey-react/src/components/Modal/Modal.theme.ts, packages/odyssey-react/src/components/Modal/Modal.tsx
Updates our Modal to be aligned with the latest visual designs. This also adds tokens for Header, Content, and Footer padding to make updates simpler in the future.
=> [Design, FixIt] update Modal display, add tokens for Padding

packages/odyssey-storybook/.storybook/preview.js, packages/odyssey-storybook/src/components/Banner/Banner.mdx, packages/odyssey-storybook/src/components/Box/Box.mdx, packages/odyssey-storybook/src/components/Button/Button.mdx, packages/odyssey-storybook/src/components/Checkbox/Checkbox.mdx, packages/odyssey-storybook/src/components/CircularLoadIndicator/CircularLoadIndicator.mdx, packages/odyssey-storybook/src/components/Field/Field.mdx, packages/odyssey-storybook/src/components/FieldGroup/FieldGroup.mdx, packages/odyssey-storybook/src/components/Form/Form.mdx, packages/odyssey-storybook/src/components/Heading/Heading.mdx, packages/odyssey-storybook/src/components/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/Link/Link.mdx, packages/odyssey-storybook/src/components/List/List.mdx, packages/odyssey-storybook/src/components/Modal/Modal.mdx, packages/odyssey-storybook/src/components/NativeSelect/NativeSelect.mdx, packages/odyssey-storybook/src/components/Radio/Radio.mdx, packages/odyssey-storybook/src/components/Select/Select.mdx, packages/odyssey-storybook/src/components/Status/Status.mdx, packages/odyssey-storybook/src/components/Table/Table.mdx, packages/odyssey-storybook/src/components/Tabs/Tabs.mdx, packages/odyssey-storybook/src/components/TagList/TagList.mdx, packages/odyssey-storybook/src/components/Text/Text.mdx, packages/odyssey-storybook/src/components/TextArea/TextArea.mdx, packages/odyssey-storybook/src/components/TextInput/TextInput.mdx, packages/odyssey-storybook/src/components/Toast/Toast.mdx, packages/odyssey-storybook/src/components/Tooltip/Tooltip.mdx
This makes "Docs" tab our default when viewing Storybook. The addition of `<Meta anchor />` is required on `.mdx` pages with stories, so that Storybook doesn't auto-scroll to the first CSF on load.
=> [Docs] Make "Docs" tab the default rather than "Canvas"

packages/odyssey-react/src/components/Box/_box-hover-focus.scss, packages/odyssey-react/src/components/Checkbox/Checkbox.module.scss, packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Radio/RadioButton.module.scss, packages/odyssey-react/src/components/Tabs/Tabs.module.scss, packages/odyssey-react/src/components/Text/Text.module.scss
Transitions most components to use `:focus-visible` rather than `:focus`. TextInput and components sharing that form factor continue to use `:focus` for an additional affordance when inputting data.
=> feat(odyssey-react): utilize :focus-visible for less intrusive ui

packages/odyssey-react/src/components/Link/Link.module.scss, packages/odyssey-react/src/components/Link/Link.theme.ts
Adds a hover state to our Monochrome Link variant.
=> feat(odyssey-react): add :hover to Link, Monochrome

packages/odyssey-react/src/components/Infobox/Infobox.module.scss, packages/odyssey-react/src/components/Infobox/Infobox.theme.ts, packages/odyssey-storybook/src/components/Infobox/Infobox.mdx
This PR sets Infobox's `max-width` to `100%` as requested here: https://oktainc.atlassian.net/browse/OKTA-500082
The docs have also been updated to indicate that Infobox will now be constrained by its parent.
=> Infobox: remove width constraints

packages/odyssey-react/src/components/Modal/Modal.module.scss, packages/odyssey-storybook/src/components/Modal/Modal.stories.tsx
Previously, Modal overflow was set to `auto`, leading to scrolling behavior when a Dropdown is activated. This PR sets `overflow` to `visible` and adds a Select to the Modal story for testing.
=> Fix: Show overflow content in Modals

packages/odyssey-react/src/components/Form/Form.module.scss
Change Form actions to follow the F pattern rather than Z.
=> refactor(odyssey-react): align Form actions to the left

packages/odyssey-react/src/components/Infobox/Infobox.theme.ts
=> fix(odyssey-react): fix Infobox icon alignment

packages/odyssey-design-tokens/package.json, packages/odyssey-react-theme/package.json, packages/odyssey-react/package.json
This flag gives signal to modern bundlers to proper tree shake odyssey-react package at production build stage.
Reference: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
=> chore(odyssey-react): add sideEffects flag to enable bundler level tree shaking

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-storybook/src/components/CircularProgress/CircularProgress.mdx, packages/odyssey-storybook/src/components/CircularProgress/CircularProgress.stories.tsx
This adds a component theme for `<CircularProgress>` as well as stories for the `determiniate` and `indeterminate` variants.
The theme values here are still hard-coded. This will be refactored whenever variables are available for use within `theme`.
MUI uses a single `svg` circle, which precludes us from styling this to match exactly (ODS uses two differently-colored circles). My feeling is that we should lead with this and then construct our own `CircularProgress` component later if the style differentiation is important.
This theme does not include a theme override for the animation. While this is possible, I am unclear on what that syntax should look like within the theme object. 
@magizh-okta @josesolano-okta if this is acceptable, I will leave this as-is for now and we can revisit …
=> MUI Theme: CircularProgress

packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/components/Link/Link.tsx, packages/odyssey-react-mui/src/components/Link/index.tsx, packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-react-mui/src/themes/odyssey/components.types.ts, packages/odyssey-react-mui/src/themes/odyssey/theme.ts, packages/odyssey-storybook/src/components/MuiLink/MuiLink.mdx, packages/odyssey-storybook/src/components/MuiLink/MuiLink.stories.tsx
- Adds new story for the material ui link [component]( https://mui.com/material-ui/api/link/), listed under MUI Components/Link in our storybook
- Link props matches odyssey prop values
- Mui link style overrides for odyssey props contained inside @okta/odyssey-react-mui/themes/odyssey
- [fixes](https://github.com/mui/material-ui/issues/28633#issuecomment-930098459) theme font-family by applying it as a style override so it applies to all components
=> chore(odyssey-react-mui): add Link component

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-storybook/src/components/MuiButton/MuiButton.mdx, packages/odyssey-storybook/src/components/MuiButton/MuiButton.stories.tsx
- fixes style override for component MuiButton which was breaking a couple prop situations, such as `startIcon`, `endIcon`, and `data-*`
- adds stories for button text with icon and button with icon only
- adds style overrides for icon to match odyssey
- fixes button variant danger in disabled state
=> chore(odyssey-storybook): add mui button icon stories

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
Adds theming for:
- Button
- Adds variables for padding, adjusts height
- FormControl
- Adds correct `width` and `max-width` behavior
- InputLabel
- Disables "floating" behavior for labels
- NativeSelect
- Adds some fallback styling; `<Select native>` should be preferred
- OutlinedInput
- Adds theme to match ODS
- SvgIcon
- Removes individual icon styling for now; MUI relies on the parent component setting styles
Adds stories for:
- `<Select native>`
=> Theme for Select, Native

package.json, yarn.lock
Lerna was on v4 and had been a dead project for a while. I considered changing us to a different monorepo technology but decided the best course of action was to update Lerna to the latest version now that Nx is in charge of the project and is releasing security updates.
[OKTA-473520](https://oktainc.atlassian.net/browse/OKTA-473520)
=> fix: Update Lerna to v5

packages/odyssey-storybook/src/components/odyssey-legacy/TextInput/TextInput.mdx
Removes reference to a missing story in our legacy docs.
=> docs(odyssey-storybook): remove docs for unsupported Text story

packages/odyssey-react-mui/src/themes/odyssey/components.ts
Adds appropriate styling for `:focus-visible` states on `Button`.
=> fix(odyssey-react-mui): fix Button :focus-visible styles

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-react-mui/src/themes/odyssey/palette.ts, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.mdx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx
- Hover state for the input field is now `gray[900]`
- Text area now has correct padding, defaults to 3 rows
- Hint default is now `null`
- Adds a text field story for `hint`
- Updates `disabled` state
=> TextField: UI updates

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
This removes the "Dismiss" action from Toast, instead relying on the transient state to handle removal.
=> Update: Remove "Dismiss" action from Toast

packages/odyssey-react-mui/src/themes/odyssey/components.ts, packages/odyssey-react-mui/src/themes/odyssey/typography.ts, packages/odyssey-react-mui/src/themes/odyssey/typography.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/PasswordInput/PasswordInput.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.mdx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx
This PR adds documentation, stories, and styles for Form-related components.
The stories are a template for future `Form` and `FieldGroup` components. For now, this acts as a guide to self-assembly until those components are available.
=> Theme & Docs for Form

packages/odyssey-react-theme/src/withTheme/stylesheet.ts
Added a connection for legacy Odyssey apps to utilize a nonce.
=> feat: added nonce capability for legacy Odyssey

packages/odyssey-react-mui/src/themes/odyssey/components.tsx
Themes `Alert` to utilize ODS icons by default and sets default props for `SvgIcon`.
=> Apply ODS Icons to MuiAlert, set props for SvgIcon

packages/odyssey-react-mui/src/themes/odyssey/components.types.ts, packages/odyssey-react-mui/src/themes/odyssey/typography.types.ts
A small fix to ensure our typography type mods match the available styles.
=> fix(odyssey-react-mui): remove `body` from type mods

packages/odyssey-react-mui/src/themes/odyssey/components.tsx
Fixes previously hidden outline on `:focus-visible` `<Link>` inside `Alert.Message`.
=> fix(odyssey-react-mui): fixes focus outline on Infobox links

packages/odyssey-react-mui/src/themes/odyssey/components.tsx
Adds `:hover` state to non-interactive table rows.
=> fix(odyssey-react-mui): fix bg color on table row hover

packages/odyssey-react-mui/src/Link.tsx
When using the `Link` component, the following error will be logged in the console:
```
Warning: forwardRef render functions accept exactly two parameters: props and ref. Did you forget to use the ref parameter?
```
`ref` is not used in Links so usage of `forwardRef` is unnecessary. This PR removes it from the component.
=> fix: remove forwardRef from Link

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/typography.ts, packages/odyssey-react-mui/src/theme/typography.types.ts
Increases the default icon size to `1.14285714em`, which matches our UI type line-height. This is achieved by adding the missing `theme.typography.ui` variant, for which we already have tokens.
I've also refactored any places where that was previously hard-corded to instead utilize the theme variable.
=> feat(odyssey-react-mui): increase default icon size to 16px

packages/odyssey-react-mui/src/theme/components.tsx
`MuiBackdrop` always inherits from `root`, even when using `invisible`, so we need to override both.
=> fix(odyssey-react-mui): override MuiBackdrop colors correctly

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
Preview: https://214d1ce.ods.dev/?path=/docs/mui-components-alerts-toast--info
- Toasts now support `action`
- A dismissible variant is now available
- When we move to wrapping and exporting, we'll revisit when each prop is allowed (e.g. is `action` only allowed in conjunction with `isDismissible`)
- Toast no longer supports `content` and `title`
- `content` now uses the "title" styling of other Alerts
- Toast layout updated to center-align flex contents; removed any absolute positioning
- `floating` buttons now correctly have their background set to "transparent"
- `s` sized buttons now have the correct padding
- `startIcon` now drops it's margin if the button has no other content
=> Toast Updates

packages/odyssey-react-mui/src/Link.tsx
This fixes a bug where a team was passing the ref, and it wasn't going through.
- Added back `forwardRef` to `Link`, but this time, it's wired up correct.
=> feat: added forwardRef to Link

packages/odyssey-react-mui/src/theme/components.tsx
FormHelperText component uses `text-align: left` by default, this makes the text incompatible with RTL languages. The purpose of this PR is to apply the logical counterpart to the left align CSS property. 
**Left aligned** using `text-align: start`:
**Right aligned** using `text-align: start`:
=> fix: textAlign logical value in FormHelperText for RTL support

packages/odyssey-react-mui/src/theme/components.tsx
Makes link a11y-compliant per @josesolano-okta's rec here: https://oktainc.atlassian.net/browse/OKTA-566351
More context on this request here: https://okta.slack.com/archives/C7T2H3KNJ/p1673453694499269
=> make Link a11y-compliant in all cases

packages/odyssey-react-mui/src/theme/components.tsx
Adds `boxShadow: "none"` safety for users in mixed-style environments.
=> fix(odyssey-react-mui): provide safety dec for input box-shadow

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
Better interface for icon-only buttons. Prior `children=""` support is left in place to prevent a breaking change.
=> fix(odyssey-react-mui): don't require children prop for Icon buttons

packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx
The `TextField` component was unintentionally missing the `onBlur` handler, and adopters started asking, so we added it in.
=> Add onBlur to TextField

packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.stories.tsx
removes inline link example from Infobox
=> docs(odyssey-storybook): remove inline link example from Infobox

packages/odyssey-react-mui/src/TextField.tsx
Previously, when the user toggled the `Eye` icon in a `TextField` of `type='password'`, the Eye would disappear.
It turns out the presence of the Eye was dependent on the `currentType` of the component, not the `type`. I swapped out that variable and now it works properly.
=> Prevent Eye from disappearing when the user makes a password visible

packages/odyssey-react-mui/src/Banner.tsx, packages/odyssey-react-mui/src/Infobox.tsx
`Banner` and `Infobox` messages are now prefixed with the variant type for screen readers only, to provide more context.
`Toast` needs this as well,  but we'll need to wrap it first.
=> Add screenreader context to Banner and Infobox

packages/odyssey-react-mui/src/theme/components.tsx
Focus was wonky on any element built on `InputBase`; this PR fixes the issues, as well as some issues with `Button` focus in Safari. Fixes include:
- Use `box-shadow` instead of `outline` for focus state, since Safari won't do rounded corners on `outline`s
- Add transparent outlines in some places so that high-contrast mode will still get a focus state
I spent way too long trying to figure out why Button wasn't receiving focus properly in Safari, and it turns out that Safari uses Opt-Tab instead of just Tab for focusing on things that aren't text inputs. Bonkers.
=> Fix Safari focus states

packages/odyssey-react-mui/src/theme/components.tsx
- fixes spacing for Hint/Error field helpers
- `CssBaseline` styling for `p` now only applies to classless elements
=> fix(odyssey-react-mui): fixes spacing for Hint/Error field helpers

packages/odyssey-react-mui/src/CircularProgress.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/CircularProgress/CircularProgress.stories.tsx
This PR wraps `CircularProgress`. The API is almost identical to MUI's version, but I removed the explicit `variant` prop. Previously, the user would specify `indeterminate` or `determinate`; the Odyssey version now assumes that any `CircularProgress` with a set value is determinate, otherwise it's indeterminate.
=> Wrapped CircularProgress

packages/odyssey-react-mui/src/Banner.tsx, packages/odyssey-react-mui/src/CheckboxGroup.tsx, packages/odyssey-react-mui/src/Infobox.tsx, packages/odyssey-react-mui/src/RadioGroup.tsx, packages/odyssey-react-mui/src/ScreenReaderText.tsx, packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/ScreenReaderText/ScreenReaderText.mdx, packages/odyssey-storybook/src/components/odyssey-mui/ScreenReaderText/ScreenReaderText.stories.tsx
Adds `ScreenReaderText` for visually hiding accessible content.
=> ScreenReaderText component

packages/odyssey-react-mui/src/Tag.tsx, packages/odyssey-react-mui/src/TagList.tsx, packages/odyssey-react-mui/src/TagListContext.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
This is a simple wrapper over `Chip` and `Stack` to add better ergonomics around tags and taglists.
I changed MUI's default `disabled` prop to `isDisabled` to be consistent with our other components.
=> Wrapped Tag and TagList

packages/odyssey-react-mui/src/theme/components.tsx
When `RadioGroup` was disabled, every `Radio` inside would be both disabled and selected. This was a pure CSS issue, nothing functional.
=> Fix broken Radio disabled states

packages/odyssey-react-mui/src/MenuButton.tsx
This adds an ID override to `MenuButton`, similar to our other inputs.
=> Add missing `id` override to MenuButton

packages/odyssey-react-mui/src/CheckboxGroup.tsx, packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/TextField.tsx
Repurpose `id` as `name` in form fields.
=> Add missing `name` prop to `TextField`

packages/odyssey-react-mui/src/Button.tsx
Per feedback from @KevinGhadyani-Okta, I've made two changes:
1. Update the type of `startIcon` and `endIcon` to accept `<Icon>`s instead of generic React components
2. Add `{...rest}` so that the Button can accept arbitrary props (useful for ARIA values), but omit any props that exist in `MuiButtonProps` but not `ButtonProps` to ensure nobody can use this to circumvent our intentions.
=> Update Button props and types

packages/odyssey-react-mui/src/Autocomplete.tsx
`Autocomplete` is missing the `onInput` prop required by other apps. This PR adds it.
=> fix: add missing onInput to Autocomplete

packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Link/Link.mdx, packages/odyssey-storybook/src/contributing/CustomTheme.mdx
Removes the MUI links in the documentation, since people were getting confused.
I left a single reference in the [Custom Theming ](https://odyssey.okta.design/?path=/docs/guidelines-custom-theming--page) page, since the intention of that page is specifically to point to MUI's `ThemeOptions` documentation for anyone taking a deep dive into how Odyssey works under-the-hood.
=> Remove MUI links in documentation

packages/odyssey-react-mui/src/Field.tsx, packages/odyssey-react-mui/src/FieldLabel.tsx, packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/PasswordField/PasswordField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx
This PR improves the optional/required handling on form fields. I made the following changes:
1. **`isRequired` is now `isOptional` on all form fields that include it**. This includes all types of `TextField`, as well as `PasswordField`. It does not include `SearchField`, since that component doesn't include `required`/`optional` functionality. I made this change throughout the stack for consistency (`Textfield` -> `Field` -> `FieldLabel`, etc)
2. **Updated the `lineHeight` on the optional label.** The line height was 1.14 pixels off, making the input "jump" by a pixel when the optionalLabel was visible. I updated it to the proper value to ensure that it remains positioned properly without bumping anything improperly.
=> Switch isRequired to isOptional

packages/odyssey-react-mui/src/theme/components.tsx
Removes `cursor` styling for disabled Buttons and returns `pointer-events` to default state.
=> fix(odyssey-react-mui): ensure pointer events are disabled

packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx
Fixes RadioGroup stories that were missing legends.
=> fix(odyssey-storybook): restore defaultValues for RadioGroup

packages/odyssey-react-mui/src/theme/components.tsx
Make sure every Radio in a RadioGroup isn't toggled when it has an error state.
=> Fix broken error state on RadioGroup

packages/odyssey-storybook/src/components/odyssey-mui/Infobox/Infobox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/SearchField/SearchField.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
Removed `Template.args` and put those back as `defaultValues` on `storybookMeta`.
This fixes a number of stories that were broken in a recent update.
=> fix(odyssey-storybook): stories were broken from incorrect template args

packages/odyssey-react-mui/src/Link.tsx, packages/odyssey-react-mui/src/theme/components.tsx
Fix: passes `variant` and `target` to `Link`
=> fix(odyssey-react-mui): pass variant and target props to Link

packages/odyssey-react-mui/src/TextField.tsx
`TextField` was always showing an input adornment. I've fixed it. This is was a recent regression.
=> fix(odyssey-react-mui): fixed TextField always showing input adronment

packages/odyssey-react-mui/src/MenuItem.tsx, packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/Toast.tsx
For components where the memoization was making it appear in code as `<MemoizedComponentName>`, add a displayName to ensure it gets output properly.
=> Add displayName to memoized components

packages/odyssey-react-labs/src/index.ts
`DatePicker` wasn't rendering correctly in Storybook. That's because our export from Labs was using MUI, not Labs. It's been fixed.
=> fix: exported DatePicker from Labs instead of MUI

packages/odyssey-react-mui/src/theme/components.tsx
=> fix(odyssey-react-mui): fix RTL placement of Select chevron

packages/odyssey-react-mui/src/Select.tsx
We had a lint error get merged. This PR fixes it.
=> fix: renderValue was missing a useCallback wrapper

packages/odyssey-react-mui/src/theme/components.tsx
Migrates CircularProgress to design tokens instead of MUI theme variables.
=> refactor(odyssey-react-mui): migrate Circular Progress to design tokens

packages/odyssey-react-mui/src/Link.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Link/Link.stories.tsx
The `Link` component was missing memoization and didn't have the correct `displayName` when used in Storybook.
That's now fixed.
=> fix: memoize the Link component

packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/index.ts, packages/odyssey-react-mui/src/theme/mixins.ts, packages/odyssey-react-mui/src/theme/palette.ts, packages/odyssey-react-mui/src/theme/shape.ts, packages/odyssey-react-mui/src/theme/spacing.ts, packages/odyssey-react-mui/src/theme/theme.ts, packages/odyssey-react-mui/src/theme/typography.ts, packages/odyssey-storybook/.storybook/manager.ts, packages/odyssey-storybook/.storybook/odysseyStorybookTheme.js
Our theme creation functions have the wrong design tokens type: `DesignTokensOverride` rather than the full `DesignTokens` requiring we setup null checks. We no longer need those.
=> fix: change to DesignTokens type rather than the overrides in theme

packages/odyssey-react-mui/src/Tooltip.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx
Make the Tooltip default to `placement` `top` to be consistent with our design.
=> refactor: make default Tooltip placement top

packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.stories.tsx
Variable default date was causing VRT to need an update every day
=> docs(odyssey-storybook): make datepicker starting date fixed

packages/odyssey-react-mui/src/theme/components.tsx
This PR makes the NativeSelect chevron behave the same as the Select chevron in RTL.
=> Fix RTL position of chevron in NativeSelect

packages/odyssey-react-mui/i18n.config.json
Summary: Remove default branch in i18n config
Reason: 
In this [PR](https://github.com/atko-eng/okta-ui/pull/6537), we are getting the default branch name from the output of command `git remote show origin`.
In odyssey, it will be "develop" (`HEAD branch: develop`). So we do not need to define the `defaultBranch` in config file.
=> Remove default branch in i18n config

packages/odyssey-design-tokens/src/border.json, packages/odyssey-react-mui/src/Fieldset.tsx, packages/odyssey-react-mui/src/Form.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/typography.ts, packages/odyssey-react-mui/src/theme/typography.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.stories.tsx
Updates `Form` and `Fieldset` to match designs.
- Adds `border.radius.tight` at `4px`
- Updates `border.radius.main` to `6px`
- Adds `subtitle2` variant for use in Forms, Fieldsets, and Dialogs
- Increases `legend` `font-size` and `line-height`
- Updates spacing across `Form` and `Fieldset`
- Updates `Form` "kitchen sink" to provide more coverage
=> Rebrand: Form & Fieldset

packages/odyssey-react-mui/src/theme/components.tsx
In certain cases, the `<Banner>` dismiss button could overlap the banner content. This PR applies some additional end padding on dismissable banners, ensuring the content avoids any awkward overlaps.
=> Prevent dismiss button from overlapping Banner text

packages/odyssey-react-mui/src/theme/components.tsx
The spacing on the tab icons assumed LTR reading order; this adjusts it to accommodate RTL too.
=> Update RTL spacing for tab icons

packages/odyssey-react-mui/src/ScreenReaderText.tsx
`ScreenReaderText` was rendering as a `<div>`, which is semantically incorrect inside of a `<p>`. Now it's a `<span>` and all is right with the world.
=> Fix div-inside-of-p issue in field errors

packages/odyssey-react-mui/src/theme/components.tsx
Refactors our styling to use MUI variables rather than strings for class names wherever possible. For example, `.${checkboxClasses.root}` rather than `".MuiCheckbox-root"`.
- As far as I can tell, global state classes like `.Mui-error` do not have a source of truth. Instead, each component declares `globalClasses` individually and does not seem to export them. 
- `Box` does not export its only class, `.MuiBox-root`
=> refactor(odyssey-react-mui): use component class name variables

packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-react-mui/src/NullElement.tsx, packages/odyssey-react-mui/src/index.ts
This PR creates a new `NullElement` type, and allows `MenuButton` to accept it as a child. This enables conditional rendering of children.
=> Allow MenuButton to accept null children

packages/odyssey-react-mui/src/Dialog.tsx
It previously accepted a `ReactNode` or an array of `ReactNode`s, but we only need the former.
=> Simplify Dialog children type

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
Icon-only `<Button>`s were adding too much horizontal padding unless the component was explicitly passed `text=""`. In other words: **If the button text was undefined, icon-only buttons looked bad.**
This is an issue we inherited from MUI, so the simplest fix is to simply default the `text` prop to an empty string if it's not explicitly defined.
=> Default Button text to empty string

packages/odyssey-react-mui/src/Form.tsx, packages/odyssey-react-mui/src/Infobox.tsx, packages/odyssey-react-mui/src/theme/typography.ts
Makes `Form` and `Infobox` spacing consistent regardless of children amount/types.
=> fix(odyssey-react-mui): make Form, Infobox spacing constent across uses

packages/odyssey-react-mui/src/OdysseyCacheProvider.tsx, packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx, packages/odyssey-react-mui/src/OdysseyTranslationProvider.tsx
`OdysseyCacheProvider` didn't allow passing custom StylisPlugins to Emotion.
In adding this, I went ahead and refactored the types for `OdysseyProvider`. 2 birds; 1 stone.
=> Add StylisPlugins to OdysseyCacheProvider

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
Add `type` prop to `Button`, which can be `button`, `submit`, or `reset`.
=> feat: add Button types

packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
For Supernova, we want to include a demo that shows all the variants of `<Button>` side-by-side. This provides a story which does that.
=> docs: add kitchen sink to Button

packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CheckboxGroup/CheckboxGroup.stories.tsx
1. Changes `Checkbox` `onChange` to make the component fully controlled. As part of this, `isChecked` has been replaced with `isDefaultChecked`, which matches the MUI standard.
2. Replaces `isValid` and `isInvalid` with a single `validity` prop.
=> Change Checkbox onChange and validity

packages/odyssey-design-tokens/src/typography.json, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/typography.ts
Renames `caption` to `subordinate` since the use is broader than a single element.
=> refactor: caption to subordinate

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
`<Button>` must now include either `text`, `startIcon`, or `endIcon` — it can't have none of those.
=> Require Button to have text, startIcon, or endIcon

packages/odyssey-react-mui/README.md, packages/odyssey-react-mui/src/Box.tsx, packages/odyssey-react-mui/src/Fieldset.tsx, packages/odyssey-react-mui/src/labs/README.md, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Box/Box.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Callout/Callout.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Toast/Toast.stories.tsx
- Fix `Fieldset` margin issue
- Add `id` prop to `<Box>`
- Move components out of `/Alerts` folder in Storybook
- Update READMEs
=> Launch day fixes

packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/scripts/properties-to-ts.js, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
Fix Odyssey exports in the older format. This reverts `type: module`.
=> fix: revert Odyssey bundle exports

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/theme/components.tsx
Fixes `autocomplete.option` padding and selected styles; now matches Select.
=> fix(odyssey-react-mui): make Autocomplete option styles match Select

packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx
Two changes here:
1. `MenuButton` icon now defaults to ChevronDown, not More
2. `MenuButton` gains a new `isOverflow` prop, which defaults the icon to `More` and not `ChevronDown`
=> Update MenuButton icon

packages/odyssey-react-mui/src/Select.tsx
Checkboxes in multi-select MenuItems weren't working properly; the quickest fix is to change the implementation to use MUI's default checkbox instead of our wrapped implementation.
=> Fix multi-select checkbox

packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/theme/components.tsx
Swaps out `Button` for `IconButton` within `SearchField` and `PasswordField`; now matches `Autocomplete`.
=> refactor(odyssey-react-mui): use IconButton within Form Fields

packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-react-mui/src/theme/components.tsx
`Typography` variants no longer have their `fontFamily` overridden by a default prop. `support` and `subordinate` now render as `p` instead of `h6`.
=> fix(odyssey-react-mui): ensure headings pick up TypographyFamilyHeading

packages/odyssey-react-mui/README.md, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/labs/README.md, yarn.lock
`@emotion/styled` and `@emotion/react` were in `devDependencies`. We need to move them to `dependencies` to make it easier to install Odyssey.
- [OKTA-639400](https://oktainc.atlassian.net/browse/OKTA-639400)
- [OKTA-641085](https://oktainc.atlassian.net/browse/OKTA-641085)
=> fix: moves @emotion/styled and @emotion/react to dependencies

packages/odyssey-storybook/applitools.config.js, packages/odyssey-storybook/applitools.xbrowser.config.js
Applitools was lacking branches. This PR adds branches to the Applitools config, so they'll function again now that GitHub integration with Applitools is no longer possible.
=> fix: adds branches back to Applitools

packages/odyssey-react-mui/src/theme/components.tsx
Reduces `paddingBlock` on `DialogActions` to `24px/Spacing5`.
=> refactor(odyssey-react-mui): tighten up DialogActions padding

packages/odyssey-react-mui/src/MenuButton.tsx
Makes `Button` sizes available to `MenuButton` as well.
=> feat(odyssey-react-mui): add `size` prop to MenuButton

packages/odyssey-react-mui/src/labs/PaginatedTable.tsx, packages/odyssey-react-mui/src/labs/StaticTable.tsx
`onGlobalFilterChange` should fire when string removed, but it was gating by falsey values rather than `undefined`.
=> fix: onGlobalFilterChange should fire when string removed

packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx
Replacement for #1946 to use `main` instead of `develop`.
=> refactor: switch Typography stories to use semantic aliases

packages/odyssey-react-mui/src/labs/StaticTable.tsx
`StaticTable` wouldn't work properly if the data amount changed after rendering. It either always needed virtualization or never needed it. It cannot be added after-the-fact based on the way the library works.
I've left it on always for now and can revisit exposing the option to consumers in the future with @jordankoschei-okta's new design changes.
=> fix: static tables to always have virtualization enabled

packages/odyssey-react-mui/src/@types/i18next.d.ts, packages/odyssey-react-mui/src/OdysseyTranslationProvider.test.tsx, packages/odyssey-react-mui/src/OdysseyTranslationProvider.tsx, packages/odyssey-react-mui/src/i18n.ts, packages/odyssey-react-mui/src/index.ts
[OKTA-649524](https://oktainc.atlassian.net/browse/OKTA-649524)
1. Rename `OdysseyI18n` to `i18n` to more closely detail what is being exported
2. Export the translate `t` function under the name `odysseyTranslate`
3. Refactor usage in `OdysseyTranslationProvider.test.tsx` to only use `odysseyTranslate`
4. Export `odysseyTranslate` so it can be used elsewhere
Needed to unblock [OKTA-646387](https://oktainc.atlassian.net/browse/OKTA-646387), where we want to compare the localized values in `PasswordField.stories.tsx`
I cherrypicked the commit on this branch onto the branch for [OKTA-646387](https://oktainc.atlassian.net/browse/OKTA-646387) and added a test using the `odysseyTranslate` export. It passed in localhost (image below shows it properly resolving to the value)
=> Adding i18n translate function as an export to odyssey-react-mui

packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx
[OKTA-653049](https://oktainc.atlassian.net/browse/OKTA-653049)
We need to remove `classes` from Typography components. It should've never been in Odyssey in the first place. Only `Box` has `sx`, and that's it.
N/A
=> fix: removed classes prop from Typography components

packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-storybook/src/components/odyssey-mui/PasswordField/PasswordField.stories.tsx
[OKTA-646382](https://oktainc.atlassian.net/browse/OKTA-646382)
1. As per a request from the sign-in-widget team, we have added a prop `hasPasswordIcon` which is default true, but can be overloaded to `false`. When it is `false`, there is no show password eye icon in the `PasswordField`.
2. Added a new StoryObj `NoShowPassword` where `hasPasswordIcon` is set to `false`
=> Add disabling of show/hide icon feature in PasswordField

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx
[OKTA-649454](https://oktainc.atlassian.net/browse/OKTA-649454)
1. Added `errorMessage` prop and Storybook object with example
2. Added `isOptional` prop to Storybook (was there before but not in stories)
3. Added `onBlur` and `onFocus` props
4. Added `id` and `name` props
errorMessage
isOptional
onBlur/onFocus
https://github.com/okta/odyssey/assets/109781221/cf8cbbdc-a453-4d09-bf0b-9212a55a6a29
id/name
https://github.com/okta/odyssey/assets/109781221/897b8943-1290-4159-9d75-d5a8bd9f8eb6
=> OKTA-649454: Add missing prop errorMessage to autocomplete

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-653386](https://oktainc.atlassian.net/browse/OKTA-653386)
Changed the background color of the default lamp Status from `transparent` to `gray` using design tokens. The pill variant was already correct.
[Odyssey design shows that the correct background color is gray](https://odyssey.okta.design/latest/components/status/design-rRsXKZjT#section-severity-4d)
Before:
After:
=> OKTA-653386: gray color in default Status lamp variant

packages/odyssey-storybook/applitools.config.js
https://oktainc.atlassian.net/browse/OKTA-651614
Applitools had too high of a concurrency for our plan. This has been taken down to only 10 threads to reduce the workload.
N/A
=> fix: concurrency in Applitools being too high

README.md, packages/odyssey-react-mui/src/MenuButton.tsx, packages/odyssey-react-mui/src/MenuItem.tsx, packages/odyssey-storybook/src/components/odyssey-mui/MenuButton/MenuButton.stories.tsx
[OKTA-636204](https://oktainc.atlassian.net/browse/OKTA-636204)
Menu Button didn't accept `null` as a value for conditional items.
@chrispulsinelli-okta did all the code. I just moved it to a new branch.
Previous PR: https://github.com/okta/odyssey/pull/1934
N/A
=> fix: menu button not allowing falsey children

packages/odyssey-react-mui/src/Tabs.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx
[OKTA-651827](https://oktainc.atlassian.net/browse/OKTA-651827)
This allows an `onChange` prop to the `Tabs` component, to allow control, which gets called if it's defined, when the selected tab changes.
=> OKTA-651827: make tabs controlled

packages/odyssey-react-mui/src/Callout.tsx
OKTA-653209
I removed the hardcoded ":" in from ScreenReaderText element in `Callout` that was non-compliant with our translated strings approach. The change is only noticeable in the source code and to screen readers as they read label value of an icon in a `Callout`  
I tested the output before and after via screen reader and there is no difference in what is voiced. The text output in english changes from "info:, <callout message text>" to "info, <callout message text>" so I don't believe we'll need to adjust the translated values.
=> fix: remove ":" from ScreenReaderText in Callout

packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tooltip/Tooltip.stories.tsx
Wrapped the Typography component with context so that other components, like Tooltip, can create a `ref` to it and wrap it.
[OKTA-658896](https://oktainc.atlassian.net/browse/OKTA-658896)
=> feat(odyssey-react-mui): wrapped typography component with context

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
[OKTA-642069](https://oktainc.atlassian.net/browse/OKTA-642069)
Thanks to @bryancunningham-okta for doing the initial discovery!
1. Fixes the type for `onChange` and everything else related to the value in `Select.
1. Deprecates `isMultiSelect` in favor of the new `hasMultipleChoices` (the same name we use on Autocomplete).
N/A
=> Fix Select `onChange` type being `unknown`

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-663471](https://oktainc.atlassian.net/browse/OKTA-663471)
- Remove `text-decoration: underline` on non-hovered default link style
- Remove some spacing between link text and icon
=> Small style fixes to Link component

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-664290](https://oktainc.atlassian.net/browse/OKTA-664290)
- Update disabled `MuiChip-label` color to be more readable
=> Fix chip label color inside disabled input

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-658452](https://oktainc.atlassian.net/browse/OKTA-658452)
Visual updates to match the [Figma component](https://www.figma.com/file/zh7A9gjaDlI50Hctdvd1OB/Odyssey-Components?type=design&node-id=83-485)
* Left and right padding added (`4px`) to `Tab` label 
* `font-size` updated from ~`13px` (`body`) to ~`16px` (`heading 6`)
* `font-weight` changed from `600` (`bodyBold`) to `500` (`heading`)
* default `color` changed from `inherit` to `Neutral 600`
- [ x] I have confirmed this change with my designer and the Odyssey Design Team.
=> fix(odyssey-react-mui): update Tab styles to match Figma

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/labs/VirtualizedAutocomplete.tsx, packages/odyssey-react-mui/src/labs/index.ts, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx
[okta-665431](https://oktainc.atlassian.net/browse/okta-665431)
Improvements:
- Add ability to have Autocomplete work in a controlled / uncontrolled manner 
- Allow for user to provide `isOptionEqualToValue` predicate to test that option matches value when options are objects
- Allow user to provide default values (required for uncontrolled component scenario)
- Add controlled state object to drive internal state of autocomplete
- Add more stories to cover the controlled and uncontrolled scenarios
Fixes:
- Fix typing for `options` prop
- Fix typing for `value` prop
- Reflect `onChange` back to parent component
=> fix autocomplete issues

packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx
[OKTA-670762](https://oktainc.atlassian.net/browse/OKTA-670762)
**NOTE:** hint has been supported in TextField already, not code change is required.
Supports hint for Checkbox and TextField
=> feat: add hint prop to Checkbox

README.md, packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/Radio.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Checkbox/Checkbox.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx
[OKTA-670768](https://oktainc.atlassian.net/browse/OKTA-670768)
Adds onBlur prop to Radio and Checkbox component
onBlur event is captured in storybook
=> feat: add on blur for radio and checkbox OKTA-670768

packages/odyssey-react-mui/src/OdysseyCacheProvider.tsx, packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx, packages/odyssey-react-mui/src/createShadowRootElement.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/createOdysseyMuiTheme.ts, packages/odyssey-storybook/.storybook/components/MuiThemeDecorator.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.stories.tsx, packages/odyssey-storybook/src/contributing/CustomTheme.stories.tsx, packages/odyssey-storybook/src/installation/ShadowDom.mdx
- Change shadow root element type from `HTMLDivElement` to `HTMLElement` to avoid need to cast
- Fixed broken shadow dom themed tests
- Updated tests to show how to use `OdysseyProvider`
[OKTA-670823](https://oktainc.atlassian.net/browse/OKTA-670823)
=> fix: fixed typing for shadow root element. updated tests to reflect changes

.github/NEW_COMPONENT_PULL_REQUEST_TEMPLATE.md
Adds Github commit template for new component contributions.
[OKTA-672078](https://oktainc.atlassian.net/browse/OKTA-672078)
https://oktainc.atlassian.net/browse/OKTA-672078
Creating a new template that we can use for new component contributions. The template includes the Developer checklist from the Odyssey Component Workflow project. The workflow for using this component will be integrated separately after this template is merged.
=> feat: commit template for new component contributions

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/CheckboxGroup.tsx, packages/odyssey-react-mui/src/Field.tsx, packages/odyssey-react-mui/src/FieldComponentProps.ts, packages/odyssey-react-mui/src/FieldHint.tsx, packages/odyssey-react-mui/src/HintLink.tsx, packages/odyssey-react-mui/src/NativeSelect.tsx, packages/odyssey-react-mui/src/RadioGroup.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/labs/DataTable.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/LegacyTable/PaginatedTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/CheckboxGroup/CheckboxGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/NativeSelect/NativeSelect.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/TextField/TextField.stories.tsx, packages/odyssey-storybook/src/fieldComponentPropsMetaData.ts
This is a replacement PR for #2041
The previous PR was failing CI in VRT testing for unknown reasons
[OKTA-665365](https://oktainc.atlassian.net/browse/OKTA-665365)
=> Allow Link component to be rendered after hint text

packages/odyssey-react-mui/src/Breadcrumbs.tsx, packages/odyssey-react-mui/src/theme/components.tsx
Modify the Breadcrumb styles to match Figma, as close to pixel-perfect as we can get in the browser.
=> Update Breadcrumb styles to match Figma

packages/odyssey-react-mui/README.md
[OKTA-678659](https://oktainc.atlassian.net/browse/OKTA-678659)
- Fix error in README file instructing users to download 'Public Sans'. Swapped to include correct request of 'Inter' fonts
=> Fix error in README file instructing users to download 'Public Sans'. Swapped to include correct request of 'Inter' fonts

packages/odyssey-react-mui/src/OdysseyTranslationProvider.tsx
[OKTA-678132](https://oktainc.atlassian.net/browse/OKTA-678132)
- #2058 added support for languages other than the Okta-specified ones, which unblocked the SIW team's need to support customer-hosted language files for non-Okta-specified languages (Bring Your Own Language feature) after migrating to Odyssey 1.x
- However, in order to maintain the same API/functionality, the SIW needs to have access to a _list_ of translation keys rather than just the `OdysseyI18nResourceKeys` _type_ that is currently exported. This is because the SIW must be able to detect and select any overridden Odyssey-specific keys (e.g. `fieldlabel.optional.text`) from its own translation bundle in order to create an appropriately-typed object to pass into the translation provider's`translationOverrides`
=> Export translation keys as list from OdysseyTranslationProvider

packages/odyssey-react-mui/src/Badge.tsx, packages/odyssey-react-mui/src/Tabs.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/LegacyTable/PaginatedTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tabs/Tabs.stories.tsx
[OKTA-668233](https://oktainc.atlassian.net/browse/OKTA-668233)
- Adds ability to render a `Badge` in a `Tab`
https://www.figma.com/file/zh7A9gjaDlI50Hctdvd1OB/branch/tRCCNYz7ZyNP6a0pSAMlf5/Odyssey-Components?type=design&node-id=16959%3A924&mode=design&t=K2b79s64TbwcxZKF-1
=> Add ability to render a Badge inside a Tab

.github/workflows/ci.yml, packages/odyssey-storybook/applitools.config.js
[OKTA-683702](https://oktainc.atlassian.net/browse/OKTA-683702)
I moved the Applitools URL to the config because I was having issues with GitHub Secrets. This fixes the issue today, and we can address GitHub Secrets in the future or just not use that method altogether.
=> fix: moves Applitools server URL to in-repo config rather than GitHub Secrets

packages/odyssey-react-mui/src/TextField.tsx
Supports the `inputmode` prop in the `TextField` component so virtual keyboards can show the appropriate keyboard depending on what type of input data is being entered
=> feat: support inputmode prop in TextField

packages/odyssey-storybook/.storybook/components/MuiThemeDecorator.tsx
In the Storybook component docs, stories are clipping strangely. This is particularly visible in places where the component should overflow the story, such as the Select dropdown or the Dialog backdrop.
This issue was introduced with our recent Shadow DOM updates. To fix it, I've removed the shadow DOM element from the OdysseyProvider _in Storybook only_, which eliminates the issue. As far as I can tell, there are no unintended consequences, since we don't really need to reduce the scope of our CSS in Storybook.
=> Fix broken Storybook story height

packages/odyssey-react-mui/src/Accordion.tsx
- Adds support of `id` prop for `Accordion`. If `id` is not passed, it will be auto generated using hook `useUniqueId`.
- `MuiAccordionSummary` will always have `id` and [`aria-controls`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls) props required for accessibility (see [Accessibility for Accordion](https://mui.com/material-ui/react-accordion/#accessibility)).
Thus in resulted HML an accordion header would have `id` attribute with value `${accordionId}-header` and `aria-controls` attribute with value `${accordionId}-content` and an accordion content would have `id` attribute with value `${accordionId}-content`.
(Changes are needed for SIW migration to Odyssey 1.x, task [OKTA-678802](https://oktainc.atlassian.net/browse/OKTA-678802))
=> feat: Support id for Accordion

packages/odyssey-react-mui/src/PasswordField.tsx
- `PasswordField` should have `aria-controls` and `aria-pressed` on the toggle password icon button
=> feat: support aria-controls and aria-pressed in PasswordField

packages/odyssey-react-mui/src/@types/react-augment.d.ts, packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/Link.tsx, packages/odyssey-react-mui/src/NativeSelect.tsx, packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/Radio.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-react-mui/src/inputUtils.ts, packages/odyssey-react-mui/src/labs/Switch.tsx, packages/odyssey-react-mui/src/labs/VirtualizedAutocomplete.tsx
- Existing implementation of `testId` had placed it on the wrapper MUI element for all MUI components that wrap an underlying raw HTML `input` element (e.g. `TextField`, `Checkbox`, `Radio`, etc.). Most downstream repos have written their unit and e2e tests expecting that the `data-se` attribute is on the raw HTML `input` element rather than a wrapper parent element, so this PR moves `data-se` to MUI's `inputProps`
- Required module augmentation of React's `HTMLAttributes` to allow `data-*` attributes because of an underlying issue with TypeScript
- Moved `FocusHandle` out of declaration file because it fits better in `inputUtils.ts`
- Fixes missing input focus ref and autocomplete props from `NativeSelect`
=> fix: move testId to inputProps for all input components

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/CheckboxGroup.tsx, packages/odyssey-react-mui/src/Field.tsx, packages/odyssey-react-mui/src/FieldComponentProps.ts, packages/odyssey-react-mui/src/NativeSelect.tsx, packages/odyssey-react-mui/src/PasswordField.tsx, packages/odyssey-react-mui/src/RadioGroup.tsx, packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/TextField.tsx, packages/odyssey-react-mui/src/labs/VirtualizedAutocomplete.tsx
- Supports passing in an `ariaDescribedBy` prop to any `Field` components and joins that value with other relevant describedby values within `Field`
=> feat: support aria-describedby as prop for Field components

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/useNormalizedKey.ts, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
[OKTA-690467](https://oktainc.atlassian.net/browse/OKTA-690467)
Allow users to pass in an empty string for `value` prop if an option item has an empty `value` property. Allows an option with an empty string for `value` to be selected.
=> fix: allow empty string value for option value and value prop

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-691345](https://oktainc.atlassian.net/browse/OKTA-691345)
Changes spacing between hint text and checkbox label from 8px to 4px (Spacing 2 > Spacing 1) to match design conventions.
Note: Figma change for this bug has already merged (as of 2/1/24 @ 1:20 PT).
- [ x] I have confirmed this change with my designer and the Odyssey Design Team.
=> fix: change spacing on checkbox label and hint

packages/odyssey-react-mui/src/Select.tsx
[OKTA-688591](https://oktainc.atlassian.net/browse/OKTA-688591)
- Fix inconsistency with showing the check on a selected item in the menu
=> show check in both cases

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/MenuButton.tsx
[OKTA-691021](https://oktainc.atlassian.net/browse/OKTA-691021)
- Allow aria attrs from `MenuButton` to be passed through to `Button`
=> Pass correct aria attrs from menu button

packages/odyssey-react-mui/src/Form.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Form/Form.stories.tsx
[OKTA-691121](https://oktainc.atlassian.net/browse/OKTA-691121)
[OKTA-692737](https://oktainc.atlassian.net/browse/OKTA-692737)
- Moves the actions container to flex-end to align with Odyssey decision on placement of actions
=> Move primary actions in Form to end

.github/workflows/ci.yml, packages/odyssey-storybook/src/components/odyssey-labs/Switch/Switch.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Autocomplete/Autocomplete.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Banner/Banner.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.stories.tsx
[OKTA-699489](https://oktainc.atlassian.net/browse/OKTA-699489)
Fixes the `a11y` tests and sets up chromium for playwright to use to run the tests against. 
Test fixes:
- The main fix was to `await` async functions we were calling, as well as steps
- Turn non-async callbacks into async ones where we need to await anything within them
Playwright fixes:
- It appears that after the upgrades we made to the monorepo, `playwright` doesn't have a chromium binary to use to run the tests against
- [Add a step](https://playwright.dev/docs/ci-intro#on-pushpull_request:~:text=Install%20Playwright%20Browsers-,run%3A%20npx%20playwright%20install%20%2D%2Dwith%2Ddeps,-%2D%20name%3A) before we launch the `a11y` tests to [install `chromium` and any OS …
=> test: fixed test issues from playwright upgrade

packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/theme/components.tsx
=> Improve Select and SearchField, take 2

packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-storybook/src/components/odyssey-mui/SearchField/SearchField.stories.tsx
[OKTA-704203](https://oktainc.atlassian.net/browse/OKTA-704203)
- Fix bug where clear icon is not shown when a controlled value is passed in
=> Show clear icon when value is provided

packages/odyssey-react-mui/src/DataTable/DataTableEmptyState.tsx, packages/odyssey-react-mui/src/DataTable/DataTablePagination.tsx, packages/odyssey-react-mui/src/DataTable/DataTableRowActions.tsx, packages/odyssey-react-mui/src/DataTable/DataTableSettings.tsx, packages/odyssey-react-mui/src/labs/StaticTable.tsx
StaticTable and other table components needed a displayName.
=> Add displayName to table components

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/.storybook/components/MuiThemeDecorator.tsx
…om autocomplete
[OKTA-705987](https://oktainc.atlassian.net/browse/OKTA-705987)
- Passes `isFullWidth` prop from `AutoComplete` to `Field`
- Fixes regression on inputs height
=> revert height change. pass full width prop

packages/odyssey-react-mui/src/theme/components.tsx
During the MUI upgrade, the `MuiInputBase` shifted how it calculates height. Previously it used `box-sizing: content-box`; now it uses `box-sizing: border-box`.
This change was entirely on MUI's end, but causes us to need to change how we calculate input heights. Thanks to our token system, this is as easy as changing from `Spacing4` to `Spacing7`.
=> Fix wonky input height

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/theme/components.tsx
There was some unintended text clipping in `NativeSelect` that turned out to be related to the change in how the input heights were calculated. This PR addresses that issue, along with a few related issues that cropped up during the fix:
1. Input height is now implicit. The border-width compensation is now handled by the padding, not the height.
2. Select, NativeSelect, and InputBase are all using the same height measurement
3. The multi-select chips now play nicely with the new height.
=> Fix height for TextField, Select, and NativeSelect

packages/odyssey-react-mui/src/Checkbox.tsx, packages/odyssey-react-mui/src/theme/components.tsx
The checkbox label was misaligned by a few pixels when the `(Required)` span was appended to the label.
Two things needed to change to fix this:
1. The non-`(Required)` portion of the label needed to be wrapped in a `span`. There were some style differences between the Required and the rest of the label due to the fact that one was wrapped in a Typography component and the other wasn't.
2. Removed a `marginBlockStart: 0` that nixed an older alignment fix to make the checkbox positioning match the label line-height
=> Fix checkbox alignment issue

packages/odyssey-react-mui/src/Callout.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Callout/Callout.stories.tsx
[DES-5074](https://oktainc.atlassian.net/browse/DES-5074)
[OKTA-708136](https://oktainc.atlassian.net/browse/OKTA-708136)
* This PR updates Storybook documentation for Callout to correctly show that `children` is supported
* Also adds an example in Storybook showing how to add a list
* Matching Supernova and Figma example updates are ready to go pending approval of this PR.
* [Figma do/don't ](https://www.figma.com/file/FwOHteDCOQHgvtMOU6LrZT/Supernova-graphics-and-templates?type=design&node-id=2477-41071&mode=design&t=42D3r4rvhHIDkylu-4)to be added to Supernova when this PR merges
Note: I closed the [previous PR ](https://github.com/okta/odyssey/pull/2171) because of issues with the branch history breaking the build unrelated to this change.
=> fix: add official support for lists in Callout [OKTA-708136] (take 2)

packages/odyssey-react-mui/src/DataTable/DataTable.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.stories.tsx
Fixes a few missing dependencies in `useCallback` and `useMemo`, and replaces `.push()` with `.concat()` as per Kevin's suggestion.
=> Fix missing callback dependencies

packages/odyssey-react-mui/src/Breadcrumbs.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Breadcrumbs/Breadcrumbs.stories.tsx
Long titles in `<Breadcrumbs>` looked unwieldy; this PR truncates them automatically at 10rem (a reasonable length). We're using a wrapping element to do this so that the overflow styles don't interfere with the icons or other existing layout.
=> Truncate long breadcrumbs

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/theme/components.tsx
This is a dupe of a previous [PR](https://github.com/okta/odyssey/pull/2168) from @chrispulsinelli-okta 
The previous branch was in a wonky state due to VRT changes happening after the branch was cut. Moving to new branch/PR to ensure VRT is catching any regressions correctly
-Fixes autocomplete loading state so it is visually consistent with lists of options.
- Fixed height issue for all dropdowns (loading, list, virtualized list).
=> Fix autocomplete style issues

packages/odyssey-react-mui/src/Select.tsx
In the `Select` component, if an option had defined text but an empty value, the text wouldn't display when the option was selected.
For example, in a Select with this option:
```
{
text: "Nothing here",
value: ""
}
```
if that option were selected, the `Select` would _**not**_ show "Nothing here" as the text... the text would simply be empty.
It turns out this was due to a MUI option being set to `false`. I changed it to `true` and now it works.
=> Display empty values in Select

packages/odyssey-react-mui/src/Button.tsx
fixes bad setState call inside MUI
[OKTA-716418](https://oktainc.atlassian.net/browse/OKTA-716418)
- Chang how MUI's tooltip ref is assigned to fix bad setState warning.
=> Change how mui tooltip ref is assigned

.github/workflows/ci.yml, .github/workflows/warm-cache.yml, .github/workflows/x-browser-vrt.yml
Bumping the version of actions/checkout used here, reference https://github.com/actions/checkout?tab=readme-ov-file#checkout-v4
This will address (part of) the deprecation notices, screenshot from https://github.com/okta/odyssey/actions/runs/8787433325
=> Bump actions/checkout to v4 in GitHub Actions workflows

packages/odyssey-react-mui/src/Radio.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Radio/Radio.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx
[OKTA-722356](https://oktainc.atlassian.net/browse/OKTA-722356)
Adds hint text to `Radio` and `RadioGroup` (storybook). This implementation mirrors our `hint` implementation in `Checkbox`.
I am also updated this in Figma and working with Gretchen on copy updates that will be synced when this merges.
=> Add hint text to Radio and RadioGroup

packages/odyssey-react-mui/src/Dialog.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Dialog/Dialog.stories.tsx
[OKTA-728883](https://oktainc.atlassian.net/browse/OKTA-728883)
Resolves breaking change by adding support back in for 
` callToActionFirstComponent,
callToActionSecondComponent,
callToActionLastComponent`
Changes also include a deprecation warning for these props in favor of ` primaryCallToActionComponent,
secondaryCallToActionComponent,
tertiaryCallToActionComponent,`
=> fix: re-add support for "callToAction" button usage

packages/odyssey-storybook/src/components/odyssey-mui/SearchField/SearchField.stories.tsx
[DES-5625](https://oktainc.atlassian.net/browse/DES-5625)
This PR exposes the existing "outline" (gray) variant in the `Search` component. It was likely not exposed previously because it is used for very specific things, but with the upcoming layout updates we will need to offer this to engineers.
=> fix: expose "filled" variant of search

packages/odyssey-storybook/src/components/odyssey-mui/Accordion/Accordion.stories.tsx
[DES-5590](https://oktainc.atlassian.net/browse/DES-5590)
Very minor fix to update example text in `Accordion` storybook to change "Title" to "Label" to align with actual prop name.
=> Update storybook to show Label not Title

packages/odyssey-react-mui/src/Button.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/components.types.ts, packages/odyssey-storybook/src/components/odyssey-mui/Button/Button.stories.tsx
[OKTA-729832](https://oktainc.atlassian.net/browse/OKTA-729832)
-  Adds `href` prop to `Button` to enable consumers to optionally render `Button` as a link
-  Adds new `floatingAction` variant (existing floating button style but with blue text)
- `href` can be applied to any button style that needs to be rendered as a link (i.e., takes a user to a new URL)
- `href` and `onClick` can _technically_ both be passed into `Button` at the same time. If this happens, the element renders as and behaves like a link. I went back and forth on whether to show a warning but concluded there may be valid use cases like if the onClick was used for additional functionality, like link tracking.
- There isn't currently a `target` prop because I didn't want to add more stuff to the API not knowing if people …
=> Add href prop and "Floating Action" variant to button

packages/odyssey-storybook/src/guidelines/Roadmap/RoadmapTable.tsx, packages/odyssey-storybook/src/guidelines/Roadmap/roadmap.json, packages/odyssey-storybook/src/guidelines/Roadmap/roadmapData.tsx
**Notes:** I closed the [last PR](https://github.com/okta/odyssey/pull/2242) because I did not have my GPG set up to verify commits and it got messy. [the original PR](https://github.com/okta/odyssey/pull/2230) was unintentionally closed and re-opening caused CI issues. [See the previous PR](https://github.com/okta/odyssey/pull/2230) for past comments.
[DES-5467](https://oktainc.atlassian.net/browse/DES-5467)
Updates existing [Roadmap page](https://odyssey-storybook.okta.design/?path=/docs/welcome-roadmap--docs) in Storybook with new data structure, statuses with tooltips, filters, and easier method for updating data via separate JSON file.
=> Storybook Roadmap page update (take 4)

packages/odyssey-react-mui/src/Dialog.tsx
[OKTA-735371](https://oktainc.atlassian.net/browse/OKTA-735371)
For legacy action usage, missing keys were causing errors and breaking the dialog
[Context from Slack](https://okta.slack.com/archives/C7T2H3KNJ/p1717437120893959)
=> Dialog action button missing keys issue [OKTA-735371]

packages/odyssey-react-mui/src/Status.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Status/Status.stories.tsx
**NOTE:** This take 2 after messing up the history of [my original PR](https://github.com/okta/odyssey/pull/2224) fixing commit signing issues. Please refer to the original PR for comments
[DES-5591](https://oktainc.atlassian.net/browse/DES-5591)
Adds the previously deprecated `Status` `lamp` variant. This was [removed recently ](https://github.com/okta/odyssey/commit/cd68bfc7f5abc4843495419e3d94812fba969eb5)to simplify the style of `Status` but we've since found use cases for `lamp` and numerous existing uses that necessitate the style.
=> Add status lamp [DES-5591] (pr2)

packages/odyssey-react-mui/src/Card.tsx, packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Card/Card.mdx, packages/odyssey-storybook/src/components/odyssey-mui/Card/Card.stories.tsx
[DES-5647](https://oktainc.atlassian.net/browse/DES-5647)
Renames `Tile` to `Card` to align with design + storybook changes.
Also adds support for importing the component as `Tile` along with a `@deprecated` annotation and console warning
=> Rename "Tile" to "Card"

packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/labs/useDatePickerTranslations.ts, packages/odyssey-react-mui/src/properties/odyssey-react-mui.properties
[OKTA-732108](https://oktainc.atlassian.net/browse/OKTA-732108)
[OKTA-700110](https://oktainc.atlassian.net/browse/OKTA-700110)
- Fixes some non-translated text in Autocomplete
- Allows consumer to customize the empty state text
=> Allow noOptionsText and translate clear text

packages/odyssey-react-mui/src/DataTable/DataTable.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.stories.tsx
=> feat: add initial search prop to DataTable

packages/odyssey-react-mui/src/theme/components.tsx
By Alex's request, this PR removes the little circle from the left side of status pills, to match Figma.
=> Remove vestigial lamp from status pills

packages/odyssey-react-mui/src/labs/NavAccordion.tsx, packages/odyssey-react-mui/src/labs/SideNav.tsx, packages/odyssey-react-mui/src/labs/index.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
[732684](https://oktainc.atlassian.net/browse/732684)
1. [Figma link if applicable.](https://www.figma.com/design/zh7A9gjaDlI50Hctdvd1OB/Odyssey-Components?node-id=23268-78774&t=YSH3CgBAi69KFlpL-0)
2. 
https://github.com/okta/odyssey/assets/40774045/b4468682-fab9-4293-88c8-982bc495c640
=> feat: adds new side navigation component for unified nav design

packages/odyssey-react-mui/src/DataTable/DataTable.tsx, packages/odyssey-react-mui/src/Pagination/Pagination.tsx, packages/odyssey-react-mui/src/Pagination/usePagination.ts, packages/odyssey-react-mui/src/labs/DataComponents/DataStack.tsx, packages/odyssey-react-mui/src/labs/DataComponents/DataTable.tsx, packages/odyssey-react-mui/src/labs/DataComponents/DataView.tsx, packages/odyssey-react-mui/src/labs/DataComponents/componentTypes.ts, packages/odyssey-storybook/src/components/odyssey-labs/DataComponents/DataComponents.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Pagination/Pagination.stories.tsx
In response to some feedback from @alexma-okta, this PR fixes three bits of missing functionality or unanticipated behavior:
Previously, it was possible for a user to specify nonsensical or invalid pagination values, like trying to show 9999 rows per page on a dataset that only includes 100 rows, or navigating to page 100000 when there are only 20 pages.
Now, you can manually set maximum allowed values for row count and page.
Previously, if you were on page 20 (for example) and you started searching for something in a table, the pagination would continue to show that you were on page 20 even as the data changed.
Now, the pagination resets to the proper values when searching or filtering.
There are cases in which we don't know the total row count due to API limitations. Now, a consumer can …
=> Data Table legacy improvements

packages/odyssey-react-mui/src/theme/components.tsx
[OKTA-755668](https://oktainc.atlassian.net/browse/OKTA-755668)
`-moz-search-cancel-button` is not a valid pseudo-element, unlike [-webkit-search-cancel-button](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button), but they are both treated equal in the [Odyssey theme overrides](https://github.com/okta/odyssey/blob/main/packages/odyssey-react-mui/src/theme/components.tsx#L1936-L1939), which should be removed.
Error example:
=> fix: remove invalid pseudo element from theme overrides

.bacon.yml, packages/odyssey-storybook/.storybook/main.ts, packages/odyssey-storybook/applitools.config.js
[OKTA-756835](https://oktainc.atlassian.net/browse/OKTA-756835)
Applitools is having inconsistent runs since moving to Bacon. This PR adds a 2 second delay which should fix our consistently issues.
I removed any hint of GITHUB env vars and even fixed a bug where `main` wasn't used for the branch name if no PR existed when running Bacon.
Lastly, stopped one failed test from aborting others in Bacon.
This worked in my testing on Bacon both locally and on this branch. Without making new branches, it's hard to test, but others have reported it fixing these issues for them as well.
=> fix: Applitools isn't consistently running VRTs

scripts/publish-packages.sh
[OKTA-737450](https://oktainc.atlassian.net/browse/OKTA-737450)
Our Storybook topic deploy is missing the hash other packages have. This PR adds it as another hashed package.
Passing Bacon CI is the test as this is a Bacon task. I verified by looking at Artifactory for the package.
=> build: adds Git hash to Storybook package

packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/src/Autocomplete.tsx, packages/odyssey-react-mui/src/theme/components.tsx, yarn.lock
[OKTA-793324](https://oktainc.atlassian.net/browse/OKTA-793324)
- Fix bug where listbox was too long in some cases
- Allow dynamic height autocomplete items
=> Fix virtual autocomplete height

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Select/Select.stories.tsx
[OKTA-795183](https://oktainc.atlassian.net/browse/OKTA-795183)
Previously: 
Now:
=> fix: select multioption not rendering text when you use an options object 

packages/odyssey-react-mui/src/DataTable/DataTable.tsx, packages/odyssey-react-mui/src/labs/DataView/DataTable.tsx, packages/odyssey-react-mui/src/labs/DataView/DataView.tsx, packages/odyssey-react-mui/src/labs/DataView/componentTypes.ts, packages/odyssey-storybook/src/components/odyssey-labs/DataTable/DataTable.stories.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DataView/DataView.mdx, packages/odyssey-storybook/src/components/odyssey-labs/DataView/DataView.stories.tsx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.mdx, packages/odyssey-storybook/src/components/odyssey-mui/DataTable/DataTable.stories.tsx
By popular request (and to achieve parity with that first version of DataTable), this resurrects a feature that was lost as a regression.
Both DataView and DataTable now offer props for additionalActionButton and additionalActionMenuItems, which render arbitrary action button or menu items into the top of the component. This is intended for functionality like an "Add row" action or similar that should live on the table itself, not at the page-level.
=> feat: add additional action button and menu slot to table

packages/odyssey-react-mui/src/OdysseyCacheProvider.tsx, packages/odyssey-react-mui/src/OdysseyProvider.tsx, packages/odyssey-react-mui/src/OdysseyThemeProvider.tsx, packages/odyssey-react-mui/src/createShadowDomElements.ts, packages/odyssey-react-mui/src/index.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/createOdysseyMuiTheme.ts, packages/odyssey-storybook/src/installation/ShadowDom.mdx
[OKTA-798986](https://oktainc.atlassian.net/browse/OKTA-798986)
**Nothing is breaking.** All breaking changes were marked `@deprecated`.
Our Shadow DOM code nomenclature didn't make that much sense and wasn't consistent. Also, the return value was a tuple rather than an object with named props. I've updated it to be consistent throughout Odyssey including the documentation (which didn't match either).
We also had the issue of `<style>` tags from Emotion rendering into a global `<style>` tag. This should've been a `div` instead.
=> feat: adds new Shadow DOM export with better naming

packages/odyssey-react-mui/src/labs/DateField.tsx, packages/odyssey-react-mui/src/labs/DatePicker.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DatePicker/DatePicker.stories.tsx
[OKTA-804459](https://oktainc.atlassian.net/browse/OKTA-804459)
- Adds some missing props to Storybook
=> fix: Add missing props to Storybook

packages/odyssey-react-mui/src/DataTable/useScrollIndication.tsx
The fix in #2331 missed one crucial thing — we need to account for the table containers 2px of transparent borders. This PR addresses that, ensuring that if we make the inner width match the outer width, we don't accidentally push the outer width wider and wider until it expands beyond the bounds of the known universe.
From #2331:
https://github.com/user-attachments/assets/2cf1a4b6-4cbf-4419-b60d-c8fef2bda4cb
> The problem: Due to how the scroll overflow works, we use JS to detect the size of the table's wrapper div and then pass that size to the table itself. This works fine most of the time, but when its container doesn't have a set width, it can get into a weird state where it keeps modifying its width slightly, which triggers the resize observer, which modifies its width slightly, …
=> Fix useScrollIndication expansion issue

packages/odyssey-storybook/src/components/odyssey-labs/DataView/dataFunctions.ts
There was a glitch in the code we provided to demonstrate how reordering works in the DataView. This fixes it.
=> Ensure storybook demo of row reordering actually reorders rows

packages/odyssey-react-mui/src/labs/DataView/DataView.test.tsx, packages/odyssey-react-mui/src/labs/DataView/DataView.tsx, packages/odyssey-react-mui/src/labs/DataView/componentTypes.ts, packages/odyssey-storybook/src/components/odyssey-labs/DataView/DataView.stories.tsx
IGA needs an `onPaginationChange` hook in the DataView to make it work properly with their `react-query` implementation; any team using a cursor-based pagination approach in the backend will need this too.
=> Add onPaginationChange hook to DataView

packages/odyssey-design-tokens/src/typography.json, packages/odyssey-react-mui/src/Typography.test.tsx, packages/odyssey-react-mui/src/Typography.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Typography/Typography.stories.tsx
[OKTA-803564](https://oktainc.atlassian.net/browse/OKTA-803564)
- Adds `Overline` typography component
- Only allow all caps when lang is 'en'
=> feat(odyssey-react-mui): add overline typography variant

packages/odyssey-react-mui/src/OdysseyTranslationProvider.types.ts, packages/odyssey-react-mui/src/i18n.ts, packages/odyssey-storybook/.storybook/preview.ts
- Adds Haitian Creole language support
=> feat(odyssey-react-mui): Add haitian creole to suported languages

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/theme/components.tsx
[DES-6571](https://oktainc.atlassian.net/browse/DES-6571)
- Wraps menu item when it gets long to ensure menu goes not grow in width
=> fix(odyssey-react-mui): wrap long menu items. Add sane max-height

packages/odyssey-react-mui/src/Tag.tsx, packages/odyssey-react-mui/src/theme/components.tsx
[DES-6564](https://oktainc.atlassian.net/browse/DES-6564)
* Adds disabled style for icon in `Tag` 
* Updates border behavior to align with Figma (Border only on disabled or clickable/selectable Tags)
* Adds Disabled `lowContrast`/`highContrast` specific style for text to align with Figma
=> Disabled tag style updates for icon

packages/odyssey-react-mui/src/theme/components.tsx
[DES-6605](https://oktainc.atlassian.net/browse/DES-6605)
Tags could be very long when 'selected'. This change limits them to ~55ch
covers up 'clear' button
'clear' button unobstructed
=> Truncate chips when rendered inside multi-selects

packages/odyssey-react-mui/src/Tag.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Tag/Tag.stories.tsx
[DES-6489](https://oktainc.atlassian.net/browse/DES-6489)
* Adds `small` tag variant to align with Figma
* Follows MUI sizing conventions for `Chip` (default Tag is called medium)
=> Small `Tag` variant

packages/odyssey-react-mui/src/labs/AppTile.tsx
Fixes a regression in the AppTile image dimensions spotted by @stephanieyoshimoto-okta.
=> fix: enforce AppTile image heighgt

packages/odyssey-react-mui/src/labs/DataView/TableLayoutContent.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DataView/DataView.stories.tsx
In DataView, the last column automatically expands to fill the remaining space. This is the intended behavior in _most_ scenarios.
In some cases, though, a team will manually set a different column to grow to fill the remaining space. Before this PR, that column would compete with the final column for space.
Now, DataView detects if any table columns have `grow: true` set. If they do, it won't force the last column to fill the remaining space.
Before:
After:
=> Smarter column expansion in DataView

packages/odyssey-react-mui/src/theme/components.tsx
[DES-6778](https://oktainc.atlassian.net/browse/DES-6778)
- Adds `width: 100%` to table to fix Chrom regression
=> fix(odyssey-react-mui): ensure table is 100% width

packages/odyssey-react-mui/src/labs/SideNav/SideNav.tsx, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
[OKTA-832344](https://oktainc.atlassian.net/browse/OKTA-832344)
Fixes bug in SideNav where sideNavItems are initially `[]`, then later populated with actual data (but are never rendered).
=> fix: bug in SideNav when sideNavItems comes delayed

packages/odyssey-react-mui/src/labs/UiShell/UiShell.tsx, packages/odyssey-react-mui/src/labs/UiShell/UiShellContent.tsx, packages/odyssey-react-mui/src/labs/UiShell/renderUiShell.tsx, packages/odyssey-storybook/src/components/odyssey-labs/UiShell/UiShell.stories.tsx
[OKTA-832948](https://oktainc.atlassian.net/browse/OKTA-832948)
Improves the first-render of the UiShell. Allows consumers to opt into which components should be initially visible during the phase before they're able to influence things via a call to setComponentProps. If present, SideNav has `isLoading`.
=> feat: better first-render options for UiShell

packages/odyssey-react-mui/src/theme/components.tsx
[DES-6770](https://oktainc.atlassian.net/browse/DES-6770)
Updates `Button` styles to match Nick's latest updates in Figma
**States that have changed:**
* Secondary hover
* Secondary Active
* Secondary disabled
* Floating/FloatingAction Hover
* Floating/FloatingAction Active
* Danger Secondary Hover
* Danger Secondary Disabled
This PR also adds support for the `MenuButton`'s "open" state aka `&[aria-expanded='true']` and applies the `:active` state styles when a `MenuButton` is in this state.
=> Update Button styles + support for aria-expanded

packages/odyssey-react-mui/src/labs/DataView/DataCard.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/DataView/DataView.stories.tsx
This PR brings the style of the `compact` variant of `DataCards` (cards within `DataView`) into conformity with the Figma mocks and suggestions from Alex and Nick.
The biggest change, in terms of scope, is that the card content now changes alignment depending on how much content is present (only in the `compact` variant). If there's just a title, for example, it's centered alongside the image; if there's a title + description + overline + button, however, it's aligned to the top of the image. This sounds complex, but looks visually correct in practice:
=> Update styles on compact cards

packages/odyssey-react-mui/src/labs/AppTile.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-labs/AppTile/AppTile.stories.tsx
This PR fixes a height issue with `AppTile` and adds the new `compact` variant required by End User Dashboard.
=> AppTile adjustments

packages/odyssey-react-mui/src/labs/UiShell/renderUiShell.test.tsx, packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.ts
[OKTA-838077](https://oktainc.atlassian.net/browse/OKTA-838077)
React 17 compatibility fix via Kevin. Rebased as patch for 1.28
=> React 17 compatibility (as patch to 1.28)

packages/odyssey-react-mui/src/labs/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavHeader.tsx, packages/odyssey-react-mui/src/labs/SideNav/SortableList/SortableItem.tsx, packages/odyssey-react-mui/src/labs/SideNav/SortableList/SortableList.tsx, packages/odyssey-react-mui/src/labs/SideNav/types.ts, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
=> fix: make sidenav header optional, allow items to be not sortable

yarn.lock
Feeding 2 birds with 1 scone:
- Resolves vuln issue with express in [OKTA-904213](https://oktainc.atlassian.net/browse/OKTA-804213)
- Indirectly resolves another vuln issue in `path-to-regexp` dependency, which is a dependency of express here [OKTA-803399](https://oktainc.atlassian.net/browse/OKTA-803399)
[OKTA-804213](https://oktainc.atlassian.net/browse/OKTA-804213)
- [n/a] I have confirmed this change with my designer and the Odyssey Design Team.
=> fix: addressed vuln issue with express with version bump

packages/odyssey-react-mui/src/Select.tsx, packages/odyssey-react-mui/src/labs/OdysseyPickers/PickerVirtualizationListBox.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavItemContent.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavLogo.tsx, packages/odyssey-react-mui/src/labs/SideNav/SideNavToggleButton.tsx, packages/odyssey-react-mui/src/labs/SideNav/types.ts, packages/odyssey-react-mui/src/labs/TopNav/UserProfile.tsx, packages/odyssey-react-mui/src/labs/TopNav/UserProfileMenuButton.tsx, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
[DES-6951](https://oktainc.atlassian.net/browse/DES-6951)
- Allows `translate` prop to be passed through to `UserProfile`'s `userName` and `orgName`
- Fixes virtualized listbox not calculating height correctly when one item is present
- Removes min-height on select menu
- Adds hard coded test selectors for sidenav toggle and logo
=> Pass translate to profile button and misc height issue fixes

packages/odyssey-react-mui/src/labs/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/labs/SideNav/SortableList/SortableList.tsx, packages/odyssey-react-mui/src/labs/SideNav/types.ts, packages/odyssey-storybook/src/components/odyssey-labs/SideNav/SideNav.stories.tsx
[OKTA-853942](https://oktainc.atlassian.net/browse/OKTA-853942)
fix: make sidenav nested items sortable by default
=> fix: make sidenav nested items sortable by default

packages/odyssey-react-mui/src/Accordion.tsx, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Accordion/Accordion.stories.tsx
[DES-6886](https://oktainc.atlassian.net/browse/DES-6886)
* Adds `borderless` variant to accordion to match Figma 
* Updates accordion storybook docs with correct prop type for label (`string` not `ReactNode`)
=> Add `Borderless` variant to Accordion

packages/odyssey-react-mui/src/Buttons/BaseMenuButton.tsx, packages/odyssey-react-mui/src/Buttons/index.ts, packages/odyssey-react-mui/src/labs/UserProfile.tsx, packages/odyssey-react-mui/src/labs/UserProfileMenuButton.tsx, packages/odyssey-storybook/.storybook/main.ts, packages/odyssey-storybook/package.json, packages/odyssey-storybook/src/components/odyssey-labs/UserProfileMenuButton/UserProfileMenuButton.stories.tsx, yarn.lock
[DES-6997](https://oktainc.atlassian.net/browse/DES-6997)
- Adds ability to show vertical divider
- Style UserProfileButton slightly differently(no set height, smaller block padding)
- Adds back storybook rtl addon
=> User menu button fixes

packages/odyssey-react-mui/src/createContrastColors.ts, packages/odyssey-react-mui/src/hexToRgb.ts, packages/odyssey-react-mui/src/theme/components.tsx, packages/odyssey-react-mui/src/theme/useContrastMode.test.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/NavAccordion.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavFooterContent.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavHeader.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavItemContent.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavToggleButton.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SortableList/SortableItem.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SortableList/SortableList.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/types.ts, packages/odyssey-react-mui/src/ui-shell/TopNav/TopNav.tsx, packages/odyssey-react-mui/src/ui-shell/UiShell.tsx, packages/odyssey-react-mui/src/ui-shell/UiShellColorsProvider.tsx, packages/odyssey-react-mui/src/ui-shell/UiShellContent.tsx, packages/odyssey-react-mui/src/ui-shell/UiShellProvider.tsx, packages/odyssey-react-mui/src/ui-shell/renderUiShell.tsx, packages/odyssey-react-mui/src/useContrastMode.tsx, packages/odyssey-storybook/src/components/odyssey-ui-shell/UiShell/UiShell.stories.tsx
[DES-6894](https://oktainc.atlassian.net/browse/DES-6894)
- Adds ability to users to pass in custom color for side nav background
- Adds ability to users to pass in custom color for top nav background
- Adds ability to users to pass in custom color for app content area background
- Adds logic to change text color based on background color's luminance value
=> UI shell customization

packages/odyssey-react-mui/src/SearchField.tsx, packages/odyssey-react-mui/src/theme/components.tsx
…highContrast style
[DES-7007](https://oktainc.atlassian.net/browse/DES-7007)
- Makes SearchField contrastMode aware
- Removes border when SearchField is rendered on a gray background
=> Remove SearchField border on gray background

packages/odyssey-react-mui/src/labs/UserProfile.tsx
[OKTA-856128](https://oktainc.atlassian.net/browse/OKTA-856128)
When the translate="no" attribute is placed on the container (and test infrastructure looks for these to rule out english leaks), the resulting text content is all combined. The pre-Odyssey behavior is that the attribute is instead on the individual elements within this area. This updates where the translate attribute is placed to be more explicit.
=> fix: move translate attribute to paragraph element

packages/odyssey-storybook/package.json, yarn.lock
[OKTA-849447](https://oktainc.atlassian.net/browse/OKTA-849447)
A CI and install-time change that removes the dependency of `@applitools/eyes-storybook` as an installable package and instead makes it a CI-runtime executable.
This addresses the vuln ticket linked above to prevent `puppeteer` (a dependency of `eyes-storybook`) from running its `postinstall` script whenever the dependencies of the odyssey repo are installed.
More info here: https://socket.dev/npm/package/puppeteer/alerts/23.5.1?alert_name=installScripts
The fix here is to execute `eyes-storybook` as a runtime executable only when needed in CI, by having yarn download and execute `eyes-storybook` when the script `ci:visualRegressionTest` is invoked.
The change also impacts the invocation of `dev:visualRegressionTest` locally …
=> ci: execute eyes-storybook-in-ci-only

packages/odyssey-design-tokens/config.cjs
[OKTA-857768](https://oktainc.atlassian.net/browse/OKTA-857768)
Generate scss file and include it in the generated source that is to be published for this package.
Creates a `dist/index.scss` file of the ODS tokens.
=> fix: generate scss file to include in published package

packages/odyssey-react-mui/src/RadioGroup.tsx, packages/odyssey-storybook/src/components/odyssey-mui/RadioGroup/RadioGroup.stories.tsx
[DES-7006](https://oktainc.atlassian.net/browse/DES-7006)
* After refactoring in the [read-only PR for radios](https://github.com/okta/odyssey/pull/2305/files#diff-a337770904c0a51966e0e57d6f18157a72927ef5783d32e319042cd5fdb772c3R110), we inadvertently removed the ability to set individual radios as disabled (or read-only). This PR restores that functionality.
* Also adds a story demonstrating how to do this.
=> Allow each radio in radio group to be disabled/read-only

packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.tsx
[860405](https://oktainc.atlassian.net/browse/860405)
fix: sidenav footer component does not use the theme background color
Before:
After:
=> fix: sidenav footer component does not use the theme background color

packages/odyssey-react-mui/src/Breadcrumbs.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Breadcrumbs/Breadcrumbs.stories.tsx
[OKTA-867708](https://oktainc.atlassian.net/browse/OKTA-867708)
- feat: add onClick handler to Breadcrumb
Adding onClick to the component so it can be routing via the routing library of choice of the consumer. Keeping href required as to retain working functionality without JavaScript. onClick wrapper needs to prevent default and stop propagation.
No visual implications with this work.
=> [odyssey-react-mui] add onClick handler to Breadcrumb

packages/odyssey-react-mui/src/Breadcrumbs.tsx, packages/odyssey-storybook/src/components/odyssey-mui/Breadcrumbs/Breadcrumbs.stories.tsx
[OKTA-869652](https://oktainc.atlassian.net/browse/OKTA-869652)
feat: add noninteractive mode to breadcrumb item (by making href optional)
=> feat: add noninteractive mode to breadcrumb item (by making href optional)

packages/odyssey-react-mui/src/ui-shell/NarrowUiShellContent.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNavLogo.tsx
[OKTA-887123](https://oktainc.atlassian.net/browse/OKTA-887123)
Narrow UI Shell's icons to open the side nav and user profile were missing `data-se` props used by existing Selenium tests.
=> fix: add data-se to narrow UI Shell

packages/odyssey-react-mui/src/Dialog.tsx, packages/odyssey-react-mui/src/HtmlProps.ts, packages/odyssey-react-mui/src/Typography.test.tsx, packages/odyssey-react-mui/src/Typography.tsx
[OKTA-881699](https://oktainc.atlassian.net/browse/OKTA-881699)
This PR is created to workaround some A11Y issues reported in SIW and EUS
Changes:
1. support role as a prop in `Typography` component
2. make sure close button is not read out in title by screen reader
no component/s visual change is introduced in this PR
- [OKTA-874282](https://oktainc.atlassian.net/browse/OKTA-874282)
- [OKTA-874278](https://oktainc.atlassian.net/browse/OKTA-874278)
=> feat: support role in Typography and Dialog title

packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.test.tsx, packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.ts
Current implementation only mounts the react root in the constructor. Move that to the connectedCallback so we’re never operating on a root which has already been unmounted. This is required for monolith where other apps controlling the dom may cause our app to unmount by removing the elements it’s mounted to.
[OKTA-904979](https://oktainc.atlassian.net/browse/OKTA-904979)
=> fix: fixed render function

packages/odyssey-react-mui/src/ui-shell/useMatchAppElementToUiShellAppArea.ts
[OKTA-907628](https://oktainc.atlassian.net/browse/OKTA-907628)
When updating SPA to use the Unified Look & Feel UI Shell component there was an issue where the content of the page was overflowing such that the page was extending beyond the visible screen. After debugging with @KevinGhadyani-Okta the issue was identified as the box-sizing property on the app container element needing to be set to border-box.
=> [UI] [package: odyssey-react-mui] Add box sizing border box to app container element

.gitignore, packages/odyssey-react-mui/package.json, packages/odyssey-react-mui/scripts/updateWebComponentVersion.ts, packages/odyssey-react-mui/src/ui-shell/renderUiShell.browser.test.ts, packages/odyssey-react-mui/src/web-component/odysseyWebComponentVersion.generated.ts, packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.browser.test.tsx, packages/odyssey-react-mui/src/web-component/renderReactInWebComponent.ts, packages/odyssey-react-mui/tsconfig.json, scripts/publish-packages.sh
- adds script for generating versioned web component name
This is needed so that different versions of odyssey with 
possibly different web component implementations can coexist
without overwriting eachother.
- add role selector for web component
Allows tests to find the web component without it having a 
consistent name
- add webComponentName parameter
Allows users to define their own web component name if needed.
Defaults to the standard versioned name.
- update web component class to use document.createElement(wcName)
Web component spec indicates that document.createElement and the
`new` style of constructing should be equivalent. As part of that
I removed the getReactComponent function from the constructor 
parameters, since that's not possible with createElement.
Also updates …
=> feat: Fix name collision issues with renderReactInWebComponent

packages/odyssey-react-mui/src/ui-shell/NarrowUiShellContent.tsx, packages/odyssey-react-mui/src/ui-shell/SideNav/SideNav.tsx, packages/odyssey-react-mui/src/ui-shell/WideUiShellContent.tsx
[OKTA-928189](https://oktainc.atlassian.net/browse/OKTA-928189)
- Side nav auto-closes in narrow view, and it can be re-opened now. No more collapsing and staying collapsed.
Hard to take a picture. I verified Narrow, Wide w/ collapsed side-nav, and Wide.
=> fix: side nav stuck closed after clicking item in narrow view

packages/odyssey-react-mui/src/EmptyState.tsx
[OKTA-923439](https://oktainc.atlassian.net/browse/OKTA-923439)
Update style of empty state of DataView.
Before:
After:
=> fix: update style of empty state in DataView
